-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: 4cf06f9ca27b7b8eedb07d0fb854e49b59c943ea8ba0340b8a2828728e162c33
-- Preserve these theorem statements when completing the exercise.

-- contrapositive
section
set_option autoImplicit true in
example : ∀ (P Q : Prop), (P → Q) → Not Q → Not P := @contrapositive
#print axioms contrapositive
end

-- contrapositive_reverse
section
set_option autoImplicit true in
example : ∀ (P Q : Prop), (Not Q → Not P) → P → Q := @contrapositive_reverse
#print axioms contrapositive_reverse
end

-- not_or_of_imp
section
set_option autoImplicit true in
example : ∀ (P Q : Prop), (P → Q) → Or (Not P) Q := @not_or_of_imp
#print axioms not_or_of_imp
end
