-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: 71a435d396fab43ce828311aeba7c50879fb05f0e58ea410957af34c2b180614
-- Preserve these theorem statements when completing the exercise.

-- by_contradiction_example
section
set_option autoImplicit true in
example : ∀ (P Q : Prop), (Not P → Q) → Not Q → P := @by_contradiction_example
#print axioms by_contradiction_example
end

-- dne
section
set_option autoImplicit true in
example : ∀ (P : Prop), Not (Not P) → P := @dne
#print axioms dne
end

-- em_example
section
set_option autoImplicit true in
example : ∀ (P : Prop), Or P (Not P) := @em_example
#print axioms em_example
end
