-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: 4b1f7b32cad2930d26589a174c89ffeb24662899d04f66b6a0b42ff1792b2477
-- Preserve these theorem statements when completing the exercise.

-- myAdd_zero
section
set_option autoImplicit true in
example : ∀ (n : Nat), @Eq.{1} Nat (myAdd n (@OfNat.ofNat.{0} Nat (nat_lit 0) (instOfNatNat (nat_lit 0)))) n := @myAdd_zero
#print axioms myAdd_zero
end

-- myAdd_zero_left
section
set_option autoImplicit true in
example : ∀ (n : Nat), @Eq.{1} Nat (myAdd (@OfNat.ofNat.{0} Nat (nat_lit 0) (instOfNatNat (nat_lit 0))) n) n := @myAdd_zero_left
#print axioms myAdd_zero_left
end
