-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: a99076c002edd7bb5f2fa1a2394b2ce124a455b9a48198bc15a2dd690939e22f
-- Preserve these theorem statements when completing the exercise.

-- myLength_append
section
set_option autoImplicit true in
example : ∀ {α : Type u_1} (l1 l2 : List.{u_1} α),
  @Eq.{1} Nat
    (@myLength.{u_1} α
      (@HAppend.hAppend.{u_1, u_1, u_1} (List.{u_1} α) (List.{u_1} α) (List.{u_1} α)
        (@instHAppendOfAppend.{u_1} (List.{u_1} α) (@List.instAppend.{u_1} α)) l1 l2))
    (@HAdd.hAdd.{0, 0, 0} Nat Nat Nat (@instHAdd.{0} Nat instAddNat) (@myLength.{u_1} α l1) (@myLength.{u_1} α l2)) := @myLength_append
#print axioms myLength_append
end
