-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: 00ca3ad511a0f27a020243d154c7499380546ebad1f7c676045a9c4660c98367
-- Preserve these theorem statements when completing the exercise.

-- Analysis.MyReal.approx
section
set_option autoImplicit true in
example : ∀ (x : Analysis.MyReal) {ε : Analysis.MyRat},
  @LT.lt.{0} Analysis.MyRat Analysis.MyRat.instLT
      (@OfNat.ofNat.{0} Analysis.MyRat (nat_lit 0) (@Zero.toOfNat0.{0} Analysis.MyRat Analysis.MyRat.instZero)) ε →
    @Exists.{1} Analysis.MyRat fun q =>
      @LT.lt.{0} Analysis.MyReal Analysis.MyReal.instLT
        (@Analysis.Abs.abs.{0} Analysis.MyReal Analysis.MyReal.instAbs
          (@HSub.hSub.{0, 0, 0} Analysis.MyReal Analysis.MyReal Analysis.MyReal
            (@instHSub.{0} Analysis.MyReal Analysis.MyReal.instSub) x (Analysis.MyReal.ofRat q)))
        (Analysis.MyReal.ofRat ε) := @Analysis.MyReal.approx
#print axioms Analysis.MyReal.approx
end
