-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: afbaac23b98429b9460de75e7d301934aa8ff38865feb1d08ac4b3e05916e0ca
-- Preserve these theorem statements when completing the exercise.

-- Analysis.MyReal.approx_isCauchy
section
set_option autoImplicit true in
example : ∀ {x : Nat → Analysis.MyReal} {q : Nat → Analysis.MyRat},
  @Analysis.IsCauchySeq.{0} Analysis.MyReal Analysis.instMetricSpaceMyReal x →
    (∀ (k : Nat),
        @LT.lt.{0} Analysis.MyReal Analysis.MyReal.instLT
          (@Analysis.Abs.abs.{0} Analysis.MyReal Analysis.MyReal.instAbs
            (@HSub.hSub.{0, 0, 0} Analysis.MyReal Analysis.MyReal Analysis.MyReal
              (@instHSub.{0} Analysis.MyReal Analysis.MyReal.instSub) (x k) (Analysis.MyReal.ofRat (q k))))
          (Analysis.MyReal.ofRat (Analysis.MyReal.tolSeq k))) →
      Analysis.IsCauchy q := @Analysis.MyReal.approx_isCauchy
#print axioms Analysis.MyReal.approx_isCauchy
end
