-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: dc170d6f4fd79dbe9d20752dde09f48cd6faf14aea7c83fc2d0f93f954e4a136
-- Preserve these theorem statements when completing the exercise.

-- Analysis.MyReal.complete
section
set_option autoImplicit true in
example : @Analysis.IsComplete.{0} Analysis.MyReal Analysis.instMetricSpaceMyReal := @Analysis.MyReal.complete
#print axioms Analysis.MyReal.complete
end
