-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: dfc57eaf9c98d2d6c076a8aef6e9ace9c209ddf65858c8a5022bb36b65f9ec14
-- Preserve these theorem statements when completing the exercise.

-- Analysis.MyReal.complete
section
set_option autoImplicit true in
example : @Analysis.IsComplete.{0} Analysis.MyReal Analysis.instMetricSpaceMyReal := @Analysis.MyReal.complete
#print axioms Analysis.MyReal.complete
end
