-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: 649ec5794bc0cc4959514fcfa72e38886c271b6cd777d686d552e3f5996b0a2f
-- Preserve these theorem statements when completing the exercise.

-- Analysis.MyReal.tendsto_of_approx
section
set_option autoImplicit true in
example : ∀ {x : Nat → Analysis.MyReal} {q : Nat → Analysis.MyRat} {L : Analysis.MyReal},
  (∀ (k : Nat),
      @LT.lt.{0} Analysis.MyReal Analysis.MyReal.instLT
        (@Analysis.Abs.abs.{0} Analysis.MyReal Analysis.MyReal.instAbs
          (@HSub.hSub.{0, 0, 0} Analysis.MyReal Analysis.MyReal Analysis.MyReal
            (@instHSub.{0} Analysis.MyReal Analysis.MyReal.instSub) (x k) (Analysis.MyReal.ofRat (q k))))
        (Analysis.MyReal.ofRat (Analysis.MyReal.tolSeq k))) →
    Analysis.MyReal.Tendsto (fun k => Analysis.MyReal.ofRat (q k)) L →
      @Analysis.Converges.{0} Analysis.MyReal Analysis.instMetricSpaceMyReal x L := @Analysis.MyReal.tendsto_of_approx
#print axioms Analysis.MyReal.tendsto_of_approx
end
