-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: 1fc13b490dbe07fe0968426f48b94fe86054a5532fe6e4f3ab32eb85a32f2195
-- Preserve these theorem statements when completing the exercise.

-- Analysis.MyRat.abs_lt
section
set_option autoImplicit true in
example : ∀ {x y : Analysis.MyRat},
  Iff
    (@LT.lt.{0} Analysis.MyRat Analysis.MyRat.instLT (@Analysis.Abs.abs.{0} Analysis.MyRat Analysis.MyRat.instAbs x) y)
    (And (@LT.lt.{0} Analysis.MyRat Analysis.MyRat.instLT (@Neg.neg.{0} Analysis.MyRat Analysis.MyRat.instNeg y) x)
      (@LT.lt.{0} Analysis.MyRat Analysis.MyRat.instLT x y)) := @Analysis.MyRat.abs_lt
#print axioms Analysis.MyRat.abs_lt
end
