-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: fc9436ec5bfa425eafca67f4889bca3f3ff0e83e71b5a486d6a7f38c0dd8df60
-- Preserve these theorem statements when completing the exercise.

-- Analysis.MyRat.abs_neg
section
set_option autoImplicit true in
example : ∀ (x : Analysis.MyRat),
  @Eq.{1} Analysis.MyRat
    (@Analysis.Abs.abs.{0} Analysis.MyRat Analysis.MyRat.instAbs (@Neg.neg.{0} Analysis.MyRat Analysis.MyRat.instNeg x))
    (@Analysis.Abs.abs.{0} Analysis.MyRat Analysis.MyRat.instAbs x) := @Analysis.MyRat.abs_neg
#print axioms Analysis.MyRat.abs_neg
end
