-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: 610eadf4d0a1c65a39af726fef6b737303dc23324693de4e0c20d9774f91a2ef
-- Preserve these theorem statements when completing the exercise.

-- Analysis.MyRat.abs_add_le
section
set_option autoImplicit true in
example : ∀ (x y : Analysis.MyRat),
  @LE.le.{0} Analysis.MyRat Analysis.MyRat.instLE
    (@Analysis.Abs.abs.{0} Analysis.MyRat Analysis.MyRat.instAbs
      (@HAdd.hAdd.{0, 0, 0} Analysis.MyRat Analysis.MyRat Analysis.MyRat
        (@instHAdd.{0} Analysis.MyRat Analysis.MyRat.instAdd) x y))
    (@HAdd.hAdd.{0, 0, 0} Analysis.MyRat Analysis.MyRat Analysis.MyRat
      (@instHAdd.{0} Analysis.MyRat Analysis.MyRat.instAdd)
      (@Analysis.Abs.abs.{0} Analysis.MyRat Analysis.MyRat.instAbs x)
      (@Analysis.Abs.abs.{0} Analysis.MyRat Analysis.MyRat.instAbs y)) := @Analysis.MyRat.abs_add_le
#print axioms Analysis.MyRat.abs_add_le
end
