-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: 026dac70a76c87b39db1bde7c0ec90d2814a459ed223f86d68c45f64e21d9f3a
-- Preserve these theorem statements when completing the exercise.

-- Analysis.MyRat.abs_nonneg
section
set_option autoImplicit true in
example : ∀ (x : Analysis.MyRat),
  @LE.le.{0} Analysis.MyRat Analysis.MyRat.instLE
    (@OfNat.ofNat.{0} Analysis.MyRat (nat_lit 0) (@Zero.toOfNat0.{0} Analysis.MyRat Analysis.MyRat.instZero))
    (@Analysis.Abs.abs.{0} Analysis.MyRat Analysis.MyRat.instAbs x) := @Analysis.MyRat.abs_nonneg
#print axioms Analysis.MyRat.abs_nonneg
end
