-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: 7de8381982683e2a9450465d27e538a0e628ff254ed2b02846eb7232eaf074d2
-- Preserve these theorem statements when completing the exercise.

-- Analysis.MyRat.abs_mul
section
set_option autoImplicit true in
example : ∀ (x y : Analysis.MyRat),
  @Eq.{1} Analysis.MyRat
    (@Analysis.Abs.abs.{0} Analysis.MyRat Analysis.MyRat.instAbs
      (@HMul.hMul.{0, 0, 0} Analysis.MyRat Analysis.MyRat Analysis.MyRat
        (@instHMul.{0} Analysis.MyRat Analysis.MyRat.instMul) x y))
    (@HMul.hMul.{0, 0, 0} Analysis.MyRat Analysis.MyRat Analysis.MyRat
      (@instHMul.{0} Analysis.MyRat Analysis.MyRat.instMul)
      (@Analysis.Abs.abs.{0} Analysis.MyRat Analysis.MyRat.instAbs x)
      (@Analysis.Abs.abs.{0} Analysis.MyRat Analysis.MyRat.instAbs y)) := @Analysis.MyRat.abs_mul
#print axioms Analysis.MyRat.abs_mul
end
