-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: 75d4807b821a99dfbf28a98b2f00c53aceb8b4fa610ea47181b8c7023333a576
-- Preserve these theorem statements when completing the exercise.

-- Analysis.MyRat.add_le_add_left
section
set_option autoImplicit true in
example : ∀ {y z : Analysis.MyRat} (x : Analysis.MyRat),
  @LE.le.{0} Analysis.MyRat Analysis.MyRat.instLE y z →
    @LE.le.{0} Analysis.MyRat Analysis.MyRat.instLE
      (@HAdd.hAdd.{0, 0, 0} Analysis.MyRat Analysis.MyRat Analysis.MyRat
        (@instHAdd.{0} Analysis.MyRat Analysis.MyRat.instAdd) x y)
      (@HAdd.hAdd.{0, 0, 0} Analysis.MyRat Analysis.MyRat Analysis.MyRat
        (@instHAdd.{0} Analysis.MyRat Analysis.MyRat.instAdd) x z) := @Analysis.MyRat.add_le_add_left
#print axioms Analysis.MyRat.add_le_add_left
end
