-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: 92deec97de5f6e2d5ccc226007db3c248bda877f897855fc82da864fc0657c45
-- Preserve these theorem statements when completing the exercise.

-- Analysis.MyRat.add_lt_add_left
section
set_option autoImplicit true in
example : ∀ {y z : Analysis.MyRat} (x : Analysis.MyRat),
  @LT.lt.{0} Analysis.MyRat Analysis.MyRat.instLT y z →
    @LT.lt.{0} Analysis.MyRat Analysis.MyRat.instLT
      (@HAdd.hAdd.{0, 0, 0} Analysis.MyRat Analysis.MyRat Analysis.MyRat
        (@instHAdd.{0} Analysis.MyRat Analysis.MyRat.instAdd) x y)
      (@HAdd.hAdd.{0, 0, 0} Analysis.MyRat Analysis.MyRat Analysis.MyRat
        (@instHAdd.{0} Analysis.MyRat Analysis.MyRat.instAdd) x z) := @Analysis.MyRat.add_lt_add_left
#print axioms Analysis.MyRat.add_lt_add_left
end
