-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: 1fc1921d962551b50db52ebd1e82f8aa5d784abf79d0379f1afcef45f8a53ae3
-- Preserve these theorem statements when completing the exercise.

-- Analysis.MyRat.archimedean
section
set_option autoImplicit true in
example : ∀ (x : Analysis.MyRat),
  @Exists.{1} Nat fun n =>
    @LT.lt.{0} Analysis.MyRat Analysis.MyRat.instLT x (Analysis.MyRat.ofInt (@Nat.cast.{0} Int instNatCastInt n)) := @Analysis.MyRat.archimedean
#print axioms Analysis.MyRat.archimedean
end
