-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: e515b5033439bef4dcff51aad1922d4d518d3846a4bc6efafa6ab59036affcfe
-- Preserve these theorem statements when completing the exercise.

-- Analysis.MyRat.exists_between
section
set_option autoImplicit true in
example : ∀ {x y : Analysis.MyRat},
  @LT.lt.{0} Analysis.MyRat Analysis.MyRat.instLT x y →
    @Exists.{1} Analysis.MyRat fun z =>
      And (@LT.lt.{0} Analysis.MyRat Analysis.MyRat.instLT x z) (@LT.lt.{0} Analysis.MyRat Analysis.MyRat.instLT z y) := @Analysis.MyRat.exists_between
#print axioms Analysis.MyRat.exists_between
end
