-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: 0a099c4107c08d7d65c89c2f07b664a3465436ac494ff2bcb95f79e75eaaed3a
-- Preserve these theorem statements when completing the exercise.

-- Analysis.MyRat.le_refl
section
set_option autoImplicit true in
example : ∀ (x : Analysis.MyRat), @LE.le.{0} Analysis.MyRat Analysis.MyRat.instLE x x := @Analysis.MyRat.le_refl
#print axioms Analysis.MyRat.le_refl
end
