-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: 3947f4e268e054345fd8c4f17a0826369363b999ba8a70ef6a8a135b39ab19cf
-- Preserve these theorem statements when completing the exercise.

-- Analysis.MyRat.le_trans
section
set_option autoImplicit true in
example : ∀ {x y z : Analysis.MyRat},
  @LE.le.{0} Analysis.MyRat Analysis.MyRat.instLE x y →
    @LE.le.{0} Analysis.MyRat Analysis.MyRat.instLE y z → @LE.le.{0} Analysis.MyRat Analysis.MyRat.instLE x z := @Analysis.MyRat.le_trans
#print axioms Analysis.MyRat.le_trans
end
