-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: 9fc4a88e319af87362a53c00606a7c8a567f00b05ec439ef05c09d24b2e00a81
-- Preserve these theorem statements when completing the exercise.

-- Analysis.MyRat.lt_irrefl
section
set_option autoImplicit true in
example : ∀ (x : Analysis.MyRat), Not (@LT.lt.{0} Analysis.MyRat Analysis.MyRat.instLT x x) := @Analysis.MyRat.lt_irrefl
#print axioms Analysis.MyRat.lt_irrefl
end
