-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: f6fe97f36d9a5c879c5abb6b64ecbe153b12d269d406eebf75f90b184a4d75e4
-- Preserve these theorem statements when completing the exercise.

-- Analysis.MyRat.lt_trans
section
set_option autoImplicit true in
example : ∀ {x y z : Analysis.MyRat},
  @LT.lt.{0} Analysis.MyRat Analysis.MyRat.instLT x y →
    @LT.lt.{0} Analysis.MyRat Analysis.MyRat.instLT y z → @LT.lt.{0} Analysis.MyRat Analysis.MyRat.instLT x z := @Analysis.MyRat.lt_trans
#print axioms Analysis.MyRat.lt_trans
end
