-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: 3c522dd98fe0a1ca3eac0a782c8ceeb6295cff82eb37cf600fd367509f9d7be8
-- Preserve these theorem statements when completing the exercise.

-- Analysis.MyRat.lt_trichotomy
section
set_option autoImplicit true in
example : ∀ (x y : Analysis.MyRat),
  Or (@LT.lt.{0} Analysis.MyRat Analysis.MyRat.instLT x y)
    (Or (@Eq.{1} Analysis.MyRat x y) (@LT.lt.{0} Analysis.MyRat Analysis.MyRat.instLT y x)) := @Analysis.MyRat.lt_trichotomy
#print axioms Analysis.MyRat.lt_trichotomy
end
