-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: aa65fe0165d93248a6305edec3e240ae0e2a712ce5ab1401d72684d5fc0aadf5
-- Preserve these theorem statements when completing the exercise.

-- Analysis.MyRat.mul_pos
section
set_option autoImplicit true in
example : ∀ {x y : Analysis.MyRat},
  @LT.lt.{0} Analysis.MyRat Analysis.MyRat.instLT
      (@OfNat.ofNat.{0} Analysis.MyRat (nat_lit 0) (@Zero.toOfNat0.{0} Analysis.MyRat Analysis.MyRat.instZero)) x →
    @LT.lt.{0} Analysis.MyRat Analysis.MyRat.instLT
        (@OfNat.ofNat.{0} Analysis.MyRat (nat_lit 0) (@Zero.toOfNat0.{0} Analysis.MyRat Analysis.MyRat.instZero)) y →
      @LT.lt.{0} Analysis.MyRat Analysis.MyRat.instLT
        (@OfNat.ofNat.{0} Analysis.MyRat (nat_lit 0) (@Zero.toOfNat0.{0} Analysis.MyRat Analysis.MyRat.instZero))
        (@HMul.hMul.{0, 0, 0} Analysis.MyRat Analysis.MyRat Analysis.MyRat
          (@instHMul.{0} Analysis.MyRat Analysis.MyRat.instMul) x y) := @Analysis.MyRat.mul_pos
#print axioms Analysis.MyRat.mul_pos
end
