-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: db15ed1943b662b45fd4e8dde6bada484cb6c74ff013e46cb1955fc85c58e092
-- Preserve these theorem statements when completing the exercise.

-- Algebra.map_inv
section
set_option autoImplicit true in
example : ∀ {G : Type u_1} {H : Type u_2} [inst : Algebra.Group.{u_1} G] [inst_1 : Algebra.Group.{u_2} H]
  (f : @Algebra.GroupHom.{u_1, u_2} G H inst inst_1) (a : G),
  @Eq.{u_2 + 1} H
    (@Algebra.GroupHom.toFun.{u_1, u_2} G H inst inst_1 f (@Inv.inv.{u_1} G (@Algebra.Group.toInv.{u_1} G inst) a))
    (@Inv.inv.{u_2} H (@Algebra.Group.toInv.{u_2} H inst_1) (@Algebra.GroupHom.toFun.{u_1, u_2} G H inst inst_1 f a)) := @Algebra.map_inv
#print axioms Algebra.map_inv
end
