-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: 5a2bdfb6de9081b994dfbd7c8f5f4ec96c4545a902ef223ae1aaeeeb00794792
-- Preserve these theorem statements when completing the exercise.

-- Algebra.map_mul_inv
section
set_option autoImplicit true in
example : ∀ {G : Type u_1} {H : Type u_2} [inst : Algebra.Group.{u_1} G] [inst_1 : Algebra.Group.{u_2} H]
  (f : @Algebra.GroupHom.{u_1, u_2} G H inst inst_1) (a b : G),
  @Eq.{u_2 + 1} H
    (@Algebra.GroupHom.toFun.{u_1, u_2} G H inst inst_1 f
      (@HMul.hMul.{u_1, u_1, u_1} G G G
        (@instHMul.{u_1} G
          (@Algebra.Magma.toMul.{u_1} G
            (@Algebra.Semigroup.toMagma.{u_1} G
              (@Algebra.Monoid.toSemigroup.{u_1} G (@Algebra.Group.toMonoid.{u_1} G inst)))))
        a (@Inv.inv.{u_1} G (@Algebra.Group.toInv.{u_1} G inst) b)))
    (@HMul.hMul.{u_2, u_2, u_2} H H H
      (@instHMul.{u_2} H
        (@Algebra.Magma.toMul.{u_2} H
          (@Algebra.Semigroup.toMagma.{u_2} H
            (@Algebra.Monoid.toSemigroup.{u_2} H (@Algebra.Group.toMonoid.{u_2} H inst_1)))))
      (@Algebra.GroupHom.toFun.{u_1, u_2} G H inst inst_1 f a)
      (@Inv.inv.{u_2} H (@Algebra.Group.toInv.{u_2} H inst_1) (@Algebra.GroupHom.toFun.{u_1, u_2} G H inst inst_1 f b))) := @Algebra.map_mul_inv
#print axioms Algebra.map_mul_inv
end
