-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: ebf385d2f35ffe128052c66e415db4f48f77f7726ab84749df12cd31646a0e7e
-- Preserve these theorem statements when completing the exercise.

-- Algebra.map_one
section
set_option autoImplicit true in
example : ∀ {G : Type u_1} {H : Type u_2} [inst : Algebra.Group.{u_1} G] [inst_1 : Algebra.Group.{u_2} H]
  (f : @Algebra.GroupHom.{u_1, u_2} G H inst inst_1),
  @Eq.{u_2 + 1} H
    (@Algebra.GroupHom.toFun.{u_1, u_2} G H inst inst_1 f
      (@OfNat.ofNat.{u_1} G (nat_lit 1)
        (@One.toOfNat1.{u_1} G (@Algebra.Monoid.toOne.{u_1} G (@Algebra.Group.toMonoid.{u_1} G inst)))))
    (@OfNat.ofNat.{u_2} H (nat_lit 1)
      (@One.toOfNat1.{u_2} H (@Algebra.Monoid.toOne.{u_2} H (@Algebra.Group.toMonoid.{u_2} H inst_1)))) := @Algebra.map_one
#print axioms Algebra.map_one
end
