-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: 59c0840ae2afd07b7d669a8bb944c8e2dbcd5fb419978bbaf0e6dacc2ef029aa
-- Preserve these theorem statements when completing the exercise.

-- Algebra.map_div
section
set_option autoImplicit true in
example : ∀ {G : Type u_1} {H : Type u_2} [inst : Algebra.Group.{u_1} G] [inst_1 : Algebra.Group.{u_2} H]
  (f : @Algebra.GroupHom.{u_1, u_2} G H inst inst_1) (a b : G),
  @Eq.{u_2 + 1} H
    (@Algebra.GroupHom.toFun.{u_1, u_2} G H inst inst_1 f
      (@HDiv.hDiv.{u_1, u_1, u_1} G G G (@instHDiv.{u_1} G (@Algebra.instGroupDiv.{u_1} G inst)) a b))
    (@HDiv.hDiv.{u_2, u_2, u_2} H H H (@instHDiv.{u_2} H (@Algebra.instGroupDiv.{u_2} H inst_1))
      (@Algebra.GroupHom.toFun.{u_1, u_2} G H inst inst_1 f a) (@Algebra.GroupHom.toFun.{u_1, u_2} G H inst inst_1 f b)) := @Algebra.map_div
#print axioms Algebra.map_div
end
