-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: 215dc180e4d7327f8becb12e86a6f404acf2b4a23b85c38b5dacc6a781b71cab
-- Preserve these theorem statements when completing the exercise.

-- Analysis.Converges.isCauchySeq
section
set_option autoImplicit true in
example : ∀ {X : Type u_1} [inst : Analysis.MetricSpace.{u_1} X] {x : Nat → X} {L : X},
  @Analysis.Converges.{u_1} X inst x L → @Analysis.IsCauchySeq.{u_1} X inst x := @Analysis.Converges.isCauchySeq
#print axioms Analysis.Converges.isCauchySeq
end
