-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: f198698f2e328026e0a683385028691bdb6623445e737ea01350b2e15f1c2f3c
-- Preserve these theorem statements when completing the exercise.

-- Analysis.Converges.const
section
set_option autoImplicit true in
example : ∀ {X : Type u_1} [inst : Analysis.MetricSpace.{u_1} X] (a : X), @Analysis.Converges.{u_1} X inst (fun x => a) a := @Analysis.Converges.const
#print axioms Analysis.Converges.const
end
