-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: 228099f0db6c79f46759a23c8d91a2443320a86c979ac2e69c18c71b190dd1ba
-- Preserve these theorem statements when completing the exercise.

-- double_0
section
set_option autoImplicit true in
example : @Eq.{1} Nat (double (@OfNat.ofNat.{0} Nat (nat_lit 0) (instOfNatNat (nat_lit 0))))
  (@OfNat.ofNat.{0} Nat (nat_lit 0) (instOfNatNat (nat_lit 0))) := @double_0
#print axioms double_0
end

-- double_2_is_add
section
set_option autoImplicit true in
example : @Eq.{1} Nat (double (@OfNat.ofNat.{0} Nat (nat_lit 2) (instOfNatNat (nat_lit 2))))
  (@HAdd.hAdd.{0, 0, 0} Nat Nat Nat (@instHAdd.{0} Nat instAddNat)
    (@OfNat.ofNat.{0} Nat (nat_lit 2) (instOfNatNat (nat_lit 2)))
    (@OfNat.ofNat.{0} Nat (nat_lit 2) (instOfNatNat (nat_lit 2)))) := @double_2_is_add
#print axioms double_2_is_add
end

-- double_3
section
set_option autoImplicit true in
example : @Eq.{1} Nat (double (@OfNat.ofNat.{0} Nat (nat_lit 3) (instOfNatNat (nat_lit 3))))
  (@OfNat.ofNat.{0} Nat (nat_lit 6) (instOfNatNat (nat_lit 6))) := @double_3
#print axioms double_3
end

-- four_is_even
section
set_option autoImplicit true in
example : @Eq.{1} Bool (isEven (@OfNat.ofNat.{0} Nat (nat_lit 4) (instOfNatNat (nat_lit 4)))) Bool.true := @four_is_even
#print axioms four_is_even
end
