-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: bf5e8fa144e9df1871cb98c8f2f5534771062610dfb5d06d8017dcf2de5c3334
-- Preserve these theorem statements when completing the exercise.

-- double_double
section
set_option autoImplicit true in
example : ∀ (n : Nat),
  @Eq.{1} Nat (double (double n))
    (@HMul.hMul.{0, 0, 0} Nat Nat Nat (@instHMul.{0} Nat instMulNat)
      (@OfNat.ofNat.{0} Nat (nat_lit 4) (instOfNatNat (nat_lit 4))) n) := @double_double
#print axioms double_double
end

-- double_is_mul2
section
set_option autoImplicit true in
example : ∀ (n : Nat),
  @Eq.{1} Nat (double n)
    (@HMul.hMul.{0, 0, 0} Nat Nat Nat (@instHMul.{0} Nat instMulNat)
      (@OfNat.ofNat.{0} Nat (nat_lit 2) (instOfNatNat (nat_lit 2))) n) := @double_is_mul2
#print axioms double_is_mul2
end

-- double_le
section
set_option autoImplicit true in
example : ∀ (a b : Nat), @LE.le.{0} Nat instLENat a b → @LE.le.{0} Nat instLENat (double a) (double b) := @double_le
#print axioms double_le
end
