-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: 5cfdeb1c35b89bcb00d6a51f4eb8f40134455e448804cccb292e5be7d7f3da3a
-- Preserve these theorem statements when completing the exercise.

-- double_add
section
set_option autoImplicit true in
example : ∀ (a b : Nat),
  @Eq.{1} Nat (double (@HAdd.hAdd.{0, 0, 0} Nat Nat Nat (@instHAdd.{0} Nat instAddNat) a b))
    (@HAdd.hAdd.{0, 0, 0} Nat Nat Nat (@instHAdd.{0} Nat instAddNat) (double a) (double b)) := @double_add
#print axioms double_add
end

-- triple_0
section
set_option autoImplicit true in
example : @Eq.{1} Nat (triple (@OfNat.ofNat.{0} Nat (nat_lit 0) (instOfNatNat (nat_lit 0))))
  (@OfNat.ofNat.{0} Nat (nat_lit 0) (instOfNatNat (nat_lit 0))) := @triple_0
#print axioms triple_0
end

-- triple_def
section
set_option autoImplicit true in
example : ∀ (n : Nat),
  @Eq.{1} Nat (triple n)
    (@HMul.hMul.{0, 0, 0} Nat Nat Nat (@instHMul.{0} Nat instMulNat)
      (@OfNat.ofNat.{0} Nat (nat_lit 3) (instOfNatNat (nat_lit 3))) n) := @triple_def
#print axioms triple_def
end

-- zero_add
section
set_option autoImplicit true in
example : ∀ (n : Nat),
  @Eq.{1} Nat
    (@HAdd.hAdd.{0, 0, 0} Nat Nat Nat (@instHAdd.{0} Nat instAddNat)
      (@OfNat.ofNat.{0} Nat (nat_lit 0) (instOfNatNat (nat_lit 0))) n)
    n := @zero_add
#print axioms zero_add
end
