-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: eee6ef7726fa88a93a0d25f305c3aee93ab20aca5d3199ff5d639611f2ce7b6d
-- Preserve these theorem statements when completing the exercise.

-- MyNat.exercise_tutorial_add_zero2
section
set_option autoImplicit true in
example : ∀ (a b c : MyNat),
  @Eq.{1} MyNat
    (@HAdd.hAdd.{0, 0, 0} MyNat MyNat MyNat (@instHAdd.{0} MyNat MyNat.instAdd)
      (@HAdd.hAdd.{0, 0, 0} MyNat MyNat MyNat (@instHAdd.{0} MyNat MyNat.instAdd) a
        (@HAdd.hAdd.{0, 0, 0} MyNat MyNat MyNat (@instHAdd.{0} MyNat MyNat.instAdd) b
          (@OfNat.ofNat.{0} MyNat (nat_lit 0) (@MyNat.instOfNat (nat_lit 0)))))
      (@HAdd.hAdd.{0, 0, 0} MyNat MyNat MyNat (@instHAdd.{0} MyNat MyNat.instAdd) c
        (@OfNat.ofNat.{0} MyNat (nat_lit 0) (@MyNat.instOfNat (nat_lit 0)))))
    (@HAdd.hAdd.{0, 0, 0} MyNat MyNat MyNat (@instHAdd.{0} MyNat MyNat.instAdd)
      (@HAdd.hAdd.{0, 0, 0} MyNat MyNat MyNat (@instHAdd.{0} MyNat MyNat.instAdd) a b) c) := @MyNat.exercise_tutorial_add_zero2
#print axioms MyNat.exercise_tutorial_add_zero2
end
