-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: fd1fdc6be04f9adbe3afbb52bd6ff5a65b9909aa4799dcdad71130838eaa7028
-- Preserve these theorem statements when completing the exercise.

-- MyNat.exercise_tutorial_rfl
section
set_option autoImplicit true in
example : ∀ (x q : MyNat),
  @Eq.{1} MyNat
    (@HAdd.hAdd.{0, 0, 0} MyNat MyNat MyNat (@instHAdd.{0} MyNat MyNat.instAdd)
      (@HMul.hMul.{0, 0, 0} MyNat MyNat MyNat (@instHMul.{0} MyNat MyNat.instMul)
        (@OfNat.ofNat.{0} MyNat (nat_lit 37) (@MyNat.instOfNat (nat_lit 37))) x)
      q)
    (@HAdd.hAdd.{0, 0, 0} MyNat MyNat MyNat (@instHAdd.{0} MyNat MyNat.instAdd)
      (@HMul.hMul.{0, 0, 0} MyNat MyNat MyNat (@instHMul.{0} MyNat MyNat.instMul)
        (@OfNat.ofNat.{0} MyNat (nat_lit 37) (@MyNat.instOfNat (nat_lit 37))) x)
      q) := @MyNat.exercise_tutorial_rfl
#print axioms MyNat.exercise_tutorial_rfl
end
