-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: 1f13c0122fbc149f748262429d9833cb6179feab901809cae5919f1ff95a9d38
-- Preserve these theorem statements when completing the exercise.

-- MyNat.exercise_tutorial_rw
section
set_option autoImplicit true in
example : ∀ (x y : MyNat),
  @Eq.{1} MyNat y
      (@HAdd.hAdd.{0, 0, 0} MyNat MyNat MyNat (@instHAdd.{0} MyNat MyNat.instAdd) x
        (@OfNat.ofNat.{0} MyNat (nat_lit 7) (@MyNat.instOfNat (nat_lit 7)))) →
    @Eq.{1} MyNat
      (@HMul.hMul.{0, 0, 0} MyNat MyNat MyNat (@instHMul.{0} MyNat MyNat.instMul)
        (@OfNat.ofNat.{0} MyNat (nat_lit 2) (@MyNat.instOfNat (nat_lit 2))) y)
      (@HMul.hMul.{0, 0, 0} MyNat MyNat MyNat (@instHMul.{0} MyNat MyNat.instMul)
        (@OfNat.ofNat.{0} MyNat (nat_lit 2) (@MyNat.instOfNat (nat_lit 2)))
        (@HAdd.hAdd.{0, 0, 0} MyNat MyNat MyNat (@instHAdd.{0} MyNat MyNat.instAdd) x
          (@OfNat.ofNat.{0} MyNat (nat_lit 7) (@MyNat.instOfNat (nat_lit 7))))) := @MyNat.exercise_tutorial_rw
#print axioms MyNat.exercise_tutorial_rw
end
