-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: 2e4508b4947f5f8a2227dc12cced0e821df1540322ad7d1feddd08c9db16c3b4
-- Preserve these theorem statements when completing the exercise.

-- MyNat.exercise_tutorial_rw_backwards
section
set_option autoImplicit true in
example : @Eq.{1} MyNat (@OfNat.ofNat.{0} MyNat (nat_lit 2) (@MyNat.instOfNat (nat_lit 2)))
  (MyNat.succ (MyNat.succ (@OfNat.ofNat.{0} MyNat (nat_lit 0) (@MyNat.instOfNat (nat_lit 0))))) := @MyNat.exercise_tutorial_rw_backwards
#print axioms MyNat.exercise_tutorial_rw_backwards
end
