-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: d75de77643658f3ca52ea4eb390d45d1338f4c9e8f98bec8e3b6ab2b21f6533d
-- Preserve these theorem statements when completing the exercise.

-- MyNat.succ_eq_add_one
section
set_option autoImplicit true in
example : ∀ (n : MyNat),
  @Eq.{1} MyNat (MyNat.succ n)
    (@HAdd.hAdd.{0, 0, 0} MyNat MyNat MyNat (@instHAdd.{0} MyNat MyNat.instAdd) n
      (@OfNat.ofNat.{0} MyNat (nat_lit 1) (@MyNat.instOfNat (nat_lit 1)))) := @MyNat.succ_eq_add_one
#print axioms MyNat.succ_eq_add_one
end
