-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: b5884547e0833afdc011619282b7e8ff1761ddb4c11793a4cb9906e6bcbe9192
-- Preserve these theorem statements when completing the exercise.

-- MyNat.exercise_tutorial_two_eq_ss0
section
set_option autoImplicit true in
example : @Eq.{1} MyNat (@OfNat.ofNat.{0} MyNat (nat_lit 2) (@MyNat.instOfNat (nat_lit 2)))
  (MyNat.succ (MyNat.succ (@OfNat.ofNat.{0} MyNat (nat_lit 0) (@MyNat.instOfNat (nat_lit 0))))) := @MyNat.exercise_tutorial_two_eq_ss0
#print axioms MyNat.exercise_tutorial_two_eq_ss0
end
