-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: 7e08c3dc03593233433b9ad4acdb34de7dd7bcadf7120e2bd71869a7bc9647df
-- Preserve these theorem statements when completing the exercise.

-- MyNat.exercise_tutorial_twoaddtwo
section
set_option autoImplicit true in
example : @Eq.{1} MyNat
  (@HAdd.hAdd.{0, 0, 0} MyNat MyNat MyNat (@instHAdd.{0} MyNat MyNat.instAdd)
    (@OfNat.ofNat.{0} MyNat (nat_lit 2) (@MyNat.instOfNat (nat_lit 2)))
    (@OfNat.ofNat.{0} MyNat (nat_lit 2) (@MyNat.instOfNat (nat_lit 2))))
  (@OfNat.ofNat.{0} MyNat (nat_lit 4) (@MyNat.instOfNat (nat_lit 4))) := @MyNat.exercise_tutorial_twoaddtwo
#print axioms MyNat.exercise_tutorial_twoaddtwo
end
