-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: f1c7797280a321946b2d55164e79253f6b3404956076208ccf777673eb4a16bf
-- Preserve these theorem statements when completing the exercise.

-- Algebra.bool_assoc
section
set_option autoImplicit true in
example : ∀ (a b c : Bool),
  @Eq.{1} Bool
    (@HMul.hMul.{0, 0, 0} Bool Bool Bool
      (@instHMul.{0} Bool
        (@Algebra.Magma.toMul.{0} Bool
          (@Algebra.Semigroup.toMagma.{0} Bool
            (@Algebra.Monoid.toSemigroup.{0} Bool (@Algebra.CommMonoid.toMonoid.{0} Bool Algebra.instCommMonoidBool)))))
      (@HMul.hMul.{0, 0, 0} Bool Bool Bool
        (@instHMul.{0} Bool
          (@Algebra.Magma.toMul.{0} Bool
            (@Algebra.Semigroup.toMagma.{0} Bool
              (@Algebra.Monoid.toSemigroup.{0} Bool
                (@Algebra.CommMonoid.toMonoid.{0} Bool Algebra.instCommMonoidBool)))))
        a b)
      c)
    (@HMul.hMul.{0, 0, 0} Bool Bool Bool
      (@instHMul.{0} Bool
        (@Algebra.Magma.toMul.{0} Bool
          (@Algebra.Semigroup.toMagma.{0} Bool
            (@Algebra.Monoid.toSemigroup.{0} Bool (@Algebra.CommMonoid.toMonoid.{0} Bool Algebra.instCommMonoidBool)))))
      a
      (@HMul.hMul.{0, 0, 0} Bool Bool Bool
        (@instHMul.{0} Bool
          (@Algebra.Magma.toMul.{0} Bool
            (@Algebra.Semigroup.toMagma.{0} Bool
              (@Algebra.Monoid.toSemigroup.{0} Bool
                (@Algebra.CommMonoid.toMonoid.{0} Bool Algebra.instCommMonoidBool)))))
        b c)) := @Algebra.bool_assoc
#print axioms Algebra.bool_assoc
end
