-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: 48db07bd3a7fa99aa6c47f65feede71433427e4752085ea847d6ddfdb27257a8
-- Preserve these theorem statements when completing the exercise.

-- Algebra.bool_and
section
set_option autoImplicit true in
example : @Eq.{1} Bool
  (@HMul.hMul.{0, 0, 0} Bool Bool Bool
    (@instHMul.{0} Bool
      (@Algebra.Magma.toMul.{0} Bool
        (@Algebra.Semigroup.toMagma.{0} Bool
          (@Algebra.Monoid.toSemigroup.{0} Bool (@Algebra.CommMonoid.toMonoid.{0} Bool Algebra.instCommMonoidBool)))))
    Bool.true Bool.false)
  Bool.false := @Algebra.bool_and
#print axioms Algebra.bool_and
end
