-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: 783e9be465fc765bfcce417f49a7aa2a48af1543d0451377edec1f6ceaae105f
-- Preserve these theorem statements when completing the exercise.

-- Algebra.bool_comm
section
set_option autoImplicit true in
example : ∀ (a b : Bool),
  @Eq.{1} Bool
    (@HMul.hMul.{0, 0, 0} Bool Bool Bool
      (@instHMul.{0} Bool
        (@Algebra.Magma.toMul.{0} Bool
          (@Algebra.Semigroup.toMagma.{0} Bool
            (@Algebra.Monoid.toSemigroup.{0} Bool (@Algebra.CommMonoid.toMonoid.{0} Bool Algebra.instCommMonoidBool)))))
      a b)
    (@HMul.hMul.{0, 0, 0} Bool Bool Bool
      (@instHMul.{0} Bool
        (@Algebra.Magma.toMul.{0} Bool
          (@Algebra.Semigroup.toMagma.{0} Bool
            (@Algebra.Monoid.toSemigroup.{0} Bool (@Algebra.CommMonoid.toMonoid.{0} Bool Algebra.instCommMonoidBool)))))
      b a) := @Algebra.bool_comm
#print axioms Algebra.bool_comm
end
