-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: 51531689be75a8eeb5512897541709fcf8a3bf090532db814d12dc9554c15f84
-- Preserve these theorem statements when completing the exercise.

-- Algebra.inv_comm
section
set_option autoImplicit true in
example : ∀ {G : Type u_1} [inst : Algebra.CommGroup.{u_1} G] (a b : G),
  @Eq.{u_1 + 1} G
    (@HMul.hMul.{u_1, u_1, u_1} G G G
      (@instHMul.{u_1} G
        (@Algebra.Magma.toMul.{u_1} G
          (@Algebra.Semigroup.toMagma.{u_1} G
            (@Algebra.Monoid.toSemigroup.{u_1} G
              (@Algebra.Group.toMonoid.{u_1} G (@Algebra.CommGroup.toGroup.{u_1} G inst))))))
      (@Inv.inv.{u_1} G (@Algebra.Group.toInv.{u_1} G (@Algebra.CommGroup.toGroup.{u_1} G inst)) a)
      (@Inv.inv.{u_1} G (@Algebra.Group.toInv.{u_1} G (@Algebra.CommGroup.toGroup.{u_1} G inst)) b))
    (@HMul.hMul.{u_1, u_1, u_1} G G G
      (@instHMul.{u_1} G
        (@Algebra.Magma.toMul.{u_1} G
          (@Algebra.Semigroup.toMagma.{u_1} G
            (@Algebra.Monoid.toSemigroup.{u_1} G
              (@Algebra.Group.toMonoid.{u_1} G (@Algebra.CommGroup.toGroup.{u_1} G inst))))))
      (@Inv.inv.{u_1} G (@Algebra.Group.toInv.{u_1} G (@Algebra.CommGroup.toGroup.{u_1} G inst)) b)
      (@Inv.inv.{u_1} G (@Algebra.Group.toInv.{u_1} G (@Algebra.CommGroup.toGroup.{u_1} G inst)) a)) := @Algebra.inv_comm
#print axioms Algebra.inv_comm
end
