-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: 5a9be3bec6af4125ba2372c22c1b697e1cd36c4976c3a9c3dbdc274a3b4462ad
-- Preserve these theorem statements when completing the exercise.

-- Algebra.mul_inv
section
set_option autoImplicit true in
example : ∀ {G : Type u_1} [inst : Algebra.CommGroup.{u_1} G] (a b : G),
  @Eq.{u_1 + 1} G
    (@Inv.inv.{u_1} G (@Algebra.Group.toInv.{u_1} G (@Algebra.CommGroup.toGroup.{u_1} G inst))
      (@HMul.hMul.{u_1, u_1, u_1} G G G
        (@instHMul.{u_1} G
          (@Algebra.Magma.toMul.{u_1} G
            (@Algebra.Semigroup.toMagma.{u_1} G
              (@Algebra.Monoid.toSemigroup.{u_1} G
                (@Algebra.Group.toMonoid.{u_1} G (@Algebra.CommGroup.toGroup.{u_1} G inst))))))
        a b))
    (@HMul.hMul.{u_1, u_1, u_1} G G G
      (@instHMul.{u_1} G
        (@Algebra.Magma.toMul.{u_1} G
          (@Algebra.Semigroup.toMagma.{u_1} G
            (@Algebra.Monoid.toSemigroup.{u_1} G
              (@Algebra.Group.toMonoid.{u_1} G (@Algebra.CommGroup.toGroup.{u_1} G inst))))))
      (@Inv.inv.{u_1} G (@Algebra.Group.toInv.{u_1} G (@Algebra.CommGroup.toGroup.{u_1} G inst)) a)
      (@Inv.inv.{u_1} G (@Algebra.Group.toInv.{u_1} G (@Algebra.CommGroup.toGroup.{u_1} G inst)) b)) := @Algebra.mul_inv
#print axioms Algebra.mul_inv
end
