-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: 4854f935e689328f60c372740c0707ee278bda3aa528cc13adf9dff2d5e19068
-- Preserve these theorem statements when completing the exercise.

-- Algebra.mul_mul_mul_comm
section
set_option autoImplicit true in
example : ∀ {G : Type u_1} [inst : Algebra.CommGroup.{u_1} G] (a b c d : G),
  @Eq.{u_1 + 1} G
    (@HMul.hMul.{u_1, u_1, u_1} G G G
      (@instHMul.{u_1} G
        (@Algebra.Magma.toMul.{u_1} G
          (@Algebra.Semigroup.toMagma.{u_1} G
            (@Algebra.Monoid.toSemigroup.{u_1} G
              (@Algebra.Group.toMonoid.{u_1} G (@Algebra.CommGroup.toGroup.{u_1} G inst))))))
      (@HMul.hMul.{u_1, u_1, u_1} G G G
        (@instHMul.{u_1} G
          (@Algebra.Magma.toMul.{u_1} G
            (@Algebra.Semigroup.toMagma.{u_1} G
              (@Algebra.Monoid.toSemigroup.{u_1} G
                (@Algebra.Group.toMonoid.{u_1} G (@Algebra.CommGroup.toGroup.{u_1} G inst))))))
        a b)
      (@HMul.hMul.{u_1, u_1, u_1} G G G
        (@instHMul.{u_1} G
          (@Algebra.Magma.toMul.{u_1} G
            (@Algebra.Semigroup.toMagma.{u_1} G
              (@Algebra.Monoid.toSemigroup.{u_1} G
                (@Algebra.Group.toMonoid.{u_1} G (@Algebra.CommGroup.toGroup.{u_1} G inst))))))
        c d))
    (@HMul.hMul.{u_1, u_1, u_1} G G G
      (@instHMul.{u_1} G
        (@Algebra.Magma.toMul.{u_1} G
          (@Algebra.Semigroup.toMagma.{u_1} G
            (@Algebra.Monoid.toSemigroup.{u_1} G
              (@Algebra.Group.toMonoid.{u_1} G (@Algebra.CommGroup.toGroup.{u_1} G inst))))))
      (@HMul.hMul.{u_1, u_1, u_1} G G G
        (@instHMul.{u_1} G
          (@Algebra.Magma.toMul.{u_1} G
            (@Algebra.Semigroup.toMagma.{u_1} G
              (@Algebra.Monoid.toSemigroup.{u_1} G
                (@Algebra.Group.toMonoid.{u_1} G (@Algebra.CommGroup.toGroup.{u_1} G inst))))))
        a c)
      (@HMul.hMul.{u_1, u_1, u_1} G G G
        (@instHMul.{u_1} G
          (@Algebra.Magma.toMul.{u_1} G
            (@Algebra.Semigroup.toMagma.{u_1} G
              (@Algebra.Monoid.toSemigroup.{u_1} G
                (@Algebra.Group.toMonoid.{u_1} G (@Algebra.CommGroup.toGroup.{u_1} G inst))))))
        b d)) := @Algebra.mul_mul_mul_comm
#print axioms Algebra.mul_mul_mul_comm
end
