-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: 801b166731cc89feae437a0a37f1df60478aba5836734f4be4c101207e0da3e9
-- Preserve these theorem statements when completing the exercise.

-- Algebra.mul_right_comm
section
set_option autoImplicit true in
example : ∀ {G : Type u_1} [inst : Algebra.CommGroup.{u_1} G] (a b c : G),
  @Eq.{u_1 + 1} G
    (@HMul.hMul.{u_1, u_1, u_1} G G G
      (@instHMul.{u_1} G
        (@Algebra.Magma.toMul.{u_1} G
          (@Algebra.Semigroup.toMagma.{u_1} G
            (@Algebra.Monoid.toSemigroup.{u_1} G
              (@Algebra.Group.toMonoid.{u_1} G (@Algebra.CommGroup.toGroup.{u_1} G inst))))))
      (@HMul.hMul.{u_1, u_1, u_1} G G G
        (@instHMul.{u_1} G
          (@Algebra.Magma.toMul.{u_1} G
            (@Algebra.Semigroup.toMagma.{u_1} G
              (@Algebra.Monoid.toSemigroup.{u_1} G
                (@Algebra.Group.toMonoid.{u_1} G (@Algebra.CommGroup.toGroup.{u_1} G inst))))))
        a b)
      c)
    (@HMul.hMul.{u_1, u_1, u_1} G G G
      (@instHMul.{u_1} G
        (@Algebra.Magma.toMul.{u_1} G
          (@Algebra.Semigroup.toMagma.{u_1} G
            (@Algebra.Monoid.toSemigroup.{u_1} G
              (@Algebra.Group.toMonoid.{u_1} G (@Algebra.CommGroup.toGroup.{u_1} G inst))))))
      (@HMul.hMul.{u_1, u_1, u_1} G G G
        (@instHMul.{u_1} G
          (@Algebra.Magma.toMul.{u_1} G
            (@Algebra.Semigroup.toMagma.{u_1} G
              (@Algebra.Monoid.toSemigroup.{u_1} G
                (@Algebra.Group.toMonoid.{u_1} G (@Algebra.CommGroup.toGroup.{u_1} G inst))))))
        a c)
      b) := @Algebra.mul_right_comm
#print axioms Algebra.mul_right_comm
end
