-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: e7f697b567e26345ad822f4ed4b23b070e9e2e7ada43a586f65e22dd0ebfdfa3
-- Preserve these theorem statements when completing the exercise.

-- Algebra.mul_left_comm
section
set_option autoImplicit true in
example : ∀ {G : Type u_1} [inst : Algebra.CommGroup.{u_1} G] (a b c : G),
  @Eq.{u_1 + 1} G
    (@HMul.hMul.{u_1, u_1, u_1} G G G
      (@instHMul.{u_1} G
        (@Algebra.Magma.toMul.{u_1} G
          (@Algebra.Semigroup.toMagma.{u_1} G
            (@Algebra.Monoid.toSemigroup.{u_1} G
              (@Algebra.Group.toMonoid.{u_1} G (@Algebra.CommGroup.toGroup.{u_1} G inst))))))
      a
      (@HMul.hMul.{u_1, u_1, u_1} G G G
        (@instHMul.{u_1} G
          (@Algebra.Magma.toMul.{u_1} G
            (@Algebra.Semigroup.toMagma.{u_1} G
              (@Algebra.Monoid.toSemigroup.{u_1} G
                (@Algebra.Group.toMonoid.{u_1} G (@Algebra.CommGroup.toGroup.{u_1} G inst))))))
        b c))
    (@HMul.hMul.{u_1, u_1, u_1} G G G
      (@instHMul.{u_1} G
        (@Algebra.Magma.toMul.{u_1} G
          (@Algebra.Semigroup.toMagma.{u_1} G
            (@Algebra.Monoid.toSemigroup.{u_1} G
              (@Algebra.Group.toMonoid.{u_1} G (@Algebra.CommGroup.toGroup.{u_1} G inst))))))
      b
      (@HMul.hMul.{u_1, u_1, u_1} G G G
        (@instHMul.{u_1} G
          (@Algebra.Magma.toMul.{u_1} G
            (@Algebra.Semigroup.toMagma.{u_1} G
              (@Algebra.Monoid.toSemigroup.{u_1} G
                (@Algebra.Group.toMonoid.{u_1} G (@Algebra.CommGroup.toGroup.{u_1} G inst))))))
        a c)) := @Algebra.mul_left_comm
#print axioms Algebra.mul_left_comm
end
