-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: 261a7df71fc4cf3bdf03af7cb7fc150399120eb910cee092c7f12bb7baa56952
-- Preserve these theorem statements when completing the exercise.

-- Algebra.conj_cancel
section
set_option autoImplicit true in
example : ∀ {G : Type u_1} [inst : Algebra.Group.{u_1} G] (g a : G),
  @Eq.{u_1 + 1} G
    (@HMul.hMul.{u_1, u_1, u_1} G G G
      (@instHMul.{u_1} G
        (@Algebra.Magma.toMul.{u_1} G
          (@Algebra.Semigroup.toMagma.{u_1} G
            (@Algebra.Monoid.toSemigroup.{u_1} G (@Algebra.Group.toMonoid.{u_1} G inst)))))
      (@HMul.hMul.{u_1, u_1, u_1} G G G
        (@instHMul.{u_1} G
          (@Algebra.Magma.toMul.{u_1} G
            (@Algebra.Semigroup.toMagma.{u_1} G
              (@Algebra.Monoid.toSemigroup.{u_1} G (@Algebra.Group.toMonoid.{u_1} G inst)))))
        (@HMul.hMul.{u_1, u_1, u_1} G G G
          (@instHMul.{u_1} G
            (@Algebra.Magma.toMul.{u_1} G
              (@Algebra.Semigroup.toMagma.{u_1} G
                (@Algebra.Monoid.toSemigroup.{u_1} G (@Algebra.Group.toMonoid.{u_1} G inst)))))
          g a)
        (@Inv.inv.{u_1} G (@Algebra.Group.toInv.{u_1} G inst) g))
      g)
    (@HMul.hMul.{u_1, u_1, u_1} G G G
      (@instHMul.{u_1} G
        (@Algebra.Magma.toMul.{u_1} G
          (@Algebra.Semigroup.toMagma.{u_1} G
            (@Algebra.Monoid.toSemigroup.{u_1} G (@Algebra.Group.toMonoid.{u_1} G inst)))))
      g a) := @Algebra.conj_cancel
#print axioms Algebra.conj_cancel
end
