-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: 79c3ef7c0987e9750236548cd6708ab363fba69e448e3a48b742eb97e89051b6
-- Preserve these theorem statements when completing the exercise.

-- Algebra.eq_inv_of_mul_eq_one
section
set_option autoImplicit true in
example : ∀ {G : Type u_1} [inst : Algebra.Group.{u_1} G] (a b : G),
  @Eq.{u_1 + 1} G
      (@HMul.hMul.{u_1, u_1, u_1} G G G
        (@instHMul.{u_1} G
          (@Algebra.Magma.toMul.{u_1} G
            (@Algebra.Semigroup.toMagma.{u_1} G
              (@Algebra.Monoid.toSemigroup.{u_1} G (@Algebra.Group.toMonoid.{u_1} G inst)))))
        a b)
      (@OfNat.ofNat.{u_1} G (nat_lit 1)
        (@One.toOfNat1.{u_1} G (@Algebra.Monoid.toOne.{u_1} G (@Algebra.Group.toMonoid.{u_1} G inst)))) →
    @Eq.{u_1 + 1} G b (@Inv.inv.{u_1} G (@Algebra.Group.toInv.{u_1} G inst) a) := @Algebra.eq_inv_of_mul_eq_one
#print axioms Algebra.eq_inv_of_mul_eq_one
end
