-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: 6ee9b2d4eed8c3801897cea0beb684faa9b0fba37b73354cc8211960a5ca9ca7
-- Preserve these theorem statements when completing the exercise.

-- Algebra.eq_of_mul_inv_eq_one
section
set_option autoImplicit true in
example : ∀ {G : Type u_1} [inst : Algebra.Group.{u_1} G] (a b : G),
  @Eq.{u_1 + 1} G
      (@HMul.hMul.{u_1, u_1, u_1} G G G
        (@instHMul.{u_1} G
          (@Algebra.Magma.toMul.{u_1} G
            (@Algebra.Semigroup.toMagma.{u_1} G
              (@Algebra.Monoid.toSemigroup.{u_1} G (@Algebra.Group.toMonoid.{u_1} G inst)))))
        a (@Inv.inv.{u_1} G (@Algebra.Group.toInv.{u_1} G inst) b))
      (@OfNat.ofNat.{u_1} G (nat_lit 1)
        (@One.toOfNat1.{u_1} G (@Algebra.Monoid.toOne.{u_1} G (@Algebra.Group.toMonoid.{u_1} G inst)))) →
    @Eq.{u_1 + 1} G a b := @Algebra.eq_of_mul_inv_eq_one
#print axioms Algebra.eq_of_mul_inv_eq_one
end
