-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: 7a10ea6fa9b0211934cb8ad0b2cf7367563b544562efbc45f6a2a356bf4e4e10
-- Preserve these theorem statements when completing the exercise.

-- Algebra.inv_inv
section
set_option autoImplicit true in
example : ∀ {G : Type u_1} [inst : Algebra.Group.{u_1} G] (a : G),
  @Eq.{u_1 + 1} G
    (@Inv.inv.{u_1} G (@Algebra.Group.toInv.{u_1} G inst) (@Inv.inv.{u_1} G (@Algebra.Group.toInv.{u_1} G inst) a)) a := @Algebra.inv_inv
#print axioms Algebra.inv_inv
end
