-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: 07ff10c41d28243dde36cd6900be89bed98c06b2015af75ccf4cf05b544698cf
-- Preserve these theorem statements when completing the exercise.

-- Algebra.inv_one
section
set_option autoImplicit true in
example : ∀ {G : Type u_1} [inst : Algebra.Group.{u_1} G],
  @Eq.{u_1 + 1} G
    (@Inv.inv.{u_1} G (@Algebra.Group.toInv.{u_1} G inst)
      (@OfNat.ofNat.{u_1} G (nat_lit 1)
        (@One.toOfNat1.{u_1} G (@Algebra.Monoid.toOne.{u_1} G (@Algebra.Group.toMonoid.{u_1} G inst)))))
    (@OfNat.ofNat.{u_1} G (nat_lit 1)
      (@One.toOfNat1.{u_1} G (@Algebra.Monoid.toOne.{u_1} G (@Algebra.Group.toMonoid.{u_1} G inst)))) := @Algebra.inv_one
#print axioms Algebra.inv_one
end
