-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: 183e5c9161e208f12610f420b520e8969cafbdc97bc3971f1080dd36706f1e8d
-- Preserve these theorem statements when completing the exercise.

-- Algebra.inv_inj
section
set_option autoImplicit true in
example : ∀ {G : Type u_1} [inst : Algebra.Group.{u_1} G] (a b : G),
  @Eq.{u_1 + 1} G (@Inv.inv.{u_1} G (@Algebra.Group.toInv.{u_1} G inst) a)
      (@Inv.inv.{u_1} G (@Algebra.Group.toInv.{u_1} G inst) b) →
    @Eq.{u_1 + 1} G a b := @Algebra.inv_inj
#print axioms Algebra.inv_inj
end
