-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: 0c635e142f3ec69f638305334bd481c35e42122b610350387d86bf3e851add8f
-- Preserve these theorem statements when completing the exercise.

-- Algebra.inv_mul_cancel_right
section
set_option autoImplicit true in
example : ∀ {G : Type u_1} [inst : Algebra.Group.{u_1} G] (a b : G),
  @Eq.{u_1 + 1} G
    (@HMul.hMul.{u_1, u_1, u_1} G G G
      (@instHMul.{u_1} G
        (@Algebra.Magma.toMul.{u_1} G
          (@Algebra.Semigroup.toMagma.{u_1} G
            (@Algebra.Monoid.toSemigroup.{u_1} G (@Algebra.Group.toMonoid.{u_1} G inst)))))
      (@HMul.hMul.{u_1, u_1, u_1} G G G
        (@instHMul.{u_1} G
          (@Algebra.Magma.toMul.{u_1} G
            (@Algebra.Semigroup.toMagma.{u_1} G
              (@Algebra.Monoid.toSemigroup.{u_1} G (@Algebra.Group.toMonoid.{u_1} G inst)))))
        a (@Inv.inv.{u_1} G (@Algebra.Group.toInv.{u_1} G inst) b))
      b)
    a := @Algebra.inv_mul_cancel_right
#print axioms Algebra.inv_mul_cancel_right
end
