-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: 3145a78dbf32c609bfe88e5eb9224f659c18a567d907ceeac31768ff00579e7e
-- Preserve these theorem statements when completing the exercise.

-- Algebra.inv_eq_of_mul_eq_one
section
set_option autoImplicit true in
example : ∀ {G : Type u_1} [inst : Algebra.Group.{u_1} G] (a b : G),
  @Eq.{u_1 + 1} G
      (@HMul.hMul.{u_1, u_1, u_1} G G G
        (@instHMul.{u_1} G
          (@Algebra.Magma.toMul.{u_1} G
            (@Algebra.Semigroup.toMagma.{u_1} G
              (@Algebra.Monoid.toSemigroup.{u_1} G (@Algebra.Group.toMonoid.{u_1} G inst)))))
        a b)
      (@OfNat.ofNat.{u_1} G (nat_lit 1)
        (@One.toOfNat1.{u_1} G (@Algebra.Monoid.toOne.{u_1} G (@Algebra.Group.toMonoid.{u_1} G inst)))) →
    @Eq.{u_1 + 1} G (@Inv.inv.{u_1} G (@Algebra.Group.toInv.{u_1} G inst) a) b := @Algebra.inv_eq_of_mul_eq_one
#print axioms Algebra.inv_eq_of_mul_eq_one
end
