-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: fb894c4b4c658f98fee91cf82a8f86f6e74a6565fa1ca877631436149a02e29a
-- Preserve these theorem statements when completing the exercise.

-- Algebra.mul_inv_cancel_left
section
set_option autoImplicit true in
example : ∀ {G : Type u_1} [inst : Algebra.Group.{u_1} G] (a b : G),
  @Eq.{u_1 + 1} G
    (@HMul.hMul.{u_1, u_1, u_1} G G G
      (@instHMul.{u_1} G
        (@Algebra.Magma.toMul.{u_1} G
          (@Algebra.Semigroup.toMagma.{u_1} G
            (@Algebra.Monoid.toSemigroup.{u_1} G (@Algebra.Group.toMonoid.{u_1} G inst)))))
      a
      (@HMul.hMul.{u_1, u_1, u_1} G G G
        (@instHMul.{u_1} G
          (@Algebra.Magma.toMul.{u_1} G
            (@Algebra.Semigroup.toMagma.{u_1} G
              (@Algebra.Monoid.toSemigroup.{u_1} G (@Algebra.Group.toMonoid.{u_1} G inst)))))
        (@Inv.inv.{u_1} G (@Algebra.Group.toInv.{u_1} G inst) a) b))
    b := @Algebra.mul_inv_cancel_left
#print axioms Algebra.mul_inv_cancel_left
end
