-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: 7471fa789bfb1dc3d18d0db77e9a3624b98506039ba2da2eff617e791e308cff
-- Preserve these theorem statements when completing the exercise.

-- Algebra.mul_inv_rev
section
set_option autoImplicit true in
example : ∀ {G : Type u_1} [inst : Algebra.Group.{u_1} G] (a b : G),
  @Eq.{u_1 + 1} G
    (@Inv.inv.{u_1} G (@Algebra.Group.toInv.{u_1} G inst)
      (@HMul.hMul.{u_1, u_1, u_1} G G G
        (@instHMul.{u_1} G
          (@Algebra.Magma.toMul.{u_1} G
            (@Algebra.Semigroup.toMagma.{u_1} G
              (@Algebra.Monoid.toSemigroup.{u_1} G (@Algebra.Group.toMonoid.{u_1} G inst)))))
        a b))
    (@HMul.hMul.{u_1, u_1, u_1} G G G
      (@instHMul.{u_1} G
        (@Algebra.Magma.toMul.{u_1} G
          (@Algebra.Semigroup.toMagma.{u_1} G
            (@Algebra.Monoid.toSemigroup.{u_1} G (@Algebra.Group.toMonoid.{u_1} G inst)))))
      (@Inv.inv.{u_1} G (@Algebra.Group.toInv.{u_1} G inst) b) (@Inv.inv.{u_1} G (@Algebra.Group.toInv.{u_1} G inst) a)) := @Algebra.mul_inv_rev
#print axioms Algebra.mul_inv_rev
end
