-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: 23bf010a40ee140d141ec6dc269bfdc83bef5464f12ec4bf777291b4734811c0
-- Preserve these theorem statements when completing the exercise.

-- Algebra.mul_left_cancel
section
set_option autoImplicit true in
example : ∀ {G : Type u_1} [inst : Algebra.Group.{u_1} G] (a b c : G),
  @Eq.{u_1 + 1} G
      (@HMul.hMul.{u_1, u_1, u_1} G G G
        (@instHMul.{u_1} G
          (@Algebra.Magma.toMul.{u_1} G
            (@Algebra.Semigroup.toMagma.{u_1} G
              (@Algebra.Monoid.toSemigroup.{u_1} G (@Algebra.Group.toMonoid.{u_1} G inst)))))
        a b)
      (@HMul.hMul.{u_1, u_1, u_1} G G G
        (@instHMul.{u_1} G
          (@Algebra.Magma.toMul.{u_1} G
            (@Algebra.Semigroup.toMagma.{u_1} G
              (@Algebra.Monoid.toSemigroup.{u_1} G (@Algebra.Group.toMonoid.{u_1} G inst)))))
        a c) →
    @Eq.{u_1 + 1} G b c := @Algebra.mul_left_cancel
#print axioms Algebra.mul_left_cancel
end
