-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: b06fbdf874d54c68a53e3f284ca0ccbdbcfbdc9980d78fabf593192e0a94eeea
-- Preserve these theorem statements when completing the exercise.

-- Algebra.mul_eq_one_of_eq_inv
section
set_option autoImplicit true in
example : ∀ {G : Type u_1} [inst : Algebra.Group.{u_1} G] (a b : G),
  @Eq.{u_1 + 1} G a (@Inv.inv.{u_1} G (@Algebra.Group.toInv.{u_1} G inst) b) →
    @Eq.{u_1 + 1} G
      (@HMul.hMul.{u_1, u_1, u_1} G G G
        (@instHMul.{u_1} G
          (@Algebra.Magma.toMul.{u_1} G
            (@Algebra.Semigroup.toMagma.{u_1} G
              (@Algebra.Monoid.toSemigroup.{u_1} G (@Algebra.Group.toMonoid.{u_1} G inst)))))
        a b)
      (@OfNat.ofNat.{u_1} G (nat_lit 1)
        (@One.toOfNat1.{u_1} G (@Algebra.Monoid.toOne.{u_1} G (@Algebra.Group.toMonoid.{u_1} G inst)))) := @Algebra.mul_eq_one_of_eq_inv
#print axioms Algebra.mul_eq_one_of_eq_inv
end
