-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: fe561be2c2de5161d2e39002bba0718e5fdd31b66413b53925a47614a33eb7d9
-- Preserve these theorem statements when completing the exercise.

-- Algebra.mul_left_eq_self
section
set_option autoImplicit true in
example : ∀ {G : Type u_1} [inst : Algebra.Group.{u_1} G] (a b : G),
  @Eq.{u_1 + 1} G
      (@HMul.hMul.{u_1, u_1, u_1} G G G
        (@instHMul.{u_1} G
          (@Algebra.Magma.toMul.{u_1} G
            (@Algebra.Semigroup.toMagma.{u_1} G
              (@Algebra.Monoid.toSemigroup.{u_1} G (@Algebra.Group.toMonoid.{u_1} G inst)))))
        a b)
      b →
    @Eq.{u_1 + 1} G a
      (@OfNat.ofNat.{u_1} G (nat_lit 1)
        (@One.toOfNat1.{u_1} G (@Algebra.Monoid.toOne.{u_1} G (@Algebra.Group.toMonoid.{u_1} G inst)))) := @Algebra.mul_left_eq_self
#print axioms Algebra.mul_left_eq_self
end
