-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: 0deb9eda88e67b02fd16e9c4988dac05fd8c8eca4d31ec91c654963b1b1176ba
-- Preserve these theorem statements when completing the exercise.

-- Algebra.mul_right_eq_self
section
set_option autoImplicit true in
example : ∀ {G : Type u_1} [inst : Algebra.Group.{u_1} G] (a b : G),
  @Eq.{u_1 + 1} G
      (@HMul.hMul.{u_1, u_1, u_1} G G G
        (@instHMul.{u_1} G
          (@Algebra.Magma.toMul.{u_1} G
            (@Algebra.Semigroup.toMagma.{u_1} G
              (@Algebra.Monoid.toSemigroup.{u_1} G (@Algebra.Group.toMonoid.{u_1} G inst)))))
        a b)
      a →
    @Eq.{u_1 + 1} G b
      (@OfNat.ofNat.{u_1} G (nat_lit 1)
        (@One.toOfNat1.{u_1} G (@Algebra.Monoid.toOne.{u_1} G (@Algebra.Group.toMonoid.{u_1} G inst)))) := @Algebra.mul_right_eq_self
#print axioms Algebra.mul_right_eq_self
end
