-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: 51c0f108beecba335d0907082ed4a617efe01c545f140626aa3532d3f7c5ec75
-- Preserve these theorem statements when completing the exercise.

-- Algebra.mul_inv_cancel_right
section
set_option autoImplicit true in
example : ∀ {G : Type u_1} [inst : Algebra.Group.{u_1} G] (a b : G),
  @Eq.{u_1 + 1} G
    (@HMul.hMul.{u_1, u_1, u_1} G G G
      (@instHMul.{u_1} G
        (@Algebra.Magma.toMul.{u_1} G
          (@Algebra.Semigroup.toMagma.{u_1} G
            (@Algebra.Monoid.toSemigroup.{u_1} G (@Algebra.Group.toMonoid.{u_1} G inst)))))
      (@HMul.hMul.{u_1, u_1, u_1} G G G
        (@instHMul.{u_1} G
          (@Algebra.Magma.toMul.{u_1} G
            (@Algebra.Semigroup.toMagma.{u_1} G
              (@Algebra.Monoid.toSemigroup.{u_1} G (@Algebra.Group.toMonoid.{u_1} G inst)))))
        a b)
      (@Inv.inv.{u_1} G (@Algebra.Group.toInv.{u_1} G inst) b))
    a := @Algebra.mul_inv_cancel_right
#print axioms Algebra.mul_inv_cancel_right
end
