-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: 35eba7655828469d3b65795401641b56f07f223024ba82618f83cd08e27536c4
-- Preserve these theorem statements when completing the exercise.

-- Algebra.mul_right_cancel
section
set_option autoImplicit true in
example : ∀ {G : Type u_1} [inst : Algebra.Group.{u_1} G] (a b c : G),
  @Eq.{u_1 + 1} G
      (@HMul.hMul.{u_1, u_1, u_1} G G G
        (@instHMul.{u_1} G
          (@Algebra.Magma.toMul.{u_1} G
            (@Algebra.Semigroup.toMagma.{u_1} G
              (@Algebra.Monoid.toSemigroup.{u_1} G (@Algebra.Group.toMonoid.{u_1} G inst)))))
        a c)
      (@HMul.hMul.{u_1, u_1, u_1} G G G
        (@instHMul.{u_1} G
          (@Algebra.Magma.toMul.{u_1} G
            (@Algebra.Semigroup.toMagma.{u_1} G
              (@Algebra.Monoid.toSemigroup.{u_1} G (@Algebra.Group.toMonoid.{u_1} G inst)))))
        b c) →
    @Eq.{u_1 + 1} G a b := @Algebra.mul_right_cancel
#print axioms Algebra.mul_right_cancel
end
