-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: d226b714b209387f2dbf154ea049be716cf04bdec8bb3281087339013821125b
-- Preserve these theorem statements when completing the exercise.

-- false_implies_anything
section
set_option autoImplicit true in
example : False →
  @Eq.{1} Nat
    (@HAdd.hAdd.{0, 0, 0} Nat Nat Nat (@instHAdd.{0} Nat instAddNat)
      (@OfNat.ofNat.{0} Nat (nat_lit 2) (instOfNatNat (nat_lit 2)))
      (@OfNat.ofNat.{0} Nat (nat_lit 2) (instOfNatNat (nat_lit 2))))
    (@OfNat.ofNat.{0} Nat (nat_lit 5) (instOfNatNat (nat_lit 5))) := @false_implies_anything
#print axioms false_implies_anything
end

-- hello_lean
section
set_option autoImplicit true in
example : @Eq.{1} String
  (@HAppend.hAppend.{0, 0, 0} String String String (@instHAppendOfAppend.{0} String instAppendString) "Hello, " "Lean!")
  "Hello, Lean!" := @hello_lean
#print axioms hello_lean
end

-- obvious
section
set_option autoImplicit true in
example : True := @obvious
#print axioms obvious
end

-- one_plus_one
section
set_option autoImplicit true in
example : @Eq.{1} Nat
  (@HAdd.hAdd.{0, 0, 0} Nat Nat Nat (@instHAdd.{0} Nat instAddNat)
    (@OfNat.ofNat.{0} Nat (nat_lit 1) (instOfNatNat (nat_lit 1)))
    (@OfNat.ofNat.{0} Nat (nat_lit 1) (instOfNatNat (nat_lit 1))))
  (@OfNat.ofNat.{0} Nat (nat_lit 2) (instOfNatNat (nat_lit 2))) := @one_plus_one
#print axioms one_plus_one
end
