-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: 0f3120e5d06fd73fa376761f4c5079040e9897009803693561dc3ecef13dd507
-- Preserve these theorem statements when completing the exercise.

-- contradiction
section
set_option autoImplicit true in
example : ∀ (P Q : Prop), P → Not P → Q := @contradiction
#print axioms contradiction
end

-- identity
section
set_option autoImplicit true in
example : ∀ (P : Prop), P → P := @identity
#print axioms identity
end

-- modus_ponens
section
set_option autoImplicit true in
example : ∀ (P Q : Prop), P → (P → Q) → Q := @modus_ponens
#print axioms modus_ponens
end
