-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: 4d330ce19c1db5ce083aab5e56e4bf2f1205ad1384f823f97c69b0ac60cc5cf3
-- Preserve these theorem statements when completing the exercise.

-- MyNat.add_sq
section
set_option autoImplicit true in
example : ∀ (a b : MyNat),
  @Eq.{1} MyNat
    (@HPow.hPow.{0, 0, 0} MyNat MyNat MyNat (@instHPow.{0, 0} MyNat MyNat MyNat.instPow)
      (@HAdd.hAdd.{0, 0, 0} MyNat MyNat MyNat (@instHAdd.{0} MyNat MyNat.instAdd) a b)
      (@OfNat.ofNat.{0} MyNat (nat_lit 2) (@MyNat.instOfNat (nat_lit 2))))
    (@HAdd.hAdd.{0, 0, 0} MyNat MyNat MyNat (@instHAdd.{0} MyNat MyNat.instAdd)
      (@HAdd.hAdd.{0, 0, 0} MyNat MyNat MyNat (@instHAdd.{0} MyNat MyNat.instAdd)
        (@HPow.hPow.{0, 0, 0} MyNat MyNat MyNat (@instHPow.{0, 0} MyNat MyNat MyNat.instPow) a
          (@OfNat.ofNat.{0} MyNat (nat_lit 2) (@MyNat.instOfNat (nat_lit 2))))
        (@HPow.hPow.{0, 0, 0} MyNat MyNat MyNat (@instHPow.{0, 0} MyNat MyNat MyNat.instPow) b
          (@OfNat.ofNat.{0} MyNat (nat_lit 2) (@MyNat.instOfNat (nat_lit 2)))))
      (@HMul.hMul.{0, 0, 0} MyNat MyNat MyNat (@instHMul.{0} MyNat MyNat.instMul)
        (@HMul.hMul.{0, 0, 0} MyNat MyNat MyNat (@instHMul.{0} MyNat MyNat.instMul)
          (@OfNat.ofNat.{0} MyNat (nat_lit 2) (@MyNat.instOfNat (nat_lit 2))) a)
        b)) := @MyNat.add_sq
#print axioms MyNat.add_sq
end
