-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: 9bc586e0149d7919504b15af0c32a5bbc590f9fb7831879b65da30c34f1a0585
-- Preserve these theorem statements when completing the exercise.

-- MyNat.mul_pow
section
set_option autoImplicit true in
example : ∀ (a b n : MyNat),
  @Eq.{1} MyNat
    (@HPow.hPow.{0, 0, 0} MyNat MyNat MyNat (@instHPow.{0, 0} MyNat MyNat MyNat.instPow)
      (@HMul.hMul.{0, 0, 0} MyNat MyNat MyNat (@instHMul.{0} MyNat MyNat.instMul) a b) n)
    (@HMul.hMul.{0, 0, 0} MyNat MyNat MyNat (@instHMul.{0} MyNat MyNat.instMul)
      (@HPow.hPow.{0, 0, 0} MyNat MyNat MyNat (@instHPow.{0, 0} MyNat MyNat MyNat.instPow) a n)
      (@HPow.hPow.{0, 0, 0} MyNat MyNat MyNat (@instHPow.{0, 0} MyNat MyNat MyNat.instPow) b n)) := @MyNat.mul_pow
#print axioms MyNat.mul_pow
end
