-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: 9db077f71d6dba6bc3cb6ac88170552217c424d6ea985d815c7cdf496ab8fad0
-- Preserve these theorem statements when completing the exercise.

-- MyNat.one_pow
section
set_option autoImplicit true in
example : ∀ (m : MyNat),
  @Eq.{1} MyNat
    (@HPow.hPow.{0, 0, 0} MyNat MyNat MyNat (@instHPow.{0, 0} MyNat MyNat MyNat.instPow)
      (@OfNat.ofNat.{0} MyNat (nat_lit 1) (@MyNat.instOfNat (nat_lit 1))) m)
    (@OfNat.ofNat.{0} MyNat (nat_lit 1) (@MyNat.instOfNat (nat_lit 1))) := @MyNat.one_pow
#print axioms MyNat.one_pow
end
