-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: 72fb899ebeefaf3f81ca2ae78f7998191efcdfea87b9a0cca3ee047907db93b0
-- Preserve these theorem statements when completing the exercise.

-- MyNat.pow_add
section
set_option autoImplicit true in
example : ∀ (a m n : MyNat),
  @Eq.{1} MyNat
    (@HPow.hPow.{0, 0, 0} MyNat MyNat MyNat (@instHPow.{0, 0} MyNat MyNat MyNat.instPow) a
      (@HAdd.hAdd.{0, 0, 0} MyNat MyNat MyNat (@instHAdd.{0} MyNat MyNat.instAdd) m n))
    (@HMul.hMul.{0, 0, 0} MyNat MyNat MyNat (@instHMul.{0} MyNat MyNat.instMul)
      (@HPow.hPow.{0, 0, 0} MyNat MyNat MyNat (@instHPow.{0, 0} MyNat MyNat MyNat.instPow) a m)
      (@HPow.hPow.{0, 0, 0} MyNat MyNat MyNat (@instHPow.{0, 0} MyNat MyNat MyNat.instPow) a n)) := @MyNat.pow_add
#print axioms MyNat.pow_add
end
