-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: 913cf7f52dadf2d7166bcd52218c63a0a3b5be836001d0b3c66a837665ab4f76
-- Preserve these theorem statements when completing the exercise.

-- MyNat.pow_two
section
set_option autoImplicit true in
example : ∀ (a : MyNat),
  @Eq.{1} MyNat
    (@HPow.hPow.{0, 0, 0} MyNat MyNat MyNat (@instHPow.{0, 0} MyNat MyNat MyNat.instPow) a
      (@OfNat.ofNat.{0} MyNat (nat_lit 2) (@MyNat.instOfNat (nat_lit 2))))
    (@HMul.hMul.{0, 0, 0} MyNat MyNat MyNat (@instHMul.{0} MyNat MyNat.instMul) a a) := @MyNat.pow_two
#print axioms MyNat.pow_two
end
