-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: ae62ef9c44979d8bd969487f8102ad2f337243b2f36a4b3fc833c6b11d6082d0
-- Preserve these theorem statements when completing the exercise.

-- MyNat.pow_pow
section
set_option autoImplicit true in
example : ∀ (a m n : MyNat),
  @Eq.{1} MyNat
    (@HPow.hPow.{0, 0, 0} MyNat MyNat MyNat (@instHPow.{0, 0} MyNat MyNat MyNat.instPow)
      (@HPow.hPow.{0, 0, 0} MyNat MyNat MyNat (@instHPow.{0, 0} MyNat MyNat MyNat.instPow) a m) n)
    (@HPow.hPow.{0, 0, 0} MyNat MyNat MyNat (@instHPow.{0, 0} MyNat MyNat MyNat.instPow) a
      (@HMul.hMul.{0, 0, 0} MyNat MyNat MyNat (@instHMul.{0} MyNat MyNat.instMul) m n)) := @MyNat.pow_pow
#print axioms MyNat.pow_pow
end
