-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: 380fcebe56775f8adb879bb76abe25a0f8e1411b1f374c3804da2aba37c3935e
-- Preserve these theorem statements when completing the exercise.

-- MyNat.pow_one
section
set_option autoImplicit true in
example : ∀ (a : MyNat),
  @Eq.{1} MyNat
    (@HPow.hPow.{0, 0, 0} MyNat MyNat MyNat (@instHPow.{0, 0} MyNat MyNat MyNat.instPow) a
      (@OfNat.ofNat.{0} MyNat (nat_lit 1) (@MyNat.instOfNat (nat_lit 1))))
    a := @MyNat.pow_one
#print axioms MyNat.pow_one
end
