-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: 46ca19fc1b0500f0b36c8ae8b005ac2abaea2893e3665b367bd0008d49567767
-- Preserve these theorem statements when completing the exercise.

-- MyNat.zero_pow_succ
section
set_option autoImplicit true in
example : ∀ (m : MyNat),
  @Eq.{1} MyNat
    (@HPow.hPow.{0, 0, 0} MyNat MyNat MyNat (@instHPow.{0, 0} MyNat MyNat MyNat.instPow)
      (@OfNat.ofNat.{0} MyNat (nat_lit 0) (@MyNat.instOfNat (nat_lit 0))) (MyNat.succ m))
    (@OfNat.ofNat.{0} MyNat (nat_lit 0) (@MyNat.instOfNat (nat_lit 0))) := @MyNat.zero_pow_succ
#print axioms MyNat.zero_pow_succ
end
