-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: 279ac8bf3faf96b5f7512a549e5041af655ad8e83035f08f9ceb8047b8d0a032
-- Preserve these theorem statements when completing the exercise.

-- MyNat.zero_pow_zero
section
set_option autoImplicit true in
example : @Eq.{1} MyNat
  (@HPow.hPow.{0, 0, 0} MyNat MyNat MyNat (@instHPow.{0, 0} MyNat MyNat MyNat.instPow)
    (@OfNat.ofNat.{0} MyNat (nat_lit 0) (@MyNat.instOfNat (nat_lit 0)))
    (@OfNat.ofNat.{0} MyNat (nat_lit 0) (@MyNat.instOfNat (nat_lit 0))))
  (@OfNat.ofNat.{0} MyNat (nat_lit 1) (@MyNat.instOfNat (nat_lit 1))) := @MyNat.zero_pow_zero
#print axioms MyNat.zero_pow_zero
end
