-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: 31aa7780586cd7d57e66abbdff5039659405ddbb2e7e9e35fc13975db76017d7
-- Preserve these theorem statements when completing the exercise.

-- MyNat.eq_succ_of_ne_zero
section
set_option autoImplicit true in
example : ∀ (a : MyNat),
  @Ne.{1} MyNat a (@OfNat.ofNat.{0} MyNat (nat_lit 0) (@MyNat.instOfNat (nat_lit 0))) →
    @Exists.{1} MyNat fun n => @Eq.{1} MyNat a (MyNat.succ n) := @MyNat.eq_succ_of_ne_zero
#print axioms MyNat.eq_succ_of_ne_zero
end
