-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: 8d8be729955bc9f8aa740063facb069ed3d93056125083ae3dedf4ce6a104233
-- Preserve these theorem statements when completing the exercise.

-- MyNat.le_mul_right
section
set_option autoImplicit true in
example : ∀ (a b : MyNat),
  @Ne.{1} MyNat (@HMul.hMul.{0, 0, 0} MyNat MyNat MyNat (@instHMul.{0} MyNat MyNat.instMul) a b)
      (@OfNat.ofNat.{0} MyNat (nat_lit 0) (@MyNat.instOfNat (nat_lit 0))) →
    @LE.le.{0} MyNat MyNat.instLE a (@HMul.hMul.{0, 0, 0} MyNat MyNat MyNat (@instHMul.{0} MyNat MyNat.instMul) a b) := @MyNat.le_mul_right
#print axioms MyNat.le_mul_right
end
