-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: 9c18966398992face2b8f0f37ddfd081792a0c5628b78571b966124478502c43
-- Preserve these theorem statements when completing the exercise.

-- MyNat.mul_eq_zero
section
set_option autoImplicit true in
example : ∀ (a b : MyNat),
  @Eq.{1} MyNat (@HMul.hMul.{0, 0, 0} MyNat MyNat MyNat (@instHMul.{0} MyNat MyNat.instMul) a b)
      (@OfNat.ofNat.{0} MyNat (nat_lit 0) (@MyNat.instOfNat (nat_lit 0))) →
    Or (@Eq.{1} MyNat a (@OfNat.ofNat.{0} MyNat (nat_lit 0) (@MyNat.instOfNat (nat_lit 0))))
      (@Eq.{1} MyNat b (@OfNat.ofNat.{0} MyNat (nat_lit 0) (@MyNat.instOfNat (nat_lit 0)))) := @MyNat.mul_eq_zero
#print axioms MyNat.mul_eq_zero
end
