-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: febd45067b03a2647a57d1d16797154ffa853f35f0e8d64522f695c6d9a0c0f5
-- Preserve these theorem statements when completing the exercise.

-- MyNat.mul_le_mul_right
section
set_option autoImplicit true in
example : ∀ (a b t : MyNat),
  @LE.le.{0} MyNat MyNat.instLE a b →
    @LE.le.{0} MyNat MyNat.instLE (@HMul.hMul.{0, 0, 0} MyNat MyNat MyNat (@instHMul.{0} MyNat MyNat.instMul) a t)
      (@HMul.hMul.{0, 0, 0} MyNat MyNat MyNat (@instHMul.{0} MyNat MyNat.instMul) b t) := @MyNat.mul_le_mul_right
#print axioms MyNat.mul_le_mul_right
end
