-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: 8127b58a04fb41458c23f4468d1bc4f9c5465f73a7d83037187881df242ea6bf
-- Preserve these theorem statements when completing the exercise.

-- MyNat.mul_ne_zero
section
set_option autoImplicit true in
example : ∀ (a b : MyNat),
  @Ne.{1} MyNat a (@OfNat.ofNat.{0} MyNat (nat_lit 0) (@MyNat.instOfNat (nat_lit 0))) →
    @Ne.{1} MyNat b (@OfNat.ofNat.{0} MyNat (nat_lit 0) (@MyNat.instOfNat (nat_lit 0))) →
      @Ne.{1} MyNat (@HMul.hMul.{0, 0, 0} MyNat MyNat MyNat (@instHMul.{0} MyNat MyNat.instMul) a b)
        (@OfNat.ofNat.{0} MyNat (nat_lit 0) (@MyNat.instOfNat (nat_lit 0))) := @MyNat.mul_ne_zero
#print axioms MyNat.mul_ne_zero
end
