-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: fe225e5c26357a154f0be7c14c6f73fb1affcc505e08d1eddf81fbc00af3bf26
-- Preserve these theorem statements when completing the exercise.

-- MyNat.mul_left_cancel
section
set_option autoImplicit true in
example : ∀ (a b c : MyNat),
  @Ne.{1} MyNat a (@OfNat.ofNat.{0} MyNat (nat_lit 0) (@MyNat.instOfNat (nat_lit 0))) →
    @Eq.{1} MyNat (@HMul.hMul.{0, 0, 0} MyNat MyNat MyNat (@instHMul.{0} MyNat MyNat.instMul) a b)
        (@HMul.hMul.{0, 0, 0} MyNat MyNat MyNat (@instHMul.{0} MyNat MyNat.instMul) a c) →
      @Eq.{1} MyNat b c := @MyNat.mul_left_cancel
#print axioms MyNat.mul_left_cancel
end
