-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: ae241012c2a4e324c822666758ea794e2bf7863899f938d629cf4d9a801653d9
-- Preserve these theorem statements when completing the exercise.

-- MyNat.mul_right_eq_one
section
set_option autoImplicit true in
example : ∀ (x y : MyNat),
  @Eq.{1} MyNat (@HMul.hMul.{0, 0, 0} MyNat MyNat MyNat (@instHMul.{0} MyNat MyNat.instMul) x y)
      (@OfNat.ofNat.{0} MyNat (nat_lit 1) (@MyNat.instOfNat (nat_lit 1))) →
    @Eq.{1} MyNat x (@OfNat.ofNat.{0} MyNat (nat_lit 1) (@MyNat.instOfNat (nat_lit 1))) := @MyNat.mul_right_eq_one
#print axioms MyNat.mul_right_eq_one
end
