-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: df7e03d23c6112b4a1024a5526f554a9273c3d02c6800cb783da125076f5e28e
-- Preserve these theorem statements when completing the exercise.

-- MyNat.mul_right_eq_self
section
set_option autoImplicit true in
example : ∀ (a b : MyNat),
  @Ne.{1} MyNat a (@OfNat.ofNat.{0} MyNat (nat_lit 0) (@MyNat.instOfNat (nat_lit 0))) →
    @Eq.{1} MyNat (@HMul.hMul.{0, 0, 0} MyNat MyNat MyNat (@instHMul.{0} MyNat MyNat.instMul) a b) a →
      @Eq.{1} MyNat b (@OfNat.ofNat.{0} MyNat (nat_lit 1) (@MyNat.instOfNat (nat_lit 1))) := @MyNat.mul_right_eq_self
#print axioms MyNat.mul_right_eq_self
end
