-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: b515b789bbcaacfc713ebc1c40380fcb9e73d8f9e0129b9d397a68f36c4a4c6e
-- Preserve these theorem statements when completing the exercise.

-- MyNat.mul_le_mul_right
section
set_option autoImplicit true in
example : ∀ (a b t : MyNat),
  @LE.le.{0} MyNat MyNat.instLE a b →
    @LE.le.{0} MyNat MyNat.instLE (@HMul.hMul.{0, 0, 0} MyNat MyNat MyNat (@instHMul.{0} MyNat MyNat.instMul) a t)
      (@HMul.hMul.{0, 0, 0} MyNat MyNat MyNat (@instHMul.{0} MyNat MyNat.instMul) b t) := @MyNat.mul_le_mul_right
#print axioms MyNat.mul_le_mul_right
end
