-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: a94a949ede06f185fecec5fc344d939f1e759e8065f404106aa496a852026830
-- Preserve these theorem statements when completing the exercise.

-- MyNat.mul_ne_zero
section
set_option autoImplicit true in
example : ∀ (a b : MyNat),
  @Ne.{1} MyNat a (@OfNat.ofNat.{0} MyNat (nat_lit 0) (@MyNat.instOfNat (nat_lit 0))) →
    @Ne.{1} MyNat b (@OfNat.ofNat.{0} MyNat (nat_lit 0) (@MyNat.instOfNat (nat_lit 0))) →
      @Ne.{1} MyNat (@HMul.hMul.{0, 0, 0} MyNat MyNat MyNat (@instHMul.{0} MyNat MyNat.instMul) a b)
        (@OfNat.ofNat.{0} MyNat (nat_lit 0) (@MyNat.instOfNat (nat_lit 0))) := @MyNat.mul_ne_zero
#print axioms MyNat.mul_ne_zero
end
