-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: d79a8aed75f43fec515cbe0a7b5d5161393b27e5d1cec8f992f4bca7fdbc2acc
-- Preserve these theorem statements when completing the exercise.

-- MyNat.one_le_of_ne_zero
section
set_option autoImplicit true in
example : ∀ (a : MyNat),
  @Ne.{1} MyNat a (@OfNat.ofNat.{0} MyNat (nat_lit 0) (@MyNat.instOfNat (nat_lit 0))) →
    @LE.le.{0} MyNat MyNat.instLE (@OfNat.ofNat.{0} MyNat (nat_lit 1) (@MyNat.instOfNat (nat_lit 1))) a := @MyNat.one_le_of_ne_zero
#print axioms MyNat.one_le_of_ne_zero
end
