-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: 7891b85eadea75fff7c2def689dfd6b7975625f61a7f86785debb89f3e802b58
-- Preserve these theorem statements when completing the exercise.

-- MyNat.exercise_algorithm_add_algo1
section
set_option autoImplicit true in
example : ∀ (a b c d : MyNat),
  @Eq.{1} MyNat
    (@HAdd.hAdd.{0, 0, 0} MyNat MyNat MyNat (@instHAdd.{0} MyNat MyNat.instAdd)
      (@HAdd.hAdd.{0, 0, 0} MyNat MyNat MyNat (@instHAdd.{0} MyNat MyNat.instAdd) a b)
      (@HAdd.hAdd.{0, 0, 0} MyNat MyNat MyNat (@instHAdd.{0} MyNat MyNat.instAdd) c d))
    (@HAdd.hAdd.{0, 0, 0} MyNat MyNat MyNat (@instHAdd.{0} MyNat MyNat.instAdd)
      (@HAdd.hAdd.{0, 0, 0} MyNat MyNat MyNat (@instHAdd.{0} MyNat MyNat.instAdd)
        (@HAdd.hAdd.{0, 0, 0} MyNat MyNat MyNat (@instHAdd.{0} MyNat MyNat.instAdd) a c) d)
      b) := @MyNat.exercise_algorithm_add_algo1
#print axioms MyNat.exercise_algorithm_add_algo1
end
