-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: 01403ab2d7bce91eb033aeaf02be5b1ceca248d97088df57236d8fa5d73f07ff
-- Preserve these theorem statements when completing the exercise.

-- MyNat.add_left_comm
section
set_option autoImplicit true in
example : ∀ (a b c : MyNat),
  @Eq.{1} MyNat
    (@HAdd.hAdd.{0, 0, 0} MyNat MyNat MyNat (@instHAdd.{0} MyNat MyNat.instAdd) a
      (@HAdd.hAdd.{0, 0, 0} MyNat MyNat MyNat (@instHAdd.{0} MyNat MyNat.instAdd) b c))
    (@HAdd.hAdd.{0, 0, 0} MyNat MyNat MyNat (@instHAdd.{0} MyNat MyNat.instAdd) b
      (@HAdd.hAdd.{0, 0, 0} MyNat MyNat MyNat (@instHAdd.{0} MyNat MyNat.instAdd) a c)) := @MyNat.add_left_comm
#print axioms MyNat.add_left_comm
end
