-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: 08338167cc5a2412b43d1165072598bdaf2b91d8aed767ca7c77b0b4055d6614
-- Preserve these theorem statements when completing the exercise.

-- MyNat.exercise_algorithm_decide
section
set_option autoImplicit true in
example : @Eq.{1} MyNat
  (@HAdd.hAdd.{0, 0, 0} MyNat MyNat MyNat (@instHAdd.{0} MyNat MyNat.instAdd)
    (@OfNat.ofNat.{0} MyNat (nat_lit 20) (@MyNat.instOfNat (nat_lit 20)))
    (@OfNat.ofNat.{0} MyNat (nat_lit 20) (@MyNat.instOfNat (nat_lit 20))))
  (@OfNat.ofNat.{0} MyNat (nat_lit 40) (@MyNat.instOfNat (nat_lit 40))) := @MyNat.exercise_algorithm_decide
#print axioms MyNat.exercise_algorithm_decide
end
