-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: b056add467643b1642cc628fd5577e348e08d5456ae64b5929f9cd2928749483
-- Preserve these theorem statements when completing the exercise.

-- MyNat.exercise_algorithm_decide2
section
set_option autoImplicit true in
example : @Ne.{1} MyNat
  (@HAdd.hAdd.{0, 0, 0} MyNat MyNat MyNat (@instHAdd.{0} MyNat MyNat.instAdd)
    (@OfNat.ofNat.{0} MyNat (nat_lit 2) (@MyNat.instOfNat (nat_lit 2)))
    (@OfNat.ofNat.{0} MyNat (nat_lit 2) (@MyNat.instOfNat (nat_lit 2))))
  (@OfNat.ofNat.{0} MyNat (nat_lit 5) (@MyNat.instOfNat (nat_lit 5))) := @MyNat.exercise_algorithm_decide2
#print axioms MyNat.exercise_algorithm_decide2
end
