-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: fd8d9b47b7293a8a3efde1de03ef303837dfaeedece7249ee73fba967dcea0a6
-- Preserve these theorem statements when completing the exercise.

-- MyNat.exercise_algorithm_pred
section
set_option autoImplicit true in
example : ∀ (a b : MyNat), @Eq.{1} MyNat (MyNat.succ a) (MyNat.succ b) → @Eq.{1} MyNat a b := @MyNat.exercise_algorithm_pred
#print axioms MyNat.exercise_algorithm_pred
end
