-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: db2ffd7053f6f911b6565aeb224f91131e9e65b54856b95f99f8efab1b91bb96
-- Preserve these theorem statements when completing the exercise.

-- MyNat.succ_ne_succ
section
set_option autoImplicit true in
example : ∀ (m n : MyNat), @Ne.{1} MyNat m n → @Ne.{1} MyNat (MyNat.succ m) (MyNat.succ n) := @MyNat.succ_ne_succ
#print axioms MyNat.succ_ne_succ
end
