-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: 6669929f70961a6e3fbd3351057fa95bff1c1406c081ddcd6a9bc4a06f921d44
-- Preserve these theorem statements when completing the exercise.

-- MyNat.succ_ne_succ
section
set_option autoImplicit true in
example : ∀ (m n : MyNat), @Ne.{1} MyNat m n → @Ne.{1} MyNat (MyNat.succ m) (MyNat.succ n) := @MyNat.succ_ne_succ
#print axioms MyNat.succ_ne_succ
end
