-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: 96fd6fd03a137428d0f8da7b8ffde6ca161bbfded8df0b388b43c6071898997d
-- Preserve these theorem statements when completing the exercise.

-- MyNat.succ_ne_zero
section
set_option autoImplicit true in
example : ∀ (a : MyNat), @Ne.{1} MyNat (MyNat.succ a) (@OfNat.ofNat.{0} MyNat (nat_lit 0) (@MyNat.instOfNat (nat_lit 0))) := @MyNat.succ_ne_zero
#print axioms MyNat.succ_ne_zero
end
