-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: e6427cad5b4589ccaeda0735b0b617a32d0d242e43dbca2a26b30a5c961ea93f
-- Preserve these theorem statements when completing the exercise.

-- Algebra.add_right_cancel
section
set_option autoImplicit true in
example : ∀ {R : Type u_1} [inst : Algebra.Ring.{u_1} R] (a b c : R),
  @Eq.{u_1 + 1} R (@HAdd.hAdd.{u_1, u_1, u_1} R R R (@instHAdd.{u_1} R (@Algebra.Ring.toAdd.{u_1} R inst)) a c)
      (@HAdd.hAdd.{u_1, u_1, u_1} R R R (@instHAdd.{u_1} R (@Algebra.Ring.toAdd.{u_1} R inst)) b c) →
    @Eq.{u_1 + 1} R a b := @Algebra.add_right_cancel
#print axioms Algebra.add_right_cancel
end
