-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: f09f766d9b2e80ffa029bcd08675b787b8c2111e4adabda128ba2bac8b322c28
-- Preserve these theorem statements when completing the exercise.

-- Algebra.add_left_cancel
section
set_option autoImplicit true in
example : ∀ {R : Type u_1} [inst : Algebra.Ring.{u_1} R] (a b c : R),
  @Eq.{u_1 + 1} R (@HAdd.hAdd.{u_1, u_1, u_1} R R R (@instHAdd.{u_1} R (@Algebra.Ring.toAdd.{u_1} R inst)) a b)
      (@HAdd.hAdd.{u_1, u_1, u_1} R R R (@instHAdd.{u_1} R (@Algebra.Ring.toAdd.{u_1} R inst)) a c) →
    @Eq.{u_1 + 1} R b c := @Algebra.add_left_cancel
#print axioms Algebra.add_left_cancel
end
