-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: 90fb74eaa04d452b7b916a9e9654e9d641292760778235a7348a036e4190be3e
-- Preserve these theorem statements when completing the exercise.

-- Algebra.add_neg_cancel
section
set_option autoImplicit true in
example : ∀ {R : Type u_1} [inst : Algebra.Ring.{u_1} R] (a : R),
  @Eq.{u_1 + 1} R
    (@HAdd.hAdd.{u_1, u_1, u_1} R R R (@instHAdd.{u_1} R (@Algebra.Ring.toAdd.{u_1} R inst)) a
      (@Neg.neg.{u_1} R (@Algebra.Ring.toNeg.{u_1} R inst) a))
    (@OfNat.ofNat.{u_1} R (nat_lit 0) (@Zero.toOfNat0.{u_1} R (@Algebra.Ring.toZero.{u_1} R inst))) := @Algebra.add_neg_cancel
#print axioms Algebra.add_neg_cancel
end
