-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: b66a4f56d3a7509d76d8420291c784cef58c255f20ca4e2a954ab6312217352b
-- Preserve these theorem statements when completing the exercise.

-- Algebra.mul_zero
section
set_option autoImplicit true in
example : ∀ {R : Type u_1} [inst : Algebra.Ring.{u_1} R] (a : R),
  @Eq.{u_1 + 1} R
    (@HMul.hMul.{u_1, u_1, u_1} R R R
      (@instHMul.{u_1} R
        (@Algebra.Magma.toMul.{u_1} R
          (@Algebra.Semigroup.toMagma.{u_1} R
            (@Algebra.Monoid.toSemigroup.{u_1} R (@Algebra.Ring.toMonoid.{u_1} R inst)))))
      a (@OfNat.ofNat.{u_1} R (nat_lit 0) (@Zero.toOfNat0.{u_1} R (@Algebra.Ring.toZero.{u_1} R inst))))
    (@OfNat.ofNat.{u_1} R (nat_lit 0) (@Zero.toOfNat0.{u_1} R (@Algebra.Ring.toZero.{u_1} R inst))) := @Algebra.mul_zero
#print axioms Algebra.mul_zero
end
