-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: 04cd85d335e3f1b34b5f6cb89910576f756f3f336c78f4f51bc51d0d62a93270
-- Preserve these theorem statements when completing the exercise.

-- Algebra.mul_neg
section
set_option autoImplicit true in
example : ∀ {R : Type u_1} [inst : Algebra.Ring.{u_1} R] (a b : R),
  @Eq.{u_1 + 1} R
    (@HMul.hMul.{u_1, u_1, u_1} R R R
      (@instHMul.{u_1} R
        (@Algebra.Magma.toMul.{u_1} R
          (@Algebra.Semigroup.toMagma.{u_1} R
            (@Algebra.Monoid.toSemigroup.{u_1} R (@Algebra.Ring.toMonoid.{u_1} R inst)))))
      a (@Neg.neg.{u_1} R (@Algebra.Ring.toNeg.{u_1} R inst) b))
    (@Neg.neg.{u_1} R (@Algebra.Ring.toNeg.{u_1} R inst)
      (@HMul.hMul.{u_1, u_1, u_1} R R R
        (@instHMul.{u_1} R
          (@Algebra.Magma.toMul.{u_1} R
            (@Algebra.Semigroup.toMagma.{u_1} R
              (@Algebra.Monoid.toSemigroup.{u_1} R (@Algebra.Ring.toMonoid.{u_1} R inst)))))
        a b)) := @Algebra.mul_neg
#print axioms Algebra.mul_neg
end
