-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: 9088c4e0a57fb81b9aa314008487be35fbc02b7619d4d856e3672a43a3691fd4
-- Preserve these theorem statements when completing the exercise.

-- Algebra.mul_add_mul
section
set_option autoImplicit true in
example : ∀ {R : Type u_1} [inst : Algebra.Ring.{u_1} R] (a b c d : R),
  @Eq.{u_1 + 1} R
    (@HMul.hMul.{u_1, u_1, u_1} R R R
      (@instHMul.{u_1} R
        (@Algebra.Magma.toMul.{u_1} R
          (@Algebra.Semigroup.toMagma.{u_1} R
            (@Algebra.Monoid.toSemigroup.{u_1} R (@Algebra.Ring.toMonoid.{u_1} R inst)))))
      (@HAdd.hAdd.{u_1, u_1, u_1} R R R (@instHAdd.{u_1} R (@Algebra.Ring.toAdd.{u_1} R inst)) a b)
      (@HAdd.hAdd.{u_1, u_1, u_1} R R R (@instHAdd.{u_1} R (@Algebra.Ring.toAdd.{u_1} R inst)) c d))
    (@HAdd.hAdd.{u_1, u_1, u_1} R R R (@instHAdd.{u_1} R (@Algebra.Ring.toAdd.{u_1} R inst))
      (@HAdd.hAdd.{u_1, u_1, u_1} R R R (@instHAdd.{u_1} R (@Algebra.Ring.toAdd.{u_1} R inst))
        (@HMul.hMul.{u_1, u_1, u_1} R R R
          (@instHMul.{u_1} R
            (@Algebra.Magma.toMul.{u_1} R
              (@Algebra.Semigroup.toMagma.{u_1} R
                (@Algebra.Monoid.toSemigroup.{u_1} R (@Algebra.Ring.toMonoid.{u_1} R inst)))))
          a c)
        (@HMul.hMul.{u_1, u_1, u_1} R R R
          (@instHMul.{u_1} R
            (@Algebra.Magma.toMul.{u_1} R
              (@Algebra.Semigroup.toMagma.{u_1} R
                (@Algebra.Monoid.toSemigroup.{u_1} R (@Algebra.Ring.toMonoid.{u_1} R inst)))))
          b c))
      (@HAdd.hAdd.{u_1, u_1, u_1} R R R (@instHAdd.{u_1} R (@Algebra.Ring.toAdd.{u_1} R inst))
        (@HMul.hMul.{u_1, u_1, u_1} R R R
          (@instHMul.{u_1} R
            (@Algebra.Magma.toMul.{u_1} R
              (@Algebra.Semigroup.toMagma.{u_1} R
                (@Algebra.Monoid.toSemigroup.{u_1} R (@Algebra.Ring.toMonoid.{u_1} R inst)))))
          a d)
        (@HMul.hMul.{u_1, u_1, u_1} R R R
          (@instHMul.{u_1} R
            (@Algebra.Magma.toMul.{u_1} R
              (@Algebra.Semigroup.toMagma.{u_1} R
                (@Algebra.Monoid.toSemigroup.{u_1} R (@Algebra.Ring.toMonoid.{u_1} R inst)))))
          b d))) := @Algebra.mul_add_mul
#print axioms Algebra.mul_add_mul
end
