-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: 5bcce2d9e5f839b7c9b51ec295efa8ea3e85fffa73b71a9b3516d1cd8f2435eb
-- Preserve these theorem statements when completing the exercise.

-- Algebra.mul_sub
section
set_option autoImplicit true in
example : ∀ {R : Type u_1} [inst : Algebra.Ring.{u_1} R] (a b c : R),
  @Eq.{u_1 + 1} R
    (@HMul.hMul.{u_1, u_1, u_1} R R R
      (@instHMul.{u_1} R
        (@Algebra.Magma.toMul.{u_1} R
          (@Algebra.Semigroup.toMagma.{u_1} R
            (@Algebra.Monoid.toSemigroup.{u_1} R (@Algebra.Ring.toMonoid.{u_1} R inst)))))
      a (@HSub.hSub.{u_1, u_1, u_1} R R R (@instHSub.{u_1} R (@Algebra.instRingSub.{u_1} R inst)) b c))
    (@HSub.hSub.{u_1, u_1, u_1} R R R (@instHSub.{u_1} R (@Algebra.instRingSub.{u_1} R inst))
      (@HMul.hMul.{u_1, u_1, u_1} R R R
        (@instHMul.{u_1} R
          (@Algebra.Magma.toMul.{u_1} R
            (@Algebra.Semigroup.toMagma.{u_1} R
              (@Algebra.Monoid.toSemigroup.{u_1} R (@Algebra.Ring.toMonoid.{u_1} R inst)))))
        a b)
      (@HMul.hMul.{u_1, u_1, u_1} R R R
        (@instHMul.{u_1} R
          (@Algebra.Magma.toMul.{u_1} R
            (@Algebra.Semigroup.toMagma.{u_1} R
              (@Algebra.Monoid.toSemigroup.{u_1} R (@Algebra.Ring.toMonoid.{u_1} R inst)))))
        a c)) := @Algebra.mul_sub
#print axioms Algebra.mul_sub
end
