-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: db78570f85378bd226727e792456c656768726b998f3fbfe7f1392ff2ae71754
-- Preserve these theorem statements when completing the exercise.

-- Algebra.neg_mul
section
set_option autoImplicit true in
example : ∀ {R : Type u_1} [inst : Algebra.Ring.{u_1} R] (a b : R),
  @Eq.{u_1 + 1} R
    (@HMul.hMul.{u_1, u_1, u_1} R R R
      (@instHMul.{u_1} R
        (@Algebra.Magma.toMul.{u_1} R
          (@Algebra.Semigroup.toMagma.{u_1} R
            (@Algebra.Monoid.toSemigroup.{u_1} R (@Algebra.Ring.toMonoid.{u_1} R inst)))))
      (@Neg.neg.{u_1} R (@Algebra.Ring.toNeg.{u_1} R inst) a) b)
    (@Neg.neg.{u_1} R (@Algebra.Ring.toNeg.{u_1} R inst)
      (@HMul.hMul.{u_1, u_1, u_1} R R R
        (@instHMul.{u_1} R
          (@Algebra.Magma.toMul.{u_1} R
            (@Algebra.Semigroup.toMagma.{u_1} R
              (@Algebra.Monoid.toSemigroup.{u_1} R (@Algebra.Ring.toMonoid.{u_1} R inst)))))
        a b)) := @Algebra.neg_mul
#print axioms Algebra.neg_mul
end
