-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: 703c03522254b31d076706c63161dfb2bfd24489025d33e4900b34fd768c80e8
-- Preserve these theorem statements when completing the exercise.

-- Algebra.neg_zero
section
set_option autoImplicit true in
example : ∀ {R : Type u_1} [inst : Algebra.Ring.{u_1} R],
  @Eq.{u_1 + 1} R
    (@Neg.neg.{u_1} R (@Algebra.Ring.toNeg.{u_1} R inst)
      (@OfNat.ofNat.{u_1} R (nat_lit 0) (@Zero.toOfNat0.{u_1} R (@Algebra.Ring.toZero.{u_1} R inst))))
    (@OfNat.ofNat.{u_1} R (nat_lit 0) (@Zero.toOfNat0.{u_1} R (@Algebra.Ring.toZero.{u_1} R inst))) := @Algebra.neg_zero
#print axioms Algebra.neg_zero
end
