-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: dc495dd3c5840fb366deb22d75869cd4dc248ddbeb51fb5c1de5d190e133db85
-- Preserve these theorem statements when completing the exercise.

-- Algebra.neg_mul_neg
section
set_option autoImplicit true in
example : ∀ {R : Type u_1} [inst : Algebra.Ring.{u_1} R] (a b : R),
  @Eq.{u_1 + 1} R
    (@HMul.hMul.{u_1, u_1, u_1} R R R
      (@instHMul.{u_1} R
        (@Algebra.Magma.toMul.{u_1} R
          (@Algebra.Semigroup.toMagma.{u_1} R
            (@Algebra.Monoid.toSemigroup.{u_1} R (@Algebra.Ring.toMonoid.{u_1} R inst)))))
      (@Neg.neg.{u_1} R (@Algebra.Ring.toNeg.{u_1} R inst) a) (@Neg.neg.{u_1} R (@Algebra.Ring.toNeg.{u_1} R inst) b))
    (@HMul.hMul.{u_1, u_1, u_1} R R R
      (@instHMul.{u_1} R
        (@Algebra.Magma.toMul.{u_1} R
          (@Algebra.Semigroup.toMagma.{u_1} R
            (@Algebra.Monoid.toSemigroup.{u_1} R (@Algebra.Ring.toMonoid.{u_1} R inst)))))
      a b) := @Algebra.neg_mul_neg
#print axioms Algebra.neg_mul_neg
end
