-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: c96a2913906ed8cbc35e0cff2743855a7d64399345f1359b6da67d4057f36b74
-- Preserve these theorem statements when completing the exercise.

-- Algebra.neg_neg
section
set_option autoImplicit true in
example : ∀ {R : Type u_1} [inst : Algebra.Ring.{u_1} R] (a : R),
  @Eq.{u_1 + 1} R
    (@Neg.neg.{u_1} R (@Algebra.Ring.toNeg.{u_1} R inst) (@Neg.neg.{u_1} R (@Algebra.Ring.toNeg.{u_1} R inst) a)) a := @Algebra.neg_neg
#print axioms Algebra.neg_neg
end
