-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: 81c3b4efbca0e3ef440fa09509cb79b924e24573ba3947c492b033df91da0276
-- Preserve these theorem statements when completing the exercise.

-- Algebra.neg_eq_of_add_eq_zero
section
set_option autoImplicit true in
example : ∀ {R : Type u_1} [inst : Algebra.Ring.{u_1} R] (a b : R),
  @Eq.{u_1 + 1} R (@HAdd.hAdd.{u_1, u_1, u_1} R R R (@instHAdd.{u_1} R (@Algebra.Ring.toAdd.{u_1} R inst)) a b)
      (@OfNat.ofNat.{u_1} R (nat_lit 0) (@Zero.toOfNat0.{u_1} R (@Algebra.Ring.toZero.{u_1} R inst))) →
    @Eq.{u_1 + 1} R (@Neg.neg.{u_1} R (@Algebra.Ring.toNeg.{u_1} R inst) a) b := @Algebra.neg_eq_of_add_eq_zero
#print axioms Algebra.neg_eq_of_add_eq_zero
end
