-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: 9e39c3664fe511ec19abeef608640cdd9f1e739b2be8b8aa7054fff1e41cf308
-- Preserve these theorem statements when completing the exercise.

-- Algebra.neg_add
section
set_option autoImplicit true in
example : ∀ {R : Type u_1} [inst : Algebra.Ring.{u_1} R] (a b : R),
  @Eq.{u_1 + 1} R
    (@Neg.neg.{u_1} R (@Algebra.Ring.toNeg.{u_1} R inst)
      (@HAdd.hAdd.{u_1, u_1, u_1} R R R (@instHAdd.{u_1} R (@Algebra.Ring.toAdd.{u_1} R inst)) a b))
    (@HAdd.hAdd.{u_1, u_1, u_1} R R R (@instHAdd.{u_1} R (@Algebra.Ring.toAdd.{u_1} R inst))
      (@Neg.neg.{u_1} R (@Algebra.Ring.toNeg.{u_1} R inst) b) (@Neg.neg.{u_1} R (@Algebra.Ring.toNeg.{u_1} R inst) a)) := @Algebra.neg_add
#print axioms Algebra.neg_add
end
