-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: 3b39abff67bd8cb2809b3dfe61a0ac85c154c4a59e1003edcbe84748ee6ffc77
-- Preserve these theorem statements when completing the exercise.

-- Algebra.sub_zero
section
set_option autoImplicit true in
example : ∀ {R : Type u_1} [inst : Algebra.Ring.{u_1} R] (a : R),
  @Eq.{u_1 + 1} R
    (@HSub.hSub.{u_1, u_1, u_1} R R R (@instHSub.{u_1} R (@Algebra.instRingSub.{u_1} R inst)) a
      (@OfNat.ofNat.{u_1} R (nat_lit 0) (@Zero.toOfNat0.{u_1} R (@Algebra.Ring.toZero.{u_1} R inst))))
    a := @Algebra.sub_zero
#print axioms Algebra.sub_zero
end
