-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: f7d08947b02fc0ab37cbff647ed346eb9f2cd2b3003fbda6532580e028c71496
-- Preserve these theorem statements when completing the exercise.

-- Algebra.sub_self
section
set_option autoImplicit true in
example : ∀ {R : Type u_1} [inst : Algebra.Ring.{u_1} R] (a : R),
  @Eq.{u_1 + 1} R (@HSub.hSub.{u_1, u_1, u_1} R R R (@instHSub.{u_1} R (@Algebra.instRingSub.{u_1} R inst)) a a)
    (@OfNat.ofNat.{u_1} R (nat_lit 0) (@Zero.toOfNat0.{u_1} R (@Algebra.Ring.toZero.{u_1} R inst))) := @Algebra.sub_self
#print axioms Algebra.sub_self
end
