-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: eb49a72044abc9864e6e792c3e2ad2317eae47dff58d565e45ca3e93ad54e8ee
-- Preserve these theorem statements when completing the exercise.

-- Algebra.sub_mul
section
set_option autoImplicit true in
example : ∀ {R : Type u_1} [inst : Algebra.Ring.{u_1} R] (a b c : R),
  @Eq.{u_1 + 1} R
    (@HMul.hMul.{u_1, u_1, u_1} R R R
      (@instHMul.{u_1} R
        (@Algebra.Magma.toMul.{u_1} R
          (@Algebra.Semigroup.toMagma.{u_1} R
            (@Algebra.Monoid.toSemigroup.{u_1} R (@Algebra.Ring.toMonoid.{u_1} R inst)))))
      (@HSub.hSub.{u_1, u_1, u_1} R R R (@instHSub.{u_1} R (@Algebra.instRingSub.{u_1} R inst)) a b) c)
    (@HSub.hSub.{u_1, u_1, u_1} R R R (@instHSub.{u_1} R (@Algebra.instRingSub.{u_1} R inst))
      (@HMul.hMul.{u_1, u_1, u_1} R R R
        (@instHMul.{u_1} R
          (@Algebra.Magma.toMul.{u_1} R
            (@Algebra.Semigroup.toMagma.{u_1} R
              (@Algebra.Monoid.toSemigroup.{u_1} R (@Algebra.Ring.toMonoid.{u_1} R inst)))))
        a c)
      (@HMul.hMul.{u_1, u_1, u_1} R R R
        (@instHMul.{u_1} R
          (@Algebra.Magma.toMul.{u_1} R
            (@Algebra.Semigroup.toMagma.{u_1} R
              (@Algebra.Monoid.toSemigroup.{u_1} R (@Algebra.Ring.toMonoid.{u_1} R inst)))))
        b c)) := @Algebra.sub_mul
#print axioms Algebra.sub_mul
end
