-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: 2e6508b7ef84ff0ad6d8691f77e58cbe7bb0b55509a9208adb0acb30ed6ecd69
-- Preserve these theorem statements when completing the exercise.

-- Algebra.zero_mul
section
set_option autoImplicit true in
example : ∀ {R : Type u_1} [inst : Algebra.Ring.{u_1} R] (a : R),
  @Eq.{u_1 + 1} R
    (@HMul.hMul.{u_1, u_1, u_1} R R R
      (@instHMul.{u_1} R
        (@Algebra.Magma.toMul.{u_1} R
          (@Algebra.Semigroup.toMagma.{u_1} R
            (@Algebra.Monoid.toSemigroup.{u_1} R (@Algebra.Ring.toMonoid.{u_1} R inst)))))
      (@OfNat.ofNat.{u_1} R (nat_lit 0) (@Zero.toOfNat0.{u_1} R (@Algebra.Ring.toZero.{u_1} R inst))) a)
    (@OfNat.ofNat.{u_1} R (nat_lit 0) (@Zero.toOfNat0.{u_1} R (@Algebra.Ring.toZero.{u_1} R inst))) := @Algebra.zero_mul
#print axioms Algebra.zero_mul
end
