-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: b120f4065b656eeb2e136ac5fc1afe15e9c967e61e58b81119017b1b4de0fca0
-- Preserve these theorem statements when completing the exercise.

-- Analysis.MyRat.add_zero
section
set_option autoImplicit true in
example : ∀ (x : Analysis.MyRat),
  @Eq.{1} Analysis.MyRat
    (@HAdd.hAdd.{0, 0, 0} Analysis.MyRat Analysis.MyRat Analysis.MyRat
      (@instHAdd.{0} Analysis.MyRat Analysis.MyRat.instAdd) x
      (@OfNat.ofNat.{0} Analysis.MyRat (nat_lit 0) (@Zero.toOfNat0.{0} Analysis.MyRat Analysis.MyRat.instZero)))
    x := @Analysis.MyRat.add_zero
#print axioms Analysis.MyRat.add_zero
end
