-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: d44eb1ba35f8a89c4f3c122d4e529759c07ded6f00f7caedb8c28006bcd727d6
-- Preserve these theorem statements when completing the exercise.

-- Analysis.MyRat.add_zero
section
set_option autoImplicit true in
example : ∀ (x : Analysis.MyRat),
  @Eq.{1} Analysis.MyRat
    (@HAdd.hAdd.{0, 0, 0} Analysis.MyRat Analysis.MyRat Analysis.MyRat
      (@instHAdd.{0} Analysis.MyRat Analysis.MyRat.instAdd) x
      (@OfNat.ofNat.{0} Analysis.MyRat (nat_lit 0) (@Zero.toOfNat0.{0} Analysis.MyRat Analysis.MyRat.instZero)))
    x := @Analysis.MyRat.add_zero
#print axioms Analysis.MyRat.add_zero
end
