-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: 028b8674553dad210829e2cd5fc96c33f7e785a0fe080e0796519708a02701f7
-- Preserve these theorem statements when completing the exercise.

-- Analysis.MyRat.add_assoc
section
set_option autoImplicit true in
example : ∀ (x y z : Analysis.MyRat),
  @Eq.{1} Analysis.MyRat
    (@HAdd.hAdd.{0, 0, 0} Analysis.MyRat Analysis.MyRat Analysis.MyRat
      (@instHAdd.{0} Analysis.MyRat Analysis.MyRat.instAdd)
      (@HAdd.hAdd.{0, 0, 0} Analysis.MyRat Analysis.MyRat Analysis.MyRat
        (@instHAdd.{0} Analysis.MyRat Analysis.MyRat.instAdd) x y)
      z)
    (@HAdd.hAdd.{0, 0, 0} Analysis.MyRat Analysis.MyRat Analysis.MyRat
      (@instHAdd.{0} Analysis.MyRat Analysis.MyRat.instAdd) x
      (@HAdd.hAdd.{0, 0, 0} Analysis.MyRat Analysis.MyRat Analysis.MyRat
        (@instHAdd.{0} Analysis.MyRat Analysis.MyRat.instAdd) y z)) := @Analysis.MyRat.add_assoc
#print axioms Analysis.MyRat.add_assoc
end
