-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: 402278e61b897a067f0caa26dcffc24b28df179d354439450936a7e401b96326
-- Preserve these theorem statements when completing the exercise.

-- Analysis.MyRat.add_comm
section
set_option autoImplicit true in
example : ∀ (x y : Analysis.MyRat),
  @Eq.{1} Analysis.MyRat
    (@HAdd.hAdd.{0, 0, 0} Analysis.MyRat Analysis.MyRat Analysis.MyRat
      (@instHAdd.{0} Analysis.MyRat Analysis.MyRat.instAdd) x y)
    (@HAdd.hAdd.{0, 0, 0} Analysis.MyRat Analysis.MyRat Analysis.MyRat
      (@instHAdd.{0} Analysis.MyRat Analysis.MyRat.instAdd) y x) := @Analysis.MyRat.add_comm
#print axioms Analysis.MyRat.add_comm
end
