-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: 8c8f6aa6dcf38e2d940f84c8c016a7028c97bb536d91642d4eefb63d93bef7fc
-- Preserve these theorem statements when completing the exercise.

-- Analysis.MyRat.left_distrib
section
set_option autoImplicit true in
example : ∀ (x y z : Analysis.MyRat),
  @Eq.{1} Analysis.MyRat
    (@HMul.hMul.{0, 0, 0} Analysis.MyRat Analysis.MyRat Analysis.MyRat
      (@instHMul.{0} Analysis.MyRat Analysis.MyRat.instMul) x
      (@HAdd.hAdd.{0, 0, 0} Analysis.MyRat Analysis.MyRat Analysis.MyRat
        (@instHAdd.{0} Analysis.MyRat Analysis.MyRat.instAdd) y z))
    (@HAdd.hAdd.{0, 0, 0} Analysis.MyRat Analysis.MyRat Analysis.MyRat
      (@instHAdd.{0} Analysis.MyRat Analysis.MyRat.instAdd)
      (@HMul.hMul.{0, 0, 0} Analysis.MyRat Analysis.MyRat Analysis.MyRat
        (@instHMul.{0} Analysis.MyRat Analysis.MyRat.instMul) x y)
      (@HMul.hMul.{0, 0, 0} Analysis.MyRat Analysis.MyRat Analysis.MyRat
        (@instHMul.{0} Analysis.MyRat Analysis.MyRat.instMul) x z)) := @Analysis.MyRat.left_distrib
#print axioms Analysis.MyRat.left_distrib
end
