-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: 16cda5e915411cd77984f9c1b91e9f8b7c2f8b657dcd0d489b3c4928d0f89f54
-- Preserve these theorem statements when completing the exercise.

-- Analysis.MyRat.mul_assoc
section
set_option autoImplicit true in
example : ∀ (x y z : Analysis.MyRat),
  @Eq.{1} Analysis.MyRat
    (@HMul.hMul.{0, 0, 0} Analysis.MyRat Analysis.MyRat Analysis.MyRat
      (@instHMul.{0} Analysis.MyRat Analysis.MyRat.instMul)
      (@HMul.hMul.{0, 0, 0} Analysis.MyRat Analysis.MyRat Analysis.MyRat
        (@instHMul.{0} Analysis.MyRat Analysis.MyRat.instMul) x y)
      z)
    (@HMul.hMul.{0, 0, 0} Analysis.MyRat Analysis.MyRat Analysis.MyRat
      (@instHMul.{0} Analysis.MyRat Analysis.MyRat.instMul) x
      (@HMul.hMul.{0, 0, 0} Analysis.MyRat Analysis.MyRat Analysis.MyRat
        (@instHMul.{0} Analysis.MyRat Analysis.MyRat.instMul) y z)) := @Analysis.MyRat.mul_assoc
#print axioms Analysis.MyRat.mul_assoc
end
