-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: 37009e147337e6a59d8bf061c786d1c09c43bcb5a58477542a7a2067a9054e83
-- Preserve these theorem statements when completing the exercise.

-- Analysis.MyRat.mul_zero
section
set_option autoImplicit true in
example : ∀ (x : Analysis.MyRat),
  @Eq.{1} Analysis.MyRat
    (@HMul.hMul.{0, 0, 0} Analysis.MyRat Analysis.MyRat Analysis.MyRat
      (@instHMul.{0} Analysis.MyRat Analysis.MyRat.instMul) x
      (@OfNat.ofNat.{0} Analysis.MyRat (nat_lit 0) (@Zero.toOfNat0.{0} Analysis.MyRat Analysis.MyRat.instZero)))
    (@OfNat.ofNat.{0} Analysis.MyRat (nat_lit 0) (@Zero.toOfNat0.{0} Analysis.MyRat Analysis.MyRat.instZero)) := @Analysis.MyRat.mul_zero
#print axioms Analysis.MyRat.mul_zero
end
