-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: 937e001b9e0ed44255b8b7a65b8badd8fe64dbfd7d254debfecf11f696d5b05d
-- Preserve these theorem statements when completing the exercise.

-- Analysis.MyRat.mul_inv_cancel
section
set_option autoImplicit true in
example : ∀ (x : Analysis.MyRat),
  @Ne.{1} Analysis.MyRat x
      (@OfNat.ofNat.{0} Analysis.MyRat (nat_lit 0) (@Zero.toOfNat0.{0} Analysis.MyRat Analysis.MyRat.instZero)) →
    @Eq.{1} Analysis.MyRat
      (@HMul.hMul.{0, 0, 0} Analysis.MyRat Analysis.MyRat Analysis.MyRat
        (@instHMul.{0} Analysis.MyRat Analysis.MyRat.instMul) x (@Inv.inv.{0} Analysis.MyRat Analysis.MyRat.instInv x))
      (@OfNat.ofNat.{0} Analysis.MyRat (nat_lit 1) (@One.toOfNat1.{0} Analysis.MyRat Analysis.MyRat.instOne)) := @Analysis.MyRat.mul_inv_cancel
#print axioms Analysis.MyRat.mul_inv_cancel
end
