-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: 9b4c760226f6bfbfd06e86a235e93bd5c6df6c760eadf7c52ddaa4a14a7b381f
-- Preserve these theorem statements when completing the exercise.

-- Analysis.MyRat.mul_one
section
set_option autoImplicit true in
example : ∀ (x : Analysis.MyRat),
  @Eq.{1} Analysis.MyRat
    (@HMul.hMul.{0, 0, 0} Analysis.MyRat Analysis.MyRat Analysis.MyRat
      (@instHMul.{0} Analysis.MyRat Analysis.MyRat.instMul) x
      (@OfNat.ofNat.{0} Analysis.MyRat (nat_lit 1) (@One.toOfNat1.{0} Analysis.MyRat Analysis.MyRat.instOne)))
    x := @Analysis.MyRat.mul_one
#print axioms Analysis.MyRat.mul_one
end
