-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: f97d3c25a114006b9b3847fa055d357bb96a0412ce72773b28f234126f934a46
-- Preserve these theorem statements when completing the exercise.

-- Analysis.MyRat.mul_one
section
set_option autoImplicit true in
example : ∀ (x : Analysis.MyRat),
  @Eq.{1} Analysis.MyRat
    (@HMul.hMul.{0, 0, 0} Analysis.MyRat Analysis.MyRat Analysis.MyRat
      (@instHMul.{0} Analysis.MyRat Analysis.MyRat.instMul) x
      (@OfNat.ofNat.{0} Analysis.MyRat (nat_lit 1) (@One.toOfNat1.{0} Analysis.MyRat Analysis.MyRat.instOne)))
    x := @Analysis.MyRat.mul_one
#print axioms Analysis.MyRat.mul_one
end
