-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: 5600394530ca346e9168408b1ef5056620e44057701c02d99da08841edb469d4
-- Preserve these theorem statements when completing the exercise.

-- Analysis.MyRat.mul_comm
section
set_option autoImplicit true in
example : ∀ (x y : Analysis.MyRat),
  @Eq.{1} Analysis.MyRat
    (@HMul.hMul.{0, 0, 0} Analysis.MyRat Analysis.MyRat Analysis.MyRat
      (@instHMul.{0} Analysis.MyRat Analysis.MyRat.instMul) x y)
    (@HMul.hMul.{0, 0, 0} Analysis.MyRat Analysis.MyRat Analysis.MyRat
      (@instHMul.{0} Analysis.MyRat Analysis.MyRat.instMul) y x) := @Analysis.MyRat.mul_comm
#print axioms Analysis.MyRat.mul_comm
end
