-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: e7dd068b6f35a60e79b6ac5700d38d8e3cd8add305251abde0ded58ef0e14d3d
-- Preserve these theorem statements when completing the exercise.

-- Analysis.MyRat.neg_add_cancel
section
set_option autoImplicit true in
example : ∀ (x : Analysis.MyRat),
  @Eq.{1} Analysis.MyRat
    (@HAdd.hAdd.{0, 0, 0} Analysis.MyRat Analysis.MyRat Analysis.MyRat
      (@instHAdd.{0} Analysis.MyRat Analysis.MyRat.instAdd) (@Neg.neg.{0} Analysis.MyRat Analysis.MyRat.instNeg x) x)
    (@OfNat.ofNat.{0} Analysis.MyRat (nat_lit 0) (@Zero.toOfNat0.{0} Analysis.MyRat Analysis.MyRat.instZero)) := @Analysis.MyRat.neg_add_cancel
#print axioms Analysis.MyRat.neg_add_cancel
end
