-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: 5de418032f24949ad64d7066012b055fa3c06c2292c7b2b4e7ded06a8a75e652
-- Preserve these theorem statements when completing the exercise.

-- Analysis.MyRat.neg_neg
section
set_option autoImplicit true in
example : ∀ (x : Analysis.MyRat),
  @Eq.{1} Analysis.MyRat
    (@Neg.neg.{0} Analysis.MyRat Analysis.MyRat.instNeg (@Neg.neg.{0} Analysis.MyRat Analysis.MyRat.instNeg x)) x := @Analysis.MyRat.neg_neg
#print axioms Analysis.MyRat.neg_neg
end
