-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: a3bace0e82042d20f3af965175e6b8d38c40108d5f09990b3d4e1f7390fbf581
-- Preserve these theorem statements when completing the exercise.

-- Analysis.MyRat.one_mul
section
set_option autoImplicit true in
example : ∀ (x : Analysis.MyRat),
  @Eq.{1} Analysis.MyRat
    (@HMul.hMul.{0, 0, 0} Analysis.MyRat Analysis.MyRat Analysis.MyRat
      (@instHMul.{0} Analysis.MyRat Analysis.MyRat.instMul)
      (@OfNat.ofNat.{0} Analysis.MyRat (nat_lit 1) (@One.toOfNat1.{0} Analysis.MyRat Analysis.MyRat.instOne)) x)
    x := @Analysis.MyRat.one_mul
#print axioms Analysis.MyRat.one_mul
end
