-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: dc68f04f135a830915fd548ca86ba9996ec270f0dc84bc24acd187dd2495131e
-- Preserve these theorem statements when completing the exercise.

-- Analysis.MyRat.right_distrib
section
set_option autoImplicit true in
example : ∀ (x y z : Analysis.MyRat),
  @Eq.{1} Analysis.MyRat
    (@HMul.hMul.{0, 0, 0} Analysis.MyRat Analysis.MyRat Analysis.MyRat
      (@instHMul.{0} Analysis.MyRat Analysis.MyRat.instMul)
      (@HAdd.hAdd.{0, 0, 0} Analysis.MyRat Analysis.MyRat Analysis.MyRat
        (@instHAdd.{0} Analysis.MyRat Analysis.MyRat.instAdd) x y)
      z)
    (@HAdd.hAdd.{0, 0, 0} Analysis.MyRat Analysis.MyRat Analysis.MyRat
      (@instHAdd.{0} Analysis.MyRat Analysis.MyRat.instAdd)
      (@HMul.hMul.{0, 0, 0} Analysis.MyRat Analysis.MyRat Analysis.MyRat
        (@instHMul.{0} Analysis.MyRat Analysis.MyRat.instMul) x z)
      (@HMul.hMul.{0, 0, 0} Analysis.MyRat Analysis.MyRat Analysis.MyRat
        (@instHMul.{0} Analysis.MyRat Analysis.MyRat.instMul) y z)) := @Analysis.MyRat.right_distrib
#print axioms Analysis.MyRat.right_distrib
end
