-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: 10ab7bb0e76a80ac6c07ae075d3facbdd4caaefc90c263fa87ae207484f57a34
-- Preserve these theorem statements when completing the exercise.

-- Analysis.MyRat.zero_add
section
set_option autoImplicit true in
example : ∀ (x : Analysis.MyRat),
  @Eq.{1} Analysis.MyRat
    (@HAdd.hAdd.{0, 0, 0} Analysis.MyRat Analysis.MyRat Analysis.MyRat
      (@instHAdd.{0} Analysis.MyRat Analysis.MyRat.instAdd)
      (@OfNat.ofNat.{0} Analysis.MyRat (nat_lit 0) (@Zero.toOfNat0.{0} Analysis.MyRat Analysis.MyRat.instZero)) x)
    x := @Analysis.MyRat.zero_add
#print axioms Analysis.MyRat.zero_add
end
