-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: 0556c7cebbaf6d15ab9433cdea488f6f196d99cdb7fb68b76e735cb418625b9d
-- Preserve these theorem statements when completing the exercise.

-- exists_relabel
section
set_option autoImplicit true in
example : (@Exists.{1} Nat fun n =>
    @Eq.{1} Nat (@HAdd.hAdd.{0, 0, 0} Nat Nat Nat (@instHAdd.{0} Nat instAddNat) n n)
      (@OfNat.ofNat.{0} Nat (nat_lit 10) (instOfNatNat (nat_lit 10)))) →
  @Exists.{1} Nat fun m =>
    @Eq.{1} Nat (@HAdd.hAdd.{0, 0, 0} Nat Nat Nat (@instHAdd.{0} Nat instAddNat) m m)
      (@OfNat.ofNat.{0} Nat (nat_lit 10) (instOfNatNat (nat_lit 10))) := @exists_relabel
#print axioms exists_relabel
end

-- exists_succ_gt_one
section
set_option autoImplicit true in
example : (@Exists.{1} Nat fun n => @GT.gt.{0} Nat instLTNat n (@OfNat.ofNat.{0} Nat (nat_lit 0) (instOfNatNat (nat_lit 0)))) →
  @Exists.{1} Nat fun m => @GT.gt.{0} Nat instLTNat m (@OfNat.ofNat.{0} Nat (nat_lit 1) (instOfNatNat (nat_lit 1))) := @exists_succ_gt_one
#print axioms exists_succ_gt_one
end
