-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: 64b88a0bcc069ec20a6fd8f75f036434ab9301b247892900ba6d3e0a1f17fa37
-- Preserve these theorem statements when completing the exercise.

-- exists_double
section
set_option autoImplicit true in
example : @Exists.{1} Nat fun n =>
  @Eq.{1} Nat (@HAdd.hAdd.{0, 0, 0} Nat Nat Nat (@instHAdd.{0} Nat instAddNat) n n)
    (@OfNat.ofNat.{0} Nat (nat_lit 10) (instOfNatNat (nat_lit 10))) := @exists_double
#print axioms exists_double
end

-- exists_greater
section
set_option autoImplicit true in
example : ∀ (n : Nat), @Exists.{1} Nat fun m => @GT.gt.{0} Nat instLTNat m n := @exists_greater
#print axioms exists_greater
end

-- exists_gt_five
section
set_option autoImplicit true in
example : @Exists.{1} Nat fun n => @GT.gt.{0} Nat instLTNat n (@OfNat.ofNat.{0} Nat (nat_lit 5) (instOfNatNat (nat_lit 5))) := @exists_gt_five
#print axioms exists_gt_five
end
