-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: dbd22467fb03376e76ea6151de365945700d3e75dcce38cd2a718a05187d2246
-- Preserve these theorem statements when completing the exercise.

-- arith1
section
set_option autoImplicit true in
example : @Eq.{1} Nat
  (@HAdd.hAdd.{0, 0, 0} Nat Nat Nat (@instHAdd.{0} Nat instAddNat)
    (@OfNat.ofNat.{0} Nat (nat_lit 2) (instOfNatNat (nat_lit 2)))
    (@OfNat.ofNat.{0} Nat (nat_lit 3) (instOfNatNat (nat_lit 3))))
  (@OfNat.ofNat.{0} Nat (nat_lit 5) (instOfNatNat (nat_lit 5))) := @arith1
#print axioms arith1
end

-- arith2
section
set_option autoImplicit true in
example : ∀ (n : Nat),
  @Eq.{1} Nat
    (@HAdd.hAdd.{0, 0, 0} Nat Nat Nat (@instHAdd.{0} Nat instAddNat) n
      (@OfNat.ofNat.{0} Nat (nat_lit 0) (instOfNatNat (nat_lit 0))))
    n := @arith2
#print axioms arith2
end

-- decide_example
section
set_option autoImplicit true in
example : @LT.lt.{0} Nat instLTNat (@OfNat.ofNat.{0} Nat (nat_lit 2) (instOfNatNat (nat_lit 2)))
  (@OfNat.ofNat.{0} Nat (nat_lit 5) (instOfNatNat (nat_lit 5))) := @decide_example
#print axioms decide_example
end

-- simp_example
section
set_option autoImplicit true in
example : ∀ (l : List.{0} Nat),
  @Eq.{1} (List.{0} Nat)
    (@HAppend.hAppend.{0, 0, 0} (List.{0} Nat) (List.{0} Nat) (List.{0} Nat)
      (@instHAppendOfAppend.{0} (List.{0} Nat) (@List.instAppend.{0} Nat)) l (@List.nil.{0} Nat))
    l := @simp_example
#print axioms simp_example
end
