-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: 40a79dd0601cdc19ae69aaf79f5bc38e07b4a4809ed3cd8f2f4ef10809819ca4
-- Preserve these theorem statements when completing the exercise.

-- rewrite_back
section
set_option autoImplicit true in
example : ∀ (a b : Nat),
  @Eq.{1} Nat a b →
    @Eq.{1} Nat
        (@HAdd.hAdd.{0, 0, 0} Nat Nat Nat (@instHAdd.{0} Nat instAddNat) a
          (@OfNat.ofNat.{0} Nat (nat_lit 1) (instOfNatNat (nat_lit 1))))
        (@OfNat.ofNat.{0} Nat (nat_lit 5) (instOfNatNat (nat_lit 5))) →
      @Eq.{1} Nat
        (@HAdd.hAdd.{0, 0, 0} Nat Nat Nat (@instHAdd.{0} Nat instAddNat) b
          (@OfNat.ofNat.{0} Nat (nat_lit 1) (instOfNatNat (nat_lit 1))))
        (@OfNat.ofNat.{0} Nat (nat_lit 5) (instOfNatNat (nat_lit 5))) := @rewrite_back
#print axioms rewrite_back
end

-- rewrite_chain
section
set_option autoImplicit true in
example : ∀ (a b c : Nat), @Eq.{1} Nat a b → @Eq.{1} Nat b c → @Eq.{1} Nat a c := @rewrite_chain
#print axioms rewrite_chain
end

-- rewrite_example
section
set_option autoImplicit true in
example : ∀ (a b : Nat),
  @Eq.{1} Nat a b →
    @Eq.{1} Nat
      (@HAdd.hAdd.{0, 0, 0} Nat Nat Nat (@instHAdd.{0} Nat instAddNat) a
        (@OfNat.ofNat.{0} Nat (nat_lit 1) (instOfNatNat (nat_lit 1))))
      (@HAdd.hAdd.{0, 0, 0} Nat Nat Nat (@instHAdd.{0} Nat instAddNat) b
        (@OfNat.ofNat.{0} Nat (nat_lit 1) (instOfNatNat (nat_lit 1)))) := @rewrite_example
#print axioms rewrite_example
end
