-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: 05a84806f6ead7ff82a360eb007843c61dacb4d1f5348bf976e7d4e845e970b6
-- Preserve these theorem statements when completing the exercise.

-- and_intro
section
set_option autoImplicit true in
example : ∀ (P Q : Prop), P → Q → And P Q := @and_intro
#print axioms and_intro
end

-- and_map
section
set_option autoImplicit true in
example : ∀ (P Q R : Prop), And P Q → (Q → R) → And P R := @and_map
#print axioms and_map
end

-- and_swap
section
set_option autoImplicit true in
example : ∀ (P Q : Prop), And P Q → And Q P := @and_swap
#print axioms and_swap
end

-- apply_example
section
set_option autoImplicit true in
example : ∀ (P Q : Prop), P → (P → Q) → Q := @apply_example
#print axioms apply_example
end
