-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: 6579c919bf01579aeab9ca803c626b2596ebe2b08fe8431baae1acec9c42fbb0
-- Preserve these theorem statements when completing the exercise.

-- compose
section
set_option autoImplicit true in
example : ∀ (P Q R : Prop), (P → Q) → (Q → R) → P → R := @compose
#print axioms compose
end

-- self_implication
section
set_option autoImplicit true in
example : ∀ (P : Prop), P → P := @self_implication
#print axioms self_implication
end

-- use_second
section
set_option autoImplicit true in
example : ∀ (P Q : Prop), P → Q → Q := @use_second
#print axioms use_second
end
