-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: 4a073fbeb788b1b51daaff8cd0367334334f2487bc0967a4821734561de7cb13
-- Preserve these theorem statements when completing the exercise.

-- MyNat.le_antisymm
section
set_option autoImplicit true in
example : ∀ (x y : MyNat), @LE.le.{0} MyNat MyNat.instLE x y → @LE.le.{0} MyNat MyNat.instLE y x → @Eq.{1} MyNat x y := @MyNat.le_antisymm
#print axioms MyNat.le_antisymm
end
