-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: 4157faa1ac6ead6a9f0ae93d1f4a88458323163d93394ef1104b11118246f7d6
-- Preserve these theorem statements when completing the exercise.

-- MyNat.le_antisymm
section
set_option autoImplicit true in
example : ∀ (x y : MyNat), @LE.le.{0} MyNat MyNat.instLE x y → @LE.le.{0} MyNat MyNat.instLE y x → @Eq.{1} MyNat x y := @MyNat.le_antisymm
#print axioms MyNat.le_antisymm
end
