-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: e70d74a66c286f087376c0a649fcde3c380d61892af35daecb7d7096c5a996a3
-- Preserve these theorem statements when completing the exercise.

-- MyNat.le_one
section
set_option autoImplicit true in
example : ∀ (x : MyNat),
  @LE.le.{0} MyNat MyNat.instLE x (@OfNat.ofNat.{0} MyNat (nat_lit 1) (@MyNat.instOfNat (nat_lit 1))) →
    Or (@Eq.{1} MyNat x (@OfNat.ofNat.{0} MyNat (nat_lit 0) (@MyNat.instOfNat (nat_lit 0))))
      (@Eq.{1} MyNat x (@OfNat.ofNat.{0} MyNat (nat_lit 1) (@MyNat.instOfNat (nat_lit 1)))) := @MyNat.le_one
#print axioms MyNat.le_one
end
