-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: 15892c699e30ee253b0bb3b0ca582bcdfeb16ee57f89e72f6c9d4ea0139e6bfd
-- Preserve these theorem statements when completing the exercise.

-- MyNat.le_one
section
set_option autoImplicit true in
example : ∀ (x : MyNat),
  @LE.le.{0} MyNat MyNat.instLE x (@OfNat.ofNat.{0} MyNat (nat_lit 1) (@MyNat.instOfNat (nat_lit 1))) →
    Or (@Eq.{1} MyNat x (@OfNat.ofNat.{0} MyNat (nat_lit 0) (@MyNat.instOfNat (nat_lit 0))))
      (@Eq.{1} MyNat x (@OfNat.ofNat.{0} MyNat (nat_lit 1) (@MyNat.instOfNat (nat_lit 1)))) := @MyNat.le_one
#print axioms MyNat.le_one
end
