-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: 21c3bfe35afa01bc2aa6ef7c7ec6f1132e1e421c841f338d4bcfa3571d12865e
-- Preserve these theorem statements when completing the exercise.

-- MyNat.le_refl
section
set_option autoImplicit true in
example : ∀ (x : MyNat), @LE.le.{0} MyNat MyNat.instLE x x := @MyNat.le_refl
#print axioms MyNat.le_refl
end
