-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: f235c94fe416169dc8139686457942a87c6e8a9a6b1aa8bbeefc5c0afa5673d5
-- Preserve these theorem statements when completing the exercise.

-- MyNat.le_refl
section
set_option autoImplicit true in
example : ∀ (x : MyNat), @LE.le.{0} MyNat MyNat.instLE x x := @MyNat.le_refl
#print axioms MyNat.le_refl
end
