-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: 6fdbc14d2c00f42f35b0e7ca8b7778872f560f5d9def20e9b6203614864ea8e9
-- Preserve these theorem statements when completing the exercise.

-- MyNat.le_succ_self
section
set_option autoImplicit true in
example : ∀ (x : MyNat), @LE.le.{0} MyNat MyNat.instLE x (MyNat.succ x) := @MyNat.le_succ_self
#print axioms MyNat.le_succ_self
end
