-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: 3e0b4a61847d45fd43061b2ff3ecf835b9987c92185659dc0360f1239729086a
-- Preserve these theorem statements when completing the exercise.

-- MyNat.le_succ_self
section
set_option autoImplicit true in
example : ∀ (x : MyNat), @LE.le.{0} MyNat MyNat.instLE x (MyNat.succ x) := @MyNat.le_succ_self
#print axioms MyNat.le_succ_self
end
