-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: bfef8264172939773e38464b9c4617fed2dfa4076e5750d4ae53a6b12567589e
-- Preserve these theorem statements when completing the exercise.

-- MyNat.le_trans
section
set_option autoImplicit true in
example : ∀ (x y z : MyNat),
  @LE.le.{0} MyNat MyNat.instLE x y → @LE.le.{0} MyNat MyNat.instLE y z → @LE.le.{0} MyNat MyNat.instLE x z := @MyNat.le_trans
#print axioms MyNat.le_trans
end
