-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: 7b78b727c6049dc18fccfdcee08d24e337fb8bc5fa6f85cc4cfc2ed9649f43d9
-- Preserve these theorem statements when completing the exercise.

-- MyNat.le_total
section
set_option autoImplicit true in
example : ∀ (x y : MyNat), Or (@LE.le.{0} MyNat MyNat.instLE x y) (@LE.le.{0} MyNat MyNat.instLE y x) := @MyNat.le_total
#print axioms MyNat.le_total
end
