-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: 26292f1c5bb15cb74b36fd17875ce3a87f90f0f9c54af1ffbc1be55be99d9fc3
-- Preserve these theorem statements when completing the exercise.

-- MyNat.le_two
section
set_option autoImplicit true in
example : ∀ (x : MyNat),
  @LE.le.{0} MyNat MyNat.instLE x (@OfNat.ofNat.{0} MyNat (nat_lit 2) (@MyNat.instOfNat (nat_lit 2))) →
    Or (@Eq.{1} MyNat x (@OfNat.ofNat.{0} MyNat (nat_lit 0) (@MyNat.instOfNat (nat_lit 0))))
      (Or (@Eq.{1} MyNat x (@OfNat.ofNat.{0} MyNat (nat_lit 1) (@MyNat.instOfNat (nat_lit 1))))
        (@Eq.{1} MyNat x (@OfNat.ofNat.{0} MyNat (nat_lit 2) (@MyNat.instOfNat (nat_lit 2))))) := @MyNat.le_two
#print axioms MyNat.le_two
end
