-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: 5f448fa830fca199e390aaaca6c004774ab6c84a379994f846594a401b91c2e5
-- Preserve these theorem statements when completing the exercise.

-- MyNat.le_total
section
set_option autoImplicit true in
example : ∀ (x y : MyNat), Or (@LE.le.{0} MyNat MyNat.instLE x y) (@LE.le.{0} MyNat MyNat.instLE y x) := @MyNat.le_total
#print axioms MyNat.le_total
end
