-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: e549e62c537ff6efe4da7ddd77ae83952d8bc027eca4b194114319d00c34e7a7
-- Preserve these theorem statements when completing the exercise.

-- MyNat.le_trans
section
set_option autoImplicit true in
example : ∀ (x y z : MyNat),
  @LE.le.{0} MyNat MyNat.instLE x y → @LE.le.{0} MyNat MyNat.instLE y z → @LE.le.{0} MyNat MyNat.instLE x z := @MyNat.le_trans
#print axioms MyNat.le_trans
end
