-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: 0a57868ab30261d80ab90f848d45add0c2222bce6c63dc3f74de47f087b8f759
-- Preserve these theorem statements when completing the exercise.

-- MyNat.le_zero
section
set_option autoImplicit true in
example : ∀ (x : MyNat),
  @LE.le.{0} MyNat MyNat.instLE x (@OfNat.ofNat.{0} MyNat (nat_lit 0) (@MyNat.instOfNat (nat_lit 0))) →
    @Eq.{1} MyNat x (@OfNat.ofNat.{0} MyNat (nat_lit 0) (@MyNat.instOfNat (nat_lit 0))) := @MyNat.le_zero
#print axioms MyNat.le_zero
end
