-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: 362066d1977434915a6aa26bace4ba4f0b40a6597c578260afdbd6272822ec71
-- Preserve these theorem statements when completing the exercise.

-- MyNat.le_zero
section
set_option autoImplicit true in
example : ∀ (x : MyNat),
  @LE.le.{0} MyNat MyNat.instLE x (@OfNat.ofNat.{0} MyNat (nat_lit 0) (@MyNat.instOfNat (nat_lit 0))) →
    @Eq.{1} MyNat x (@OfNat.ofNat.{0} MyNat (nat_lit 0) (@MyNat.instOfNat (nat_lit 0))) := @MyNat.le_zero
#print axioms MyNat.le_zero
end
