-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: 7f3c1842d9681cff42b4a5cd5a06b198380818be9bb98ae6d48589e76653e842
-- Preserve these theorem statements when completing the exercise.

-- MyNat.exercise_lessorequal_or_symm
section
set_option autoImplicit true in
example : ∀ (x y : MyNat),
  Or (@Eq.{1} MyNat x (@OfNat.ofNat.{0} MyNat (nat_lit 37) (@MyNat.instOfNat (nat_lit 37))))
      (@Eq.{1} MyNat y (@OfNat.ofNat.{0} MyNat (nat_lit 42) (@MyNat.instOfNat (nat_lit 42)))) →
    Or (@Eq.{1} MyNat y (@OfNat.ofNat.{0} MyNat (nat_lit 42) (@MyNat.instOfNat (nat_lit 42))))
      (@Eq.{1} MyNat x (@OfNat.ofNat.{0} MyNat (nat_lit 37) (@MyNat.instOfNat (nat_lit 37)))) := @MyNat.exercise_lessorequal_or_symm
#print axioms MyNat.exercise_lessorequal_or_symm
end
