-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: 3957ef7be50c141573112c4212d01cbffcd13898bdddf3c9c31074010a75eafc
-- Preserve these theorem statements when completing the exercise.

-- MyNat.succ_le_succ
section
set_option autoImplicit true in
example : ∀ (x y : MyNat), @LE.le.{0} MyNat MyNat.instLE (MyNat.succ x) (MyNat.succ y) → @LE.le.{0} MyNat MyNat.instLE x y := @MyNat.succ_le_succ
#print axioms MyNat.succ_le_succ
end
