-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: 18551411aebb60348e653c3f4b643bf364e458e7a6b0a4b99c514ca2e143485e
-- Preserve these theorem statements when completing the exercise.

-- MyNat.succ_le_succ
section
set_option autoImplicit true in
example : ∀ (x y : MyNat), @LE.le.{0} MyNat MyNat.instLE (MyNat.succ x) (MyNat.succ y) → @LE.le.{0} MyNat MyNat.instLE x y := @MyNat.succ_le_succ
#print axioms MyNat.succ_le_succ
end
