-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: 79d65797742b65a57e53042fc8dc65f358b9ecfbf6a9901670c55e413837071b
-- Preserve these theorem statements when completing the exercise.

-- MyNat.zero_le
section
set_option autoImplicit true in
example : ∀ (x : MyNat), @LE.le.{0} MyNat MyNat.instLE (@OfNat.ofNat.{0} MyNat (nat_lit 0) (@MyNat.instOfNat (nat_lit 0))) x := @MyNat.zero_le
#print axioms MyNat.zero_le
end
