-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: 489eb027edef016e1fa5f40bca7f9426741a41cd2ed23f6c7fc4ffc8576b825e
-- Preserve these theorem statements when completing the exercise.

-- MyNat.zero_le
section
set_option autoImplicit true in
example : ∀ (x : MyNat), @LE.le.{0} MyNat MyNat.instLE (@OfNat.ofNat.{0} MyNat (nat_lit 0) (@MyNat.instOfNat (nat_lit 0))) x := @MyNat.zero_le
#print axioms MyNat.zero_le
end
