-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: f4d47154bf3277c0402a45d0ce07ed6fbbe5366f8492cfd002ac6911b7ebcae2
-- Preserve these theorem statements when completing the exercise.

-- MyNat.add_left_eq_zero
section
set_option autoImplicit true in
example : ∀ (a b : MyNat),
  @Eq.{1} MyNat (@HAdd.hAdd.{0, 0, 0} MyNat MyNat MyNat (@instHAdd.{0} MyNat MyNat.instAdd) a b)
      (@OfNat.ofNat.{0} MyNat (nat_lit 0) (@MyNat.instOfNat (nat_lit 0))) →
    @Eq.{1} MyNat b (@OfNat.ofNat.{0} MyNat (nat_lit 0) (@MyNat.instOfNat (nat_lit 0))) := @MyNat.add_left_eq_zero
#print axioms MyNat.add_left_eq_zero
end
