-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: e71eb1a1b2ad5572e5a9352fe3d8449e2b60d9b7e4a2fd49e4b0f0481d1e1ed2
-- Preserve these theorem statements when completing the exercise.

-- MyNat.add_right_eq_zero
section
set_option autoImplicit true in
example : ∀ (a b : MyNat),
  @Eq.{1} MyNat (@HAdd.hAdd.{0, 0, 0} MyNat MyNat MyNat (@instHAdd.{0} MyNat MyNat.instAdd) a b)
      (@OfNat.ofNat.{0} MyNat (nat_lit 0) (@MyNat.instOfNat (nat_lit 0))) →
    @Eq.{1} MyNat a (@OfNat.ofNat.{0} MyNat (nat_lit 0) (@MyNat.instOfNat (nat_lit 0))) := @MyNat.add_right_eq_zero
#print axioms MyNat.add_right_eq_zero
end
