-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: 0f5af18f0bcbbb8e56bf20c49f439f874f2ce91d2fbe427b0bade9125d5bf359
-- Preserve these theorem statements when completing the exercise.

-- MyNat.add_right_eq_zero
section
set_option autoImplicit true in
example : ∀ (a b : MyNat),
  @Eq.{1} MyNat (@HAdd.hAdd.{0, 0, 0} MyNat MyNat MyNat (@instHAdd.{0} MyNat MyNat.instAdd) a b)
      (@OfNat.ofNat.{0} MyNat (nat_lit 0) (@MyNat.instOfNat (nat_lit 0))) →
    @Eq.{1} MyNat a (@OfNat.ofNat.{0} MyNat (nat_lit 0) (@MyNat.instOfNat (nat_lit 0))) := @MyNat.add_right_eq_zero
#print axioms MyNat.add_right_eq_zero
end
