-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: 68e124228d12e7ee138d9ff883abcf6908a7c25e07162327f6ac26d8e20fc8a2
-- Preserve these theorem statements when completing the exercise.

-- MyNat.add_right_cancel
section
set_option autoImplicit true in
example : ∀ (a b n : MyNat),
  @Eq.{1} MyNat (@HAdd.hAdd.{0, 0, 0} MyNat MyNat MyNat (@instHAdd.{0} MyNat MyNat.instAdd) a n)
      (@HAdd.hAdd.{0, 0, 0} MyNat MyNat MyNat (@instHAdd.{0} MyNat MyNat.instAdd) b n) →
    @Eq.{1} MyNat a b := @MyNat.add_right_cancel
#print axioms MyNat.add_right_cancel
end
