-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: 5838045dee61c71aa055346aba1c3edb539d286583a50061df9a3ed96decc572
-- Preserve these theorem statements when completing the exercise.

-- MyNat.add_left_cancel
section
set_option autoImplicit true in
example : ∀ (a b n : MyNat),
  @Eq.{1} MyNat (@HAdd.hAdd.{0, 0, 0} MyNat MyNat MyNat (@instHAdd.{0} MyNat MyNat.instAdd) n a)
      (@HAdd.hAdd.{0, 0, 0} MyNat MyNat MyNat (@instHAdd.{0} MyNat MyNat.instAdd) n b) →
    @Eq.{1} MyNat a b := @MyNat.add_left_cancel
#print axioms MyNat.add_left_cancel
end
