-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: 80a82f2f52bac37d411746414606f65d42f350ce93f49f825e9bc6dcc5bf69b2
-- Preserve these theorem statements when completing the exercise.

-- MyNat.add_right_cancel
section
set_option autoImplicit true in
example : ∀ (a b n : MyNat),
  @Eq.{1} MyNat (@HAdd.hAdd.{0, 0, 0} MyNat MyNat MyNat (@instHAdd.{0} MyNat MyNat.instAdd) a n)
      (@HAdd.hAdd.{0, 0, 0} MyNat MyNat MyNat (@instHAdd.{0} MyNat MyNat.instAdd) b n) →
    @Eq.{1} MyNat a b := @MyNat.add_right_cancel
#print axioms MyNat.add_right_cancel
end
