-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: 26a51326b93ee42ac68b84deb79a55da2562e4d5add05db616fd24a4408b404b
-- Preserve these theorem statements when completing the exercise.

-- MyNat.add_right_eq_self
section
set_option autoImplicit true in
example : ∀ (x y : MyNat),
  @Eq.{1} MyNat (@HAdd.hAdd.{0, 0, 0} MyNat MyNat MyNat (@instHAdd.{0} MyNat MyNat.instAdd) x y) x →
    @Eq.{1} MyNat y (@OfNat.ofNat.{0} MyNat (nat_lit 0) (@MyNat.instOfNat (nat_lit 0))) := @MyNat.add_right_eq_self
#print axioms MyNat.add_right_eq_self
end
