-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: 3c206f31dfe0ca51c5d33418c6df85d43682bfb2b62d8752d60b4e70087c9090
-- Preserve these theorem statements when completing the exercise.

-- MyNat.add_left_eq_self
section
set_option autoImplicit true in
example : ∀ (x y : MyNat),
  @Eq.{1} MyNat (@HAdd.hAdd.{0, 0, 0} MyNat MyNat MyNat (@instHAdd.{0} MyNat MyNat.instAdd) x y) y →
    @Eq.{1} MyNat x (@OfNat.ofNat.{0} MyNat (nat_lit 0) (@MyNat.instOfNat (nat_lit 0))) := @MyNat.add_left_eq_self
#print axioms MyNat.add_left_eq_self
end
