-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: d2f417ae4009d0ddc21f1784deb4a22320b6155355e57b7768af98873f615b66
-- Preserve these theorem statements when completing the exercise.

-- MyNat.add_left_eq_self
section
set_option autoImplicit true in
example : ∀ (x y : MyNat),
  @Eq.{1} MyNat (@HAdd.hAdd.{0, 0, 0} MyNat MyNat MyNat (@instHAdd.{0} MyNat MyNat.instAdd) x y) y →
    @Eq.{1} MyNat x (@OfNat.ofNat.{0} MyNat (nat_lit 0) (@MyNat.instOfNat (nat_lit 0))) := @MyNat.add_left_eq_self
#print axioms MyNat.add_left_eq_self
end
