-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: 5dedcd90238f84e6a34171d5201a5401940891d72b8659a8579521c1de04e0f0
-- Preserve these theorem statements when completing the exercise.

-- Algebra.mul_rotate
section
set_option autoImplicit true in
example : ∀ {R : Type u_1} [inst : Algebra.CommRing.{u_1} R] (a b c : R),
  @Eq.{u_1 + 1} R
    (@HMul.hMul.{u_1, u_1, u_1} R R R
      (@instHMul.{u_1} R
        (@Algebra.Magma.toMul.{u_1} R
          (@Algebra.Semigroup.toMagma.{u_1} R
            (@Algebra.Monoid.toSemigroup.{u_1} R
              (@Algebra.Ring.toMonoid.{u_1} R (@Algebra.CommRing.toRing.{u_1} R inst))))))
      (@HMul.hMul.{u_1, u_1, u_1} R R R
        (@instHMul.{u_1} R
          (@Algebra.Magma.toMul.{u_1} R
            (@Algebra.Semigroup.toMagma.{u_1} R
              (@Algebra.Monoid.toSemigroup.{u_1} R
                (@Algebra.Ring.toMonoid.{u_1} R (@Algebra.CommRing.toRing.{u_1} R inst))))))
        a b)
      c)
    (@HMul.hMul.{u_1, u_1, u_1} R R R
      (@instHMul.{u_1} R
        (@Algebra.Magma.toMul.{u_1} R
          (@Algebra.Semigroup.toMagma.{u_1} R
            (@Algebra.Monoid.toSemigroup.{u_1} R
              (@Algebra.Ring.toMonoid.{u_1} R (@Algebra.CommRing.toRing.{u_1} R inst))))))
      (@HMul.hMul.{u_1, u_1, u_1} R R R
        (@instHMul.{u_1} R
          (@Algebra.Magma.toMul.{u_1} R
            (@Algebra.Semigroup.toMagma.{u_1} R
              (@Algebra.Monoid.toSemigroup.{u_1} R
                (@Algebra.Ring.toMonoid.{u_1} R (@Algebra.CommRing.toRing.{u_1} R inst))))))
        b c)
      a) := @Algebra.mul_rotate
#print axioms Algebra.mul_rotate
end
