-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: 8a261fa055b770b090fc20624fdcaf7f24ad06a4011012ebc1acca70c498183f
-- Preserve these theorem statements when completing the exercise.

-- Algebra.sq_expand
section
set_option autoImplicit true in
example : ∀ {R : Type u_1} [inst : Algebra.CommRing.{u_1} R] (a b : R),
  @Eq.{u_1 + 1} R
    (@HMul.hMul.{u_1, u_1, u_1} R R R
      (@instHMul.{u_1} R
        (@Algebra.Magma.toMul.{u_1} R
          (@Algebra.Semigroup.toMagma.{u_1} R
            (@Algebra.Monoid.toSemigroup.{u_1} R
              (@Algebra.Ring.toMonoid.{u_1} R (@Algebra.CommRing.toRing.{u_1} R inst))))))
      (@HAdd.hAdd.{u_1, u_1, u_1} R R R
        (@instHAdd.{u_1} R (@Algebra.Ring.toAdd.{u_1} R (@Algebra.CommRing.toRing.{u_1} R inst))) a b)
      (@HAdd.hAdd.{u_1, u_1, u_1} R R R
        (@instHAdd.{u_1} R (@Algebra.Ring.toAdd.{u_1} R (@Algebra.CommRing.toRing.{u_1} R inst))) a b))
    (@HAdd.hAdd.{u_1, u_1, u_1} R R R
      (@instHAdd.{u_1} R (@Algebra.Ring.toAdd.{u_1} R (@Algebra.CommRing.toRing.{u_1} R inst)))
      (@HAdd.hAdd.{u_1, u_1, u_1} R R R
        (@instHAdd.{u_1} R (@Algebra.Ring.toAdd.{u_1} R (@Algebra.CommRing.toRing.{u_1} R inst)))
        (@HMul.hMul.{u_1, u_1, u_1} R R R
          (@instHMul.{u_1} R
            (@Algebra.Magma.toMul.{u_1} R
              (@Algebra.Semigroup.toMagma.{u_1} R
                (@Algebra.Monoid.toSemigroup.{u_1} R
                  (@Algebra.Ring.toMonoid.{u_1} R (@Algebra.CommRing.toRing.{u_1} R inst))))))
          a a)
        (@HMul.hMul.{u_1, u_1, u_1} R R R
          (@instHMul.{u_1} R
            (@Algebra.Magma.toMul.{u_1} R
              (@Algebra.Semigroup.toMagma.{u_1} R
                (@Algebra.Monoid.toSemigroup.{u_1} R
                  (@Algebra.Ring.toMonoid.{u_1} R (@Algebra.CommRing.toRing.{u_1} R inst))))))
          a b))
      (@HAdd.hAdd.{u_1, u_1, u_1} R R R
        (@instHAdd.{u_1} R (@Algebra.Ring.toAdd.{u_1} R (@Algebra.CommRing.toRing.{u_1} R inst)))
        (@HMul.hMul.{u_1, u_1, u_1} R R R
          (@instHMul.{u_1} R
            (@Algebra.Magma.toMul.{u_1} R
              (@Algebra.Semigroup.toMagma.{u_1} R
                (@Algebra.Monoid.toSemigroup.{u_1} R
                  (@Algebra.Ring.toMonoid.{u_1} R (@Algebra.CommRing.toRing.{u_1} R inst))))))
          a b)
        (@HMul.hMul.{u_1, u_1, u_1} R R R
          (@instHMul.{u_1} R
            (@Algebra.Magma.toMul.{u_1} R
              (@Algebra.Semigroup.toMagma.{u_1} R
                (@Algebra.Monoid.toSemigroup.{u_1} R
                  (@Algebra.Ring.toMonoid.{u_1} R (@Algebra.CommRing.toRing.{u_1} R inst))))))
          b b))) := @Algebra.sq_expand
#print axioms Algebra.sq_expand
end
