-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: bbfc65257a9ff54d24a4822872c77a1de0373ff8082226cf21c1fceb063ae70f
-- Preserve these theorem statements when completing the exercise.

-- and_comm'
section
set_option autoImplicit true in
example : ∀ (P Q : Prop), And P Q → And Q P := @and_comm'
#print axioms and_comm'
end

-- and_or_left'
section
set_option autoImplicit true in
example : ∀ (P Q R : Prop), And P (Or Q R) → Or (And P Q) (And P R) := @and_or_left'
#print axioms and_or_left'
end

-- or_comm'
section
set_option autoImplicit true in
example : ∀ (P Q : Prop), Or P Q → Or Q P := @or_comm'
#print axioms or_comm'
end
