-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: 7a718c9f79028a0fbfc6143623792464ed6d51b816594f8c3c4f5b5b71219a40
-- Preserve these theorem statements when completing the exercise.

-- bool_and_comm
section
set_option autoImplicit true in
example : ∀ (a b : Bool), @Eq.{1} Bool (a.and b) (b.and a) := @bool_and_comm
#print axioms bool_and_comm
end

-- zero_or_pos
section
set_option autoImplicit true in
example : ∀ (n : Nat),
  Or (@Eq.{1} Nat n (@OfNat.ofNat.{0} Nat (nat_lit 0) (instOfNatNat (nat_lit 0))))
    (@GT.gt.{0} Nat instLTNat n (@OfNat.ofNat.{0} Nat (nat_lit 0) (instOfNatNat (nat_lit 0)))) := @zero_or_pos
#print axioms zero_or_pos
end
