-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: 97cbf5ba4fce37794c53a4268496faf7f3c4f9cc919491a1158b466aac3d7212
-- Preserve these theorem statements when completing the exercise.

-- chain
section
set_option autoImplicit true in
example : ∀ (P Q R : Prop), (P → Q) → (Q → R) → P → R := @chain
#print axioms chain
end

-- double_neg_intro
section
set_option autoImplicit true in
example : ∀ (P : Prop), P → Not (Not P) := @double_neg_intro
#print axioms double_neg_intro
end
