-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: 31244683397d07eacd95e5d417dc18d3fe89e29e466f7c81eded661530ec0bc1
-- Preserve these theorem statements when completing the exercise.

-- Analysis.add_isCauchy
section
set_option autoImplicit true in
example : ∀ {f g : Nat → Analysis.MyRat},
  Analysis.IsCauchy f →
    Analysis.IsCauchy g →
      Analysis.IsCauchy fun n =>
        @HAdd.hAdd.{0, 0, 0} Analysis.MyRat Analysis.MyRat Analysis.MyRat
          (@instHAdd.{0} Analysis.MyRat Analysis.MyRat.instAdd) (f n) (g n) := @Analysis.add_isCauchy
#print axioms Analysis.add_isCauchy
end
