-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: 61327c966342f7ccb4a998d7d9774c50b639153fbefb92d4b42fdd576e6c0e9f
-- Preserve these theorem statements when completing the exercise.

-- Analysis.const_isCauchy
section
set_option autoImplicit true in
example : ∀ (q : Analysis.MyRat), Analysis.IsCauchy (Analysis.constSeq q) := @Analysis.const_isCauchy
#print axioms Analysis.const_isCauchy
end
