-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: c6e618ad7b54ce5abc78ecbc589a2686fdf800a675440840cb9d6a787c401af3
-- Preserve these theorem statements when completing the exercise.

-- Analysis.equiv_trans
section
set_option autoImplicit true in
example : ∀ {f g h : Nat → Analysis.MyRat}, Analysis.CauchyEquiv f g → Analysis.CauchyEquiv g h → Analysis.CauchyEquiv f h := @Analysis.equiv_trans
#print axioms Analysis.equiv_trans
end
