-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: d03a63e4f3929cad273790b77cd7badd06976d405d743f5849ae3d33c1fe9bf6
-- Preserve these theorem statements when completing the exercise.

-- Analysis.equiv_symm
section
set_option autoImplicit true in
example : ∀ {f g : Nat → Analysis.MyRat}, Analysis.CauchyEquiv f g → Analysis.CauchyEquiv g f := @Analysis.equiv_symm
#print axioms Analysis.equiv_symm
end
