-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: 37ad752a65006059a6b5a01b85dcbfecbeef6e0e838662d1eda12d46237a530b
-- Preserve these theorem statements when completing the exercise.

-- Analysis.equiv_refl
section
set_option autoImplicit true in
example : ∀ (f : Nat → Analysis.MyRat), Analysis.CauchyEquiv f f := @Analysis.equiv_refl
#print axioms Analysis.equiv_refl
end
