-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: 23818b19a1531ac53944bd6a24a982c6e3877756884bb2a5965dc3d2d93c54d7
-- Preserve these theorem statements when completing the exercise.

-- Analysis.neg_isCauchy
section
set_option autoImplicit true in
example : ∀ {f : Nat → Analysis.MyRat},
  Analysis.IsCauchy f → Analysis.IsCauchy fun n => @Neg.neg.{0} Analysis.MyRat Analysis.MyRat.instNeg (f n) := @Analysis.neg_isCauchy
#print axioms Analysis.neg_isCauchy
end
