-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: b023d413958c9ec72d897ac371e2110dc30ac588a3ab0633029938849b4422cc
-- Preserve these theorem statements when completing the exercise.

-- Algebra.assoc_symm
section
set_option autoImplicit true in
example : ∀ {α : Type u_1} [inst : Algebra.Semigroup.{u_1} α] (a b c : α),
  @Eq.{u_1 + 1} α
    (@HMul.hMul.{u_1, u_1, u_1} α α α
      (@instHMul.{u_1} α (@Algebra.Magma.toMul.{u_1} α (@Algebra.Semigroup.toMagma.{u_1} α inst))) a
      (@HMul.hMul.{u_1, u_1, u_1} α α α
        (@instHMul.{u_1} α (@Algebra.Magma.toMul.{u_1} α (@Algebra.Semigroup.toMagma.{u_1} α inst))) b c))
    (@HMul.hMul.{u_1, u_1, u_1} α α α
      (@instHMul.{u_1} α (@Algebra.Magma.toMul.{u_1} α (@Algebra.Semigroup.toMagma.{u_1} α inst)))
      (@HMul.hMul.{u_1, u_1, u_1} α α α
        (@instHMul.{u_1} α (@Algebra.Magma.toMul.{u_1} α (@Algebra.Semigroup.toMagma.{u_1} α inst))) a b)
      c) := @Algebra.assoc_symm
#print axioms Algebra.assoc_symm
end
