-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: 3f5b5c113528f23de290a665f13dfd03abd3b2f30e472a0dcf6544d42508fc5f
-- Preserve these theorem statements when completing the exercise.

-- Algebra.reassoc_mixed
section
set_option autoImplicit true in
example : ∀ {α : Type u_1} [inst : Algebra.Semigroup.{u_1} α] (a b c d : α),
  @Eq.{u_1 + 1} α
    (@HMul.hMul.{u_1, u_1, u_1} α α α
      (@instHMul.{u_1} α (@Algebra.Magma.toMul.{u_1} α (@Algebra.Semigroup.toMagma.{u_1} α inst)))
      (@HMul.hMul.{u_1, u_1, u_1} α α α
        (@instHMul.{u_1} α (@Algebra.Magma.toMul.{u_1} α (@Algebra.Semigroup.toMagma.{u_1} α inst))) a
        (@HMul.hMul.{u_1, u_1, u_1} α α α
          (@instHMul.{u_1} α (@Algebra.Magma.toMul.{u_1} α (@Algebra.Semigroup.toMagma.{u_1} α inst))) b c))
      d)
    (@HMul.hMul.{u_1, u_1, u_1} α α α
      (@instHMul.{u_1} α (@Algebra.Magma.toMul.{u_1} α (@Algebra.Semigroup.toMagma.{u_1} α inst))) a
      (@HMul.hMul.{u_1, u_1, u_1} α α α
        (@instHMul.{u_1} α (@Algebra.Magma.toMul.{u_1} α (@Algebra.Semigroup.toMagma.{u_1} α inst))) b
        (@HMul.hMul.{u_1, u_1, u_1} α α α
          (@instHMul.{u_1} α (@Algebra.Magma.toMul.{u_1} α (@Algebra.Semigroup.toMagma.{u_1} α inst))) c d))) := @Algebra.reassoc_mixed
#print axioms Algebra.reassoc_mixed
end
