-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: 54780b40cf1c4cc605e81172174a232edea0a6cb2266ddd5c2e6805a24a8672a
-- Preserve these theorem statements when completing the exercise.

-- Algebra.reassoc5
section
set_option autoImplicit true in
example : ∀ {α : Type u_1} [inst : Algebra.Semigroup.{u_1} α] (a b c d e : α),
  @Eq.{u_1 + 1} α
    (@HMul.hMul.{u_1, u_1, u_1} α α α
      (@instHMul.{u_1} α (@Algebra.Magma.toMul.{u_1} α (@Algebra.Semigroup.toMagma.{u_1} α inst)))
      (@HMul.hMul.{u_1, u_1, u_1} α α α
        (@instHMul.{u_1} α (@Algebra.Magma.toMul.{u_1} α (@Algebra.Semigroup.toMagma.{u_1} α inst)))
        (@HMul.hMul.{u_1, u_1, u_1} α α α
          (@instHMul.{u_1} α (@Algebra.Magma.toMul.{u_1} α (@Algebra.Semigroup.toMagma.{u_1} α inst)))
          (@HMul.hMul.{u_1, u_1, u_1} α α α
            (@instHMul.{u_1} α (@Algebra.Magma.toMul.{u_1} α (@Algebra.Semigroup.toMagma.{u_1} α inst))) a b)
          c)
        d)
      e)
    (@HMul.hMul.{u_1, u_1, u_1} α α α
      (@instHMul.{u_1} α (@Algebra.Magma.toMul.{u_1} α (@Algebra.Semigroup.toMagma.{u_1} α inst))) a
      (@HMul.hMul.{u_1, u_1, u_1} α α α
        (@instHMul.{u_1} α (@Algebra.Magma.toMul.{u_1} α (@Algebra.Semigroup.toMagma.{u_1} α inst))) b
        (@HMul.hMul.{u_1, u_1, u_1} α α α
          (@instHMul.{u_1} α (@Algebra.Magma.toMul.{u_1} α (@Algebra.Semigroup.toMagma.{u_1} α inst))) c
          (@HMul.hMul.{u_1, u_1, u_1} α α α
            (@instHMul.{u_1} α (@Algebra.Magma.toMul.{u_1} α (@Algebra.Semigroup.toMagma.{u_1} α inst))) d e)))) := @Algebra.reassoc5
#print axioms Algebra.reassoc5
end
