-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: 170faa2a2df61744ceb183acf96651532a8184845311631a4b65dd50858bc97a
-- Preserve these theorem statements when completing the exercise.

-- Algebra.reassoc_back
section
set_option autoImplicit true in
example : ∀ {α : Type u_1} [inst : Algebra.Semigroup.{u_1} α] (a b c d : α),
  @Eq.{u_1 + 1} α
    (@HMul.hMul.{u_1, u_1, u_1} α α α
      (@instHMul.{u_1} α (@Algebra.Magma.toMul.{u_1} α (@Algebra.Semigroup.toMagma.{u_1} α inst))) a
      (@HMul.hMul.{u_1, u_1, u_1} α α α
        (@instHMul.{u_1} α (@Algebra.Magma.toMul.{u_1} α (@Algebra.Semigroup.toMagma.{u_1} α inst))) b
        (@HMul.hMul.{u_1, u_1, u_1} α α α
          (@instHMul.{u_1} α (@Algebra.Magma.toMul.{u_1} α (@Algebra.Semigroup.toMagma.{u_1} α inst))) c d)))
    (@HMul.hMul.{u_1, u_1, u_1} α α α
      (@instHMul.{u_1} α (@Algebra.Magma.toMul.{u_1} α (@Algebra.Semigroup.toMagma.{u_1} α inst)))
      (@HMul.hMul.{u_1, u_1, u_1} α α α
        (@instHMul.{u_1} α (@Algebra.Magma.toMul.{u_1} α (@Algebra.Semigroup.toMagma.{u_1} α inst)))
        (@HMul.hMul.{u_1, u_1, u_1} α α α
          (@instHMul.{u_1} α (@Algebra.Magma.toMul.{u_1} α (@Algebra.Semigroup.toMagma.{u_1} α inst))) a b)
        c)
      d) := @Algebra.reassoc_back
#print axioms Algebra.reassoc_back
end
