-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: bca9c7b2cf09830c92fc6b1b5bd966ccec555db6c2ee8c66280902b82abc0e5d
-- Preserve these theorem statements when completing the exercise.

-- Algebra.reassoc
section
set_option autoImplicit true in
example : ∀ {α : Type u_1} [inst : Algebra.Semigroup.{u_1} α] (a b c d : α),
  @Eq.{u_1 + 1} α
    (@HMul.hMul.{u_1, u_1, u_1} α α α
      (@instHMul.{u_1} α (@Algebra.Magma.toMul.{u_1} α (@Algebra.Semigroup.toMagma.{u_1} α inst)))
      (@HMul.hMul.{u_1, u_1, u_1} α α α
        (@instHMul.{u_1} α (@Algebra.Magma.toMul.{u_1} α (@Algebra.Semigroup.toMagma.{u_1} α inst)))
        (@HMul.hMul.{u_1, u_1, u_1} α α α
          (@instHMul.{u_1} α (@Algebra.Magma.toMul.{u_1} α (@Algebra.Semigroup.toMagma.{u_1} α inst))) a b)
        c)
      d)
    (@HMul.hMul.{u_1, u_1, u_1} α α α
      (@instHMul.{u_1} α (@Algebra.Magma.toMul.{u_1} α (@Algebra.Semigroup.toMagma.{u_1} α inst))) a
      (@HMul.hMul.{u_1, u_1, u_1} α α α
        (@instHMul.{u_1} α (@Algebra.Magma.toMul.{u_1} α (@Algebra.Semigroup.toMagma.{u_1} α inst))) b
        (@HMul.hMul.{u_1, u_1, u_1} α α α
          (@instHMul.{u_1} α (@Algebra.Magma.toMul.{u_1} α (@Algebra.Semigroup.toMagma.{u_1} α inst))) c d))) := @Algebra.reassoc
#print axioms Algebra.reassoc
end
