-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: ce5d8ec8ba1f71e29404ab22ca6891f825fdf4bea9591ca59d063a898f682fd2
-- Preserve these theorem statements when completing the exercise.

-- Analysis.MyReal.mul_inv_cancel
section
set_option autoImplicit true in
example : ∀ (x : Analysis.MyReal),
  @Ne.{1} Analysis.MyReal x
      (@OfNat.ofNat.{0} Analysis.MyReal (nat_lit 0) (@Zero.toOfNat0.{0} Analysis.MyReal Analysis.MyReal.instZero)) →
    @Eq.{1} Analysis.MyReal
      (@HMul.hMul.{0, 0, 0} Analysis.MyReal Analysis.MyReal Analysis.MyReal
        (@instHMul.{0} Analysis.MyReal Analysis.MyReal.instMul) x
        (@Inv.inv.{0} Analysis.MyReal Analysis.MyReal.instInv x))
      (@OfNat.ofNat.{0} Analysis.MyReal (nat_lit 1) (@One.toOfNat1.{0} Analysis.MyReal Analysis.MyReal.instOne)) := @Analysis.MyReal.mul_inv_cancel
#print axioms Analysis.MyReal.mul_inv_cancel
end
