-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: 27257a696dbe3701f546403cbe1151bbedee8745fec554d5cb674e9679abe3f7
-- Preserve these theorem statements when completing the exercise.

-- Algebra.div_one
section
set_option autoImplicit true in
example : ∀ {G : Type u_1} [inst : Algebra.Group.{u_1} G] (a : G),
  @Eq.{u_1 + 1} G
    (@HDiv.hDiv.{u_1, u_1, u_1} G G G (@instHDiv.{u_1} G (@Algebra.instGroupDiv.{u_1} G inst)) a
      (@OfNat.ofNat.{u_1} G (nat_lit 1)
        (@One.toOfNat1.{u_1} G (@Algebra.Monoid.toOne.{u_1} G (@Algebra.Group.toMonoid.{u_1} G inst)))))
    a := @Algebra.div_one
#print axioms Algebra.div_one
end
