-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: b6c0774772e1b3b7821959741f40aba37f1f623190963a05d423cb43d9cf1f94
-- Preserve these theorem statements when completing the exercise.

-- Algebra.div_mul_cancel
section
set_option autoImplicit true in
example : ∀ {G : Type u_1} [inst : Algebra.Group.{u_1} G] (a b : G),
  @Eq.{u_1 + 1} G
    (@HMul.hMul.{u_1, u_1, u_1} G G G
      (@instHMul.{u_1} G
        (@Algebra.Magma.toMul.{u_1} G
          (@Algebra.Semigroup.toMagma.{u_1} G
            (@Algebra.Monoid.toSemigroup.{u_1} G (@Algebra.Group.toMonoid.{u_1} G inst)))))
      (@HDiv.hDiv.{u_1, u_1, u_1} G G G (@instHDiv.{u_1} G (@Algebra.instGroupDiv.{u_1} G inst)) a b) b)
    a := @Algebra.div_mul_cancel
#print axioms Algebra.div_mul_cancel
end
