-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: b55b989ee95218d2972679d0e1eb527dafc518925b26e0962d8ec0564f4eeace
-- Preserve these theorem statements when completing the exercise.

-- Algebra.div_self
section
set_option autoImplicit true in
example : ∀ {G : Type u_1} [inst : Algebra.Group.{u_1} G] (a : G),
  @Eq.{u_1 + 1} G (@HDiv.hDiv.{u_1, u_1, u_1} G G G (@instHDiv.{u_1} G (@Algebra.instGroupDiv.{u_1} G inst)) a a)
    (@OfNat.ofNat.{u_1} G (nat_lit 1)
      (@One.toOfNat1.{u_1} G (@Algebra.Monoid.toOne.{u_1} G (@Algebra.Group.toMonoid.{u_1} G inst)))) := @Algebra.div_self
#print axioms Algebra.div_self
end
