-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: d73cf848817015cbc89df93fabb47f11ade21ace9b42b3b4dca2a823b19e9e79
-- Preserve these theorem statements when completing the exercise.

-- Algebra.mul_div_cancel
section
set_option autoImplicit true in
example : ∀ {G : Type u_1} [inst : Algebra.Group.{u_1} G] (a b : G),
  @Eq.{u_1 + 1} G
    (@HDiv.hDiv.{u_1, u_1, u_1} G G G (@instHDiv.{u_1} G (@Algebra.instGroupDiv.{u_1} G inst))
      (@HMul.hMul.{u_1, u_1, u_1} G G G
        (@instHMul.{u_1} G
          (@Algebra.Magma.toMul.{u_1} G
            (@Algebra.Semigroup.toMagma.{u_1} G
              (@Algebra.Monoid.toSemigroup.{u_1} G (@Algebra.Group.toMonoid.{u_1} G inst)))))
        a b)
      b)
    a := @Algebra.mul_div_cancel
#print axioms Algebra.mul_div_cancel
end
