-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: 366adf99dace6378ed2b68dc261d8f4da5add068c35f90d54cb1601417ab011a
-- Preserve these theorem statements when completing the exercise.

-- Algebra.one_div
section
set_option autoImplicit true in
example : ∀ {G : Type u_1} [inst : Algebra.Group.{u_1} G] (a : G),
  @Eq.{u_1 + 1} G
    (@HDiv.hDiv.{u_1, u_1, u_1} G G G (@instHDiv.{u_1} G (@Algebra.instGroupDiv.{u_1} G inst))
      (@OfNat.ofNat.{u_1} G (nat_lit 1)
        (@One.toOfNat1.{u_1} G (@Algebra.Monoid.toOne.{u_1} G (@Algebra.Group.toMonoid.{u_1} G inst))))
      a)
    (@Inv.inv.{u_1} G (@Algebra.Group.toInv.{u_1} G inst) a) := @Algebra.one_div
#print axioms Algebra.one_div
end
