-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: 649cc09e6cee62139aca902a5465b255b256d70de7c67ab019eaa433530e9405
-- Preserve these theorem statements when completing the exercise.

-- Algebra.field_mul_left_cancel
section
set_option autoImplicit true in
example : ∀ {F : Type u_1} [inst : Algebra.Field.{u_1} F] (a b c : F),
  @Ne.{u_1 + 1} F a
      (@OfNat.ofNat.{u_1} F (nat_lit 0)
        (@Zero.toOfNat0.{u_1} F
          (@Algebra.Ring.toZero.{u_1} F (@Algebra.CommRing.toRing.{u_1} F (@Algebra.Field.toCommRing.{u_1} F inst))))) →
    @Eq.{u_1 + 1} F
        (@HMul.hMul.{u_1, u_1, u_1} F F F
          (@instHMul.{u_1} F
            (@Algebra.Magma.toMul.{u_1} F
              (@Algebra.Semigroup.toMagma.{u_1} F
                (@Algebra.Monoid.toSemigroup.{u_1} F
                  (@Algebra.Ring.toMonoid.{u_1} F
                    (@Algebra.CommRing.toRing.{u_1} F (@Algebra.Field.toCommRing.{u_1} F inst)))))))
          a b)
        (@HMul.hMul.{u_1, u_1, u_1} F F F
          (@instHMul.{u_1} F
            (@Algebra.Magma.toMul.{u_1} F
              (@Algebra.Semigroup.toMagma.{u_1} F
                (@Algebra.Monoid.toSemigroup.{u_1} F
                  (@Algebra.Ring.toMonoid.{u_1} F
                    (@Algebra.CommRing.toRing.{u_1} F (@Algebra.Field.toCommRing.{u_1} F inst)))))))
          a c) →
      @Eq.{u_1 + 1} F b c := @Algebra.field_mul_left_cancel
#print axioms Algebra.field_mul_left_cancel
end
