-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: a6e077a693de594ca1d9fadd8851b12d5e0e100963ef39e502cd2db720f5cfe1
-- Preserve these theorem statements when completing the exercise.

-- Algebra.field_inv_one
section
set_option autoImplicit true in
example : ∀ {F : Type u_1} [inst : Algebra.Field.{u_1} F],
  @Eq.{u_1 + 1} F
    (@Inv.inv.{u_1} F (@Algebra.Field.toInv.{u_1} F inst)
      (@OfNat.ofNat.{u_1} F (nat_lit 1)
        (@One.toOfNat1.{u_1} F
          (@Algebra.Monoid.toOne.{u_1} F
            (@Algebra.Ring.toMonoid.{u_1} F
              (@Algebra.CommRing.toRing.{u_1} F (@Algebra.Field.toCommRing.{u_1} F inst)))))))
    (@OfNat.ofNat.{u_1} F (nat_lit 1)
      (@One.toOfNat1.{u_1} F
        (@Algebra.Monoid.toOne.{u_1} F
          (@Algebra.Ring.toMonoid.{u_1} F
            (@Algebra.CommRing.toRing.{u_1} F (@Algebra.Field.toCommRing.{u_1} F inst)))))) := @Algebra.field_inv_one
#print axioms Algebra.field_inv_one
end
