-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: 24101560907b6c26595a67d72b43aa95e91e587ad856f95921120737cece93b0
-- Preserve these theorem statements when completing the exercise.

-- Algebra.inv_ne_zero
section
set_option autoImplicit true in
example : ∀ {F : Type u_1} [inst : Algebra.Field.{u_1} F] (a : F),
  @Ne.{u_1 + 1} F a
      (@OfNat.ofNat.{u_1} F (nat_lit 0)
        (@Zero.toOfNat0.{u_1} F
          (@Algebra.Ring.toZero.{u_1} F (@Algebra.CommRing.toRing.{u_1} F (@Algebra.Field.toCommRing.{u_1} F inst))))) →
    @Ne.{u_1 + 1} F (@Inv.inv.{u_1} F (@Algebra.Field.toInv.{u_1} F inst) a)
      (@OfNat.ofNat.{u_1} F (nat_lit 0)
        (@Zero.toOfNat0.{u_1} F
          (@Algebra.Ring.toZero.{u_1} F (@Algebra.CommRing.toRing.{u_1} F (@Algebra.Field.toCommRing.{u_1} F inst))))) := @Algebra.inv_ne_zero
#print axioms Algebra.inv_ne_zero
end
