-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: 91ec838f7303971c2b3fb646753315582e32d9f518f00d8e2334935d6498f776
-- Preserve these theorem statements when completing the exercise.

-- Algebra.mul_ne_zero
section
set_option autoImplicit true in
example : ∀ {F : Type u_1} [inst : Algebra.Field.{u_1} F] (a b : F),
  @Ne.{u_1 + 1} F a
      (@OfNat.ofNat.{u_1} F (nat_lit 0)
        (@Zero.toOfNat0.{u_1} F
          (@Algebra.Ring.toZero.{u_1} F (@Algebra.CommRing.toRing.{u_1} F (@Algebra.Field.toCommRing.{u_1} F inst))))) →
    @Ne.{u_1 + 1} F b
        (@OfNat.ofNat.{u_1} F (nat_lit 0)
          (@Zero.toOfNat0.{u_1} F
            (@Algebra.Ring.toZero.{u_1} F
              (@Algebra.CommRing.toRing.{u_1} F (@Algebra.Field.toCommRing.{u_1} F inst))))) →
      @Ne.{u_1 + 1} F
        (@HMul.hMul.{u_1, u_1, u_1} F F F
          (@instHMul.{u_1} F
            (@Algebra.Magma.toMul.{u_1} F
              (@Algebra.Semigroup.toMagma.{u_1} F
                (@Algebra.Monoid.toSemigroup.{u_1} F
                  (@Algebra.Ring.toMonoid.{u_1} F
                    (@Algebra.CommRing.toRing.{u_1} F (@Algebra.Field.toCommRing.{u_1} F inst)))))))
          a b)
        (@OfNat.ofNat.{u_1} F (nat_lit 0)
          (@Zero.toOfNat0.{u_1} F
            (@Algebra.Ring.toZero.{u_1} F (@Algebra.CommRing.toRing.{u_1} F (@Algebra.Field.toCommRing.{u_1} F inst))))) := @Algebra.mul_ne_zero
#print axioms Algebra.mul_ne_zero
end
