-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: 4a57bad353aa910c6f6e35b197242130fb5a3434bf5aaef4447644382536c666
-- Preserve these theorem statements when completing the exercise.

-- Algebra.mul_self_eq_zero
section
set_option autoImplicit true in
example : ∀ {F : Type u_1} [inst : Algebra.Field.{u_1} F] (a : F),
  @Eq.{u_1 + 1} F
      (@HMul.hMul.{u_1, u_1, u_1} F F F
        (@instHMul.{u_1} F
          (@Algebra.Magma.toMul.{u_1} F
            (@Algebra.Semigroup.toMagma.{u_1} F
              (@Algebra.Monoid.toSemigroup.{u_1} F
                (@Algebra.Ring.toMonoid.{u_1} F
                  (@Algebra.CommRing.toRing.{u_1} F (@Algebra.Field.toCommRing.{u_1} F inst)))))))
        a a)
      (@OfNat.ofNat.{u_1} F (nat_lit 0)
        (@Zero.toOfNat0.{u_1} F
          (@Algebra.Ring.toZero.{u_1} F (@Algebra.CommRing.toRing.{u_1} F (@Algebra.Field.toCommRing.{u_1} F inst))))) →
    @Eq.{u_1 + 1} F a
      (@OfNat.ofNat.{u_1} F (nat_lit 0)
        (@Zero.toOfNat0.{u_1} F
          (@Algebra.Ring.toZero.{u_1} F (@Algebra.CommRing.toRing.{u_1} F (@Algebra.Field.toCommRing.{u_1} F inst))))) := @Algebra.mul_self_eq_zero
#print axioms Algebra.mul_self_eq_zero
end
