-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: 821f34ed001b5cc6c35305a6eb9a880b4ed733da7f28472f4774964849a71de8
-- Preserve these theorem statements when completing the exercise.

-- Algebra.mul_eq_zero
section
set_option autoImplicit true in
example : ∀ {F : Type u_1} [inst : Algebra.Field.{u_1} F] (a b : F),
  @Eq.{u_1 + 1} F
      (@HMul.hMul.{u_1, u_1, u_1} F F F
        (@instHMul.{u_1} F
          (@Algebra.Magma.toMul.{u_1} F
            (@Algebra.Semigroup.toMagma.{u_1} F
              (@Algebra.Monoid.toSemigroup.{u_1} F
                (@Algebra.Ring.toMonoid.{u_1} F
                  (@Algebra.CommRing.toRing.{u_1} F (@Algebra.Field.toCommRing.{u_1} F inst)))))))
        a b)
      (@OfNat.ofNat.{u_1} F (nat_lit 0)
        (@Zero.toOfNat0.{u_1} F
          (@Algebra.Ring.toZero.{u_1} F (@Algebra.CommRing.toRing.{u_1} F (@Algebra.Field.toCommRing.{u_1} F inst))))) →
    Or
      (@Eq.{u_1 + 1} F a
        (@OfNat.ofNat.{u_1} F (nat_lit 0)
          (@Zero.toOfNat0.{u_1} F
            (@Algebra.Ring.toZero.{u_1} F
              (@Algebra.CommRing.toRing.{u_1} F (@Algebra.Field.toCommRing.{u_1} F inst))))))
      (@Eq.{u_1 + 1} F b
        (@OfNat.ofNat.{u_1} F (nat_lit 0)
          (@Zero.toOfNat0.{u_1} F
            (@Algebra.Ring.toZero.{u_1} F
              (@Algebra.CommRing.toRing.{u_1} F (@Algebra.Field.toCommRing.{u_1} F inst)))))) := @Algebra.mul_eq_zero
#print axioms Algebra.mul_eq_zero
end
