-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: e967394cff784b2801e746b945996366a30e5df37d270760e18678a0d307d191
-- Preserve these theorem statements when completing the exercise.

-- Algebra.mul_inv_cancel
section
set_option autoImplicit true in
example : ∀ {F : Type u_1} [inst : Algebra.Field.{u_1} F] (a : F),
  @Ne.{u_1 + 1} F a
      (@OfNat.ofNat.{u_1} F (nat_lit 0)
        (@Zero.toOfNat0.{u_1} F
          (@Algebra.Ring.toZero.{u_1} F (@Algebra.CommRing.toRing.{u_1} F (@Algebra.Field.toCommRing.{u_1} F inst))))) →
    @Eq.{u_1 + 1} F
      (@HMul.hMul.{u_1, u_1, u_1} F F F
        (@instHMul.{u_1} F
          (@Algebra.Magma.toMul.{u_1} F
            (@Algebra.Semigroup.toMagma.{u_1} F
              (@Algebra.Monoid.toSemigroup.{u_1} F
                (@Algebra.Ring.toMonoid.{u_1} F
                  (@Algebra.CommRing.toRing.{u_1} F (@Algebra.Field.toCommRing.{u_1} F inst)))))))
        a (@Inv.inv.{u_1} F (@Algebra.Field.toInv.{u_1} F inst) a))
      (@OfNat.ofNat.{u_1} F (nat_lit 1)
        (@One.toOfNat1.{u_1} F
          (@Algebra.Monoid.toOne.{u_1} F
            (@Algebra.Ring.toMonoid.{u_1} F
              (@Algebra.CommRing.toRing.{u_1} F (@Algebra.Field.toCommRing.{u_1} F inst)))))) := @Algebra.mul_inv_cancel
#print axioms Algebra.mul_inv_cancel
end
