-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: 013e2ab966843f3c5fcdfe5ceefb60de8db508463b7dfe491f13e3dbaeeab7e8
-- Preserve these theorem statements when completing the exercise.

-- MyNat.exercise_implication_apply
section
set_option autoImplicit true in
example : ∀ (x y : MyNat),
  @Eq.{1} MyNat x (@OfNat.ofNat.{0} MyNat (nat_lit 37) (@MyNat.instOfNat (nat_lit 37))) →
    (@Eq.{1} MyNat x (@OfNat.ofNat.{0} MyNat (nat_lit 37) (@MyNat.instOfNat (nat_lit 37))) →
        @Eq.{1} MyNat y (@OfNat.ofNat.{0} MyNat (nat_lit 42) (@MyNat.instOfNat (nat_lit 42)))) →
      @Eq.{1} MyNat y (@OfNat.ofNat.{0} MyNat (nat_lit 42) (@MyNat.instOfNat (nat_lit 42))) := @MyNat.exercise_implication_apply
#print axioms MyNat.exercise_implication_apply
end
