-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: d49d8e50b3168acba635d7d954728683cdf142e290583421678c640d1c212a95
-- Preserve these theorem statements when completing the exercise.

-- MyNat.exercise_implication_exact
section
set_option autoImplicit true in
example : ∀ (x y z : MyNat),
  @Eq.{1} MyNat (@HAdd.hAdd.{0, 0, 0} MyNat MyNat MyNat (@instHAdd.{0} MyNat MyNat.instAdd) x y)
      (@OfNat.ofNat.{0} MyNat (nat_lit 37) (@MyNat.instOfNat (nat_lit 37))) →
    @Eq.{1} MyNat
        (@HAdd.hAdd.{0, 0, 0} MyNat MyNat MyNat (@instHAdd.{0} MyNat MyNat.instAdd)
          (@HMul.hMul.{0, 0, 0} MyNat MyNat MyNat (@instHMul.{0} MyNat MyNat.instMul)
            (@OfNat.ofNat.{0} MyNat (nat_lit 3) (@MyNat.instOfNat (nat_lit 3))) x)
          z)
        (@OfNat.ofNat.{0} MyNat (nat_lit 42) (@MyNat.instOfNat (nat_lit 42))) →
      @Eq.{1} MyNat (@HAdd.hAdd.{0, 0, 0} MyNat MyNat MyNat (@instHAdd.{0} MyNat MyNat.instAdd) x y)
        (@OfNat.ofNat.{0} MyNat (nat_lit 37) (@MyNat.instOfNat (nat_lit 37))) := @MyNat.exercise_implication_exact
#print axioms MyNat.exercise_implication_exact
end
