-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: 5a3df5c030e7f9677170926619e9529a9fc663446daf27547dbc96a3f0f76901
-- Preserve these theorem statements when completing the exercise.

-- MyNat.exercise_implication_exact2
section
set_option autoImplicit true in
example : ∀ (x y : MyNat),
  @Eq.{1} MyNat
      (@HAdd.hAdd.{0, 0, 0} MyNat MyNat MyNat (@instHAdd.{0} MyNat MyNat.instAdd)
        (@OfNat.ofNat.{0} MyNat (nat_lit 0) (@MyNat.instOfNat (nat_lit 0))) x)
      (@HAdd.hAdd.{0, 0, 0} MyNat MyNat MyNat (@instHAdd.{0} MyNat MyNat.instAdd)
        (@HAdd.hAdd.{0, 0, 0} MyNat MyNat MyNat (@instHAdd.{0} MyNat MyNat.instAdd)
          (@OfNat.ofNat.{0} MyNat (nat_lit 0) (@MyNat.instOfNat (nat_lit 0))) y)
        (@OfNat.ofNat.{0} MyNat (nat_lit 2) (@MyNat.instOfNat (nat_lit 2)))) →
    @Eq.{1} MyNat x
      (@HAdd.hAdd.{0, 0, 0} MyNat MyNat MyNat (@instHAdd.{0} MyNat MyNat.instAdd) y
        (@OfNat.ofNat.{0} MyNat (nat_lit 2) (@MyNat.instOfNat (nat_lit 2)))) := @MyNat.exercise_implication_exact2
#print axioms MyNat.exercise_implication_exact2
end
