-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: 8d6edc8f95a3a0155039f338fffec2fcf9c38761125cac40ab27336d5a3837b9
-- Preserve these theorem statements when completing the exercise.

-- MyNat.exercise_implication_intro2
section
set_option autoImplicit true in
example : ∀ (x y : MyNat),
  @Eq.{1} MyNat
      (@HAdd.hAdd.{0, 0, 0} MyNat MyNat MyNat (@instHAdd.{0} MyNat MyNat.instAdd) x
        (@OfNat.ofNat.{0} MyNat (nat_lit 1) (@MyNat.instOfNat (nat_lit 1))))
      (@HAdd.hAdd.{0, 0, 0} MyNat MyNat MyNat (@instHAdd.{0} MyNat MyNat.instAdd) y
        (@OfNat.ofNat.{0} MyNat (nat_lit 1) (@MyNat.instOfNat (nat_lit 1)))) →
    @Eq.{1} MyNat x y := @MyNat.exercise_implication_intro2
#print axioms MyNat.exercise_implication_intro2
end
