-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: 1df7f897e9ec0b28c1725e3b413842bc5883a83c02af6359fc45eb215bd99133
-- Preserve these theorem statements when completing the exercise.

-- MyNat.exercise_implication_intro2
section
set_option autoImplicit true in
example : ∀ (x y : MyNat),
  @Eq.{1} MyNat
      (@HAdd.hAdd.{0, 0, 0} MyNat MyNat MyNat (@instHAdd.{0} MyNat MyNat.instAdd) x
        (@OfNat.ofNat.{0} MyNat (nat_lit 1) (@MyNat.instOfNat (nat_lit 1))))
      (@HAdd.hAdd.{0, 0, 0} MyNat MyNat MyNat (@instHAdd.{0} MyNat MyNat.instAdd) y
        (@OfNat.ofNat.{0} MyNat (nat_lit 1) (@MyNat.instOfNat (nat_lit 1)))) →
    @Eq.{1} MyNat x y := @MyNat.exercise_implication_intro2
#print axioms MyNat.exercise_implication_intro2
end
