-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: 0454efa17e7ad2b5c1165b273de2e806d0b3e31ed83e15c0611247aea8fbade9
-- Preserve these theorem statements when completing the exercise.

-- MyNat.exercise_implication_intro
section
set_option autoImplicit true in
example : ∀ (x : MyNat),
  @Eq.{1} MyNat x (@OfNat.ofNat.{0} MyNat (nat_lit 37) (@MyNat.instOfNat (nat_lit 37))) →
    @Eq.{1} MyNat x (@OfNat.ofNat.{0} MyNat (nat_lit 37) (@MyNat.instOfNat (nat_lit 37))) := @MyNat.exercise_implication_intro
#print axioms MyNat.exercise_implication_intro
end
