-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: 3b49df28e5048b578948ff8e27245389a9b6c28ff76c0450311bbed0f81907d4
-- Preserve these theorem statements when completing the exercise.

-- MyNat.exercise_implication_ne
section
set_option autoImplicit true in
example : ∀ (x y : MyNat), @Eq.{1} MyNat x y → @Ne.{1} MyNat x y → False := @MyNat.exercise_implication_ne
#print axioms MyNat.exercise_implication_ne
end
