-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: ac21999e5d1acf1c3d67a47e9bf7630dc1eab766bd7e2e9bfad0648886d4d5a0
-- Preserve these theorem statements when completing the exercise.

-- MyNat.exercise_implication_ne
section
set_option autoImplicit true in
example : ∀ (x y : MyNat), @Eq.{1} MyNat x y → @Ne.{1} MyNat x y → False := @MyNat.exercise_implication_ne
#print axioms MyNat.exercise_implication_ne
end
