-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: 914e8d4393fe2d2e5fb7aa4a5b330c7fd4f978d744d0450c20296439574a8a81
-- Preserve these theorem statements when completing the exercise.

-- MyNat.one_ne_zero
section
set_option autoImplicit true in
example : @Ne.{1} MyNat (@OfNat.ofNat.{0} MyNat (nat_lit 1) (@MyNat.instOfNat (nat_lit 1)))
  (@OfNat.ofNat.{0} MyNat (nat_lit 0) (@MyNat.instOfNat (nat_lit 0))) := @MyNat.one_ne_zero
#print axioms MyNat.one_ne_zero
end
