-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: 9ac6784879f09c5bc2ab1a26e41e87d0a01b34ffd806a1e6623441e83d8a84dc
-- Preserve these theorem statements when completing the exercise.

-- MyNat.exercise_implication_succ_inj2
section
set_option autoImplicit true in
example : ∀ (x : MyNat),
  @Eq.{1} MyNat
      (@HAdd.hAdd.{0, 0, 0} MyNat MyNat MyNat (@instHAdd.{0} MyNat MyNat.instAdd) x
        (@OfNat.ofNat.{0} MyNat (nat_lit 1) (@MyNat.instOfNat (nat_lit 1))))
      (@OfNat.ofNat.{0} MyNat (nat_lit 4) (@MyNat.instOfNat (nat_lit 4))) →
    @Eq.{1} MyNat x (@OfNat.ofNat.{0} MyNat (nat_lit 3) (@MyNat.instOfNat (nat_lit 3))) := @MyNat.exercise_implication_succ_inj2
#print axioms MyNat.exercise_implication_succ_inj2
end
