-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: 71c6443ede57cb1d0e3294359f05450d3ca5b1d10cd7ed94b17172af91451506
-- Preserve these theorem statements when completing the exercise.

-- MyNat.exercise_implication_succ_inj
section
set_option autoImplicit true in
example : ∀ (x : MyNat),
  @Eq.{1} MyNat
      (@HAdd.hAdd.{0, 0, 0} MyNat MyNat MyNat (@instHAdd.{0} MyNat MyNat.instAdd) x
        (@OfNat.ofNat.{0} MyNat (nat_lit 1) (@MyNat.instOfNat (nat_lit 1))))
      (@OfNat.ofNat.{0} MyNat (nat_lit 4) (@MyNat.instOfNat (nat_lit 4))) →
    @Eq.{1} MyNat x (@OfNat.ofNat.{0} MyNat (nat_lit 3) (@MyNat.instOfNat (nat_lit 3))) := @MyNat.exercise_implication_succ_inj
#print axioms MyNat.exercise_implication_succ_inj
end
