-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: 827e95916c0eda8b6316bd3b0ebc03cb85c323280191eb5a3d83485a39982823
-- Preserve these theorem statements when completing the exercise.

-- MyNat.exercise_implication_succ_inj
section
set_option autoImplicit true in
example : ∀ (x : MyNat),
  @Eq.{1} MyNat
      (@HAdd.hAdd.{0, 0, 0} MyNat MyNat MyNat (@instHAdd.{0} MyNat MyNat.instAdd) x
        (@OfNat.ofNat.{0} MyNat (nat_lit 1) (@MyNat.instOfNat (nat_lit 1))))
      (@OfNat.ofNat.{0} MyNat (nat_lit 4) (@MyNat.instOfNat (nat_lit 4))) →
    @Eq.{1} MyNat x (@OfNat.ofNat.{0} MyNat (nat_lit 3) (@MyNat.instOfNat (nat_lit 3))) := @MyNat.exercise_implication_succ_inj
#print axioms MyNat.exercise_implication_succ_inj
end
