-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: 102c93f673ff299c44c05347183d71f886b4c86b31daf57da203f52326457bec
-- Preserve these theorem statements when completing the exercise.

-- MyNat.exercise_implication_two_add_two_ne_five
section
set_option autoImplicit true in
example : @Ne.{1} MyNat
  (@HAdd.hAdd.{0, 0, 0} MyNat MyNat MyNat (@instHAdd.{0} MyNat MyNat.instAdd)
    (MyNat.succ (MyNat.succ (@OfNat.ofNat.{0} MyNat (nat_lit 0) (@MyNat.instOfNat (nat_lit 0)))))
    (MyNat.succ (MyNat.succ (@OfNat.ofNat.{0} MyNat (nat_lit 0) (@MyNat.instOfNat (nat_lit 0))))))
  (MyNat.succ
    (MyNat.succ
      (MyNat.succ (MyNat.succ (MyNat.succ (@OfNat.ofNat.{0} MyNat (nat_lit 0) (@MyNat.instOfNat (nat_lit 0)))))))) := @MyNat.exercise_implication_two_add_two_ne_five
#print axioms MyNat.exercise_implication_two_add_two_ne_five
end
