-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: f7c93bb2390a9a78eaeea04b639a00123adc4a48c519a28c6a898f312b520474
-- Preserve these theorem statements when completing the exercise.

-- MyNat.exercise_implication_two_add_two_ne_five
section
set_option autoImplicit true in
example : @Ne.{1} MyNat
  (@HAdd.hAdd.{0, 0, 0} MyNat MyNat MyNat (@instHAdd.{0} MyNat MyNat.instAdd)
    (MyNat.succ (MyNat.succ (@OfNat.ofNat.{0} MyNat (nat_lit 0) (@MyNat.instOfNat (nat_lit 0)))))
    (MyNat.succ (MyNat.succ (@OfNat.ofNat.{0} MyNat (nat_lit 0) (@MyNat.instOfNat (nat_lit 0))))))
  (MyNat.succ
    (MyNat.succ
      (MyNat.succ (MyNat.succ (MyNat.succ (@OfNat.ofNat.{0} MyNat (nat_lit 0) (@MyNat.instOfNat (nat_lit 0)))))))) := @MyNat.exercise_implication_two_add_two_ne_five
#print axioms MyNat.exercise_implication_two_add_two_ne_five
end
