-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: 0fb977523c85b6a551ce15e835deb9be585f8669c38bb8030d2bb10655254d53
-- Preserve these theorem statements when completing the exercise.

-- MyNat.zero_ne_one
section
set_option autoImplicit true in
example : @Ne.{1} MyNat (@OfNat.ofNat.{0} MyNat (nat_lit 0) (@MyNat.instOfNat (nat_lit 0)))
  (@OfNat.ofNat.{0} MyNat (nat_lit 1) (@MyNat.instOfNat (nat_lit 1))) := @MyNat.zero_ne_one
#print axioms MyNat.zero_ne_one
end
