-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: 08a126a75c53f67288e09f56e19c85323f44c6ece0670fadfb73c6e30cc3cdd7
-- Preserve these theorem statements when completing the exercise.

-- MyNat.zero_ne_one
section
set_option autoImplicit true in
example : @Ne.{1} MyNat (@OfNat.ofNat.{0} MyNat (nat_lit 0) (@MyNat.instOfNat (nat_lit 0)))
  (@OfNat.ofNat.{0} MyNat (nat_lit 1) (@MyNat.instOfNat (nat_lit 1))) := @MyNat.zero_ne_one
#print axioms MyNat.zero_ne_one
end
