-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: 361f2d6f8eb8b70f2fba33d4c52d3e66c6d91e029e37d931be7c45a11288274e
-- Preserve these theorem statements when completing the exercise.

-- Analysis.PreRat.add_resp
section
set_option autoImplicit true in
example : ∀ {a b c d : Analysis.PreRat}, a.r c → b.r d → (a.add b).r (c.add d) := @Analysis.PreRat.add_resp
#print axioms Analysis.PreRat.add_resp
end
