-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: 6f06071c6001b0da600c2f0b8635906fd94b6e80581f3c0a7eded83b215287f6
-- Preserve these theorem statements when completing the exercise.

-- Analysis.PreRat.le_imp
section
set_option autoImplicit true in
example : ∀ {a b c d : Analysis.PreRat}, a.r c → b.r d → a.leAux b → c.leAux d := @Analysis.PreRat.le_imp
#print axioms Analysis.PreRat.le_imp
end
