-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: 8f3f37e31e080762d12b94a105c407aeda176bb9a39a187d1df6505ceb0411a7
-- Preserve these theorem statements when completing the exercise.

-- Analysis.PreRat.lt_imp
section
set_option autoImplicit true in
example : ∀ {a b c d : Analysis.PreRat}, a.r c → b.r d → a.ltAux b → c.ltAux d := @Analysis.PreRat.lt_imp
#print axioms Analysis.PreRat.lt_imp
end
