-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: 4a430bf08694500775053937be5b86662d43b9acf0cf8712ff8d72c1504ce439
-- Preserve these theorem statements when completing the exercise.

-- Analysis.PreRat.mul_resp
section
set_option autoImplicit true in
example : ∀ {a b c d : Analysis.PreRat}, a.r c → b.r d → (a.mul b).r (c.mul d) := @Analysis.PreRat.mul_resp
#print axioms Analysis.PreRat.mul_resp
end
