-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: e7a64ae9b88144a6054b3bac4d1b74aafd3fcb90fd67d04452c3a7ccf24d7044
-- Preserve these theorem statements when completing the exercise.

-- Analysis.PreRat.neg_resp
section
set_option autoImplicit true in
example : ∀ {a b : Analysis.PreRat}, a.r b → a.neg.r b.neg := @Analysis.PreRat.neg_resp
#print axioms Analysis.PreRat.neg_resp
end
