-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: d93c3bdd35b679b32f92537d63c20bb7ccaa9fbca00f298cb9328734410ef3a6
-- Preserve these theorem statements when completing the exercise.

-- Algebra.bool_one
section
set_option autoImplicit true in
example : @Eq.{1} Bool
  (@OfNat.ofNat.{0} Bool (nat_lit 1)
    (@One.toOfNat1.{0} Bool
      (@Algebra.Monoid.toOne.{0} Bool (@Algebra.CommMonoid.toMonoid.{0} Bool Algebra.instCommMonoidBool))))
  Bool.true := @Algebra.bool_one
#print axioms Algebra.bool_one
end
