-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: 4802249a909d4d04791c8cbdb82d2ed399cb6a0b7683f8e5f95c6fa3b988b8e9
-- Preserve these theorem statements when completing the exercise.

-- Algebra.id_unique_right
section
set_option autoImplicit true in
example : ∀ {M : Type u_1} [inst : Algebra.Monoid.{u_1} M] (e : M),
  (∀ (a : M),
      @Eq.{u_1 + 1} M
        (@HMul.hMul.{u_1, u_1, u_1} M M M
          (@instHMul.{u_1} M
            (@Algebra.Magma.toMul.{u_1} M
              (@Algebra.Semigroup.toMagma.{u_1} M (@Algebra.Monoid.toSemigroup.{u_1} M inst))))
          a e)
        a) →
    @Eq.{u_1 + 1} M e (@OfNat.ofNat.{u_1} M (nat_lit 1) (@One.toOfNat1.{u_1} M (@Algebra.Monoid.toOne.{u_1} M inst))) := @Algebra.id_unique_right
#print axioms Algebra.id_unique_right
end
