-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: a5b4ea6e199749721821e298ae58eb8a72116bbc9af1d56d1ae825f88dd11e06
-- Preserve these theorem statements when completing the exercise.

-- Algebra.id_unique_left
section
set_option autoImplicit true in
example : ∀ {M : Type u_1} [inst : Algebra.Monoid.{u_1} M] (e : M),
  (∀ (a : M),
      @Eq.{u_1 + 1} M
        (@HMul.hMul.{u_1, u_1, u_1} M M M
          (@instHMul.{u_1} M
            (@Algebra.Magma.toMul.{u_1} M
              (@Algebra.Semigroup.toMagma.{u_1} M (@Algebra.Monoid.toSemigroup.{u_1} M inst))))
          e a)
        a) →
    @Eq.{u_1 + 1} M e (@OfNat.ofNat.{u_1} M (nat_lit 1) (@One.toOfNat1.{u_1} M (@Algebra.Monoid.toOne.{u_1} M inst))) := @Algebra.id_unique_left
#print axioms Algebra.id_unique_left
end
