-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: cd069d7edf3310a19e2130d4691f5d482452bb274ab48319870c188844287ba4
-- Preserve these theorem statements when completing the exercise.

-- Algebra.one_idempotent
section
set_option autoImplicit true in
example : ∀ {M : Type u_1} [inst : Algebra.Monoid.{u_1} M],
  @Eq.{u_1 + 1} M
    (@HMul.hMul.{u_1, u_1, u_1} M M M
      (@instHMul.{u_1} M
        (@Algebra.Magma.toMul.{u_1} M (@Algebra.Semigroup.toMagma.{u_1} M (@Algebra.Monoid.toSemigroup.{u_1} M inst))))
      (@OfNat.ofNat.{u_1} M (nat_lit 1) (@One.toOfNat1.{u_1} M (@Algebra.Monoid.toOne.{u_1} M inst)))
      (@OfNat.ofNat.{u_1} M (nat_lit 1) (@One.toOfNat1.{u_1} M (@Algebra.Monoid.toOne.{u_1} M inst))))
    (@OfNat.ofNat.{u_1} M (nat_lit 1) (@One.toOfNat1.{u_1} M (@Algebra.Monoid.toOne.{u_1} M inst))) := @Algebra.one_idempotent
#print axioms Algebra.one_idempotent
end
