-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: 5a91de14b92b9a786e056bb82abf6a192fea72ddbac00037c4c838f023f65e8e
-- Preserve these theorem statements when completing the exercise.

-- Analysis.PreRat.r_refl
section
set_option autoImplicit true in
example : ∀ (a : Analysis.PreRat), a.r a := @Analysis.PreRat.r_refl
#print axioms Analysis.PreRat.r_refl
end
