-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: 25918b528a949c126db0fd3f1961744a4eb86c0e003fea57fa641208c9477650
-- Preserve these theorem statements when completing the exercise.

-- Analysis.PreRat.r_symm
section
set_option autoImplicit true in
example : ∀ {a b : Analysis.PreRat}, a.r b → b.r a := @Analysis.PreRat.r_symm
#print axioms Analysis.PreRat.r_symm
end
