-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: 21e11ce6c50dbcc3753d86ff21da905925b120ff88b5277f3750fc573e85f74e
-- Preserve these theorem statements when completing the exercise.

-- Analysis.PreRat.r_symm
section
set_option autoImplicit true in
example : ∀ {a b : Analysis.PreRat}, a.r b → b.r a := @Analysis.PreRat.r_symm
#print axioms Analysis.PreRat.r_symm
end
