-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: c07aa01a7709ed84af288f2d15c3b159c397476281959be4170d019f1ac6d9db
-- Preserve these theorem statements when completing the exercise.

-- Analysis.PreRat.r_trans
section
set_option autoImplicit true in
example : ∀ {a b c : Analysis.PreRat}, a.r b → b.r c → a.r c := @Analysis.PreRat.r_trans
#print axioms Analysis.PreRat.r_trans
end
