-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: b7a1207970e7534262dad7fd277be2b7d490916109d1b5924b8e91de707f6554
-- Preserve these theorem statements when completing the exercise.

-- calc_mixed
section
set_option autoImplicit true in
example : ∀ (a b c : Nat), @Eq.{1} Nat a b → @LE.le.{0} Nat instLENat b c → @LE.le.{0} Nat instLENat a c := @calc_mixed
#print axioms calc_mixed
end

-- calc_three
section
set_option autoImplicit true in
example : ∀ (f : Nat → Nat),
  @LE.le.{0} Nat instLENat (f (@OfNat.ofNat.{0} Nat (nat_lit 0) (instOfNatNat (nat_lit 0))))
      (f (@OfNat.ofNat.{0} Nat (nat_lit 1) (instOfNatNat (nat_lit 1)))) →
    @LE.le.{0} Nat instLENat (f (@OfNat.ofNat.{0} Nat (nat_lit 1) (instOfNatNat (nat_lit 1))))
        (f (@OfNat.ofNat.{0} Nat (nat_lit 2) (instOfNatNat (nat_lit 2)))) →
      @LE.le.{0} Nat instLENat (f (@OfNat.ofNat.{0} Nat (nat_lit 2) (instOfNatNat (nat_lit 2))))
          (@OfNat.ofNat.{0} Nat (nat_lit 100) (instOfNatNat (nat_lit 100))) →
        @LE.le.{0} Nat instLENat (f (@OfNat.ofNat.{0} Nat (nat_lit 0) (instOfNatNat (nat_lit 0))))
          (@OfNat.ofNat.{0} Nat (nat_lit 100) (instOfNatNat (nat_lit 100))) := @calc_three
#print axioms calc_three
end

-- calc_trans
section
set_option autoImplicit true in
example : ∀ (f : Nat → Nat),
  @LE.le.{0} Nat instLENat (f (@OfNat.ofNat.{0} Nat (nat_lit 0) (instOfNatNat (nat_lit 0))))
      (f (@OfNat.ofNat.{0} Nat (nat_lit 1) (instOfNatNat (nat_lit 1)))) →
    @LE.le.{0} Nat instLENat (f (@OfNat.ofNat.{0} Nat (nat_lit 1) (instOfNatNat (nat_lit 1))))
        (f (@OfNat.ofNat.{0} Nat (nat_lit 2) (instOfNatNat (nat_lit 2)))) →
      @LE.le.{0} Nat instLENat (f (@OfNat.ofNat.{0} Nat (nat_lit 0) (instOfNatNat (nat_lit 0))))
        (f (@OfNat.ofNat.{0} Nat (nat_lit 2) (instOfNatNat (nat_lit 2)))) := @calc_trans
#print axioms calc_trans
end
