-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: 35c8a1b22c37620cd8ae4b6e2373800360894f2ae06fc35c0ece39bd7351c03c
-- Preserve these theorem statements when completing the exercise.

-- calc_chain
section
set_option autoImplicit true in
example : ∀ (f g : Nat → Nat),
  (∀ (x : Nat),
      @Eq.{1} Nat (f x)
        (@HAdd.hAdd.{0, 0, 0} Nat Nat Nat (@instHAdd.{0} Nat instAddNat) (g x)
          (@OfNat.ofNat.{0} Nat (nat_lit 1) (instOfNatNat (nat_lit 1))))) →
    (∀ (x : Nat),
        @Eq.{1} Nat (g x)
          (@HMul.hMul.{0, 0, 0} Nat Nat Nat (@instHMul.{0} Nat instMulNat) x
            (@OfNat.ofNat.{0} Nat (nat_lit 2) (instOfNatNat (nat_lit 2))))) →
      @Eq.{1} Nat (f (@OfNat.ofNat.{0} Nat (nat_lit 5) (instOfNatNat (nat_lit 5))))
        (@OfNat.ofNat.{0} Nat (nat_lit 11) (instOfNatNat (nat_lit 11))) := @calc_chain
#print axioms calc_chain
end

-- calc_rewrite
section
set_option autoImplicit true in
example : ∀ (f : Nat → Nat),
  @Eq.{1} Nat (f (@OfNat.ofNat.{0} Nat (nat_lit 0) (instOfNatNat (nat_lit 0))))
      (@OfNat.ofNat.{0} Nat (nat_lit 3) (instOfNatNat (nat_lit 3))) →
    @Eq.{1} Nat (f (@OfNat.ofNat.{0} Nat (nat_lit 3) (instOfNatNat (nat_lit 3))))
        (@OfNat.ofNat.{0} Nat (nat_lit 7) (instOfNatNat (nat_lit 7))) →
      @Eq.{1} Nat (f (f (@OfNat.ofNat.{0} Nat (nat_lit 0) (instOfNatNat (nat_lit 0)))))
        (@OfNat.ofNat.{0} Nat (nat_lit 7) (instOfNatNat (nat_lit 7))) := @calc_rewrite
#print axioms calc_rewrite
end
