-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: e06a68fa44eb91ca027ceae19b4e09fc070d5e22bda984c67e30e313f7c70a78
-- Preserve these theorem statements when completing the exercise.

-- Analysis.MyReal.cauchy_seq_converges
section
set_option autoImplicit true in
example : ∀ (f : Nat → Analysis.MyRat) (hf : Analysis.IsCauchy f),
  Analysis.MyReal.Tendsto (fun k => Analysis.MyReal.ofRat (f k)) (Analysis.MyReal.mk f hf) := @Analysis.MyReal.cauchy_seq_converges
#print axioms Analysis.MyReal.cauchy_seq_converges
end
