-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: 6fb3e8e710c921cfd312f512cf7a25c098c370779a236dfe7ea166e336490342
-- Preserve these theorem statements when completing the exercise.

-- Analysis.MyReal.ofRat_pos
section
set_option autoImplicit true in
example : ∀ {q : Analysis.MyRat},
  @LT.lt.{0} Analysis.MyRat Analysis.MyRat.instLT
      (@OfNat.ofNat.{0} Analysis.MyRat (nat_lit 0) (@Zero.toOfNat0.{0} Analysis.MyRat Analysis.MyRat.instZero)) q →
    @LT.lt.{0} Analysis.MyReal Analysis.MyReal.instLT
      (@OfNat.ofNat.{0} Analysis.MyReal (nat_lit 0) (@Zero.toOfNat0.{0} Analysis.MyReal Analysis.MyReal.instZero))
      (Analysis.MyReal.ofRat q) := @Analysis.MyReal.ofRat_pos
#print axioms Analysis.MyReal.ofRat_pos
end
