#!/usr/bin/env python3
"""Generate exact theorem-type checks from compiled reference solutions.

Run `lake build` and `lake build Leanlings.Contracts` first. --check compares
without modifying files. Only trusted reference solutions are compiled here.
"""
import argparse
from concurrent.futures import ThreadPoolExecutor
import hashlib
import json
from pathlib import Path
import subprocess
import tempfile

ROOT = Path(__file__).resolve().parents[1]
parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument('--check', action='store_true')
parser.add_argument('--course', choices=['intro', 'nng', 'algebra', 'analysis'])
args = parser.parse_args()
courses = [ROOT / 'courses' / args.course] if args.course else sorted((ROOT / 'courses').iterdir())
exercises = [p for course in courses if course.is_dir() for p in sorted((course / 'exercises').rglob('*.lean'))]


def generate(exercise):
    course = next(p for p in exercise.parents if p.parent == ROOT / 'courses')
    rel = exercise.relative_to(course / 'exercises')
    reference = course / 'solutions' / rel
    target = course / 'contracts' / rel
    source = reference.read_text()
    with tempfile.TemporaryDirectory(prefix='leanlings-contracts-') as tmp:
        path = Path(tmp) / 'Reference.lean'
        path.write_text('import Leanlings.Contracts\n' + source + '\n#emit_leanlings_contracts\n')
        result = subprocess.run(['lake', 'env', 'lean', str(path)], cwd=ROOT,
                                capture_output=True, text=True, timeout=90)
    lines = [line.removeprefix('LEANLINGS_CONTRACTS ') for line in result.stdout.splitlines()
             if line.startswith('LEANLINGS_CONTRACTS ')]
    if result.returncode or len(lines) != 1 or 'declaration uses `sorry`' in result.stdout:
        raise RuntimeError(f'{reference.relative_to(ROOT)}: {result.stdout}{result.stderr}')
    contracts = sorted(json.loads(lines[0]), key=lambda item: item['name'])
    if contracts:
        checksum = hashlib.sha256(source.encode()).hexdigest()
        content = ('-- Generated by scripts/generate-contracts.py; do not edit by hand.\n'
                   f'-- Reference SHA-256: {checksum}\n'
                   '-- Preserve these theorem statements when completing the exercise.\n\n')
        content += '\n'.join(f'-- {item["name"]}\n{item["check"]}' for item in contracts)
    else:
        content = None
    existing = target.read_text() if target.exists() else None
    if args.check:
        if content != existing:
            raise RuntimeError(f'Stale or missing contract: {target.relative_to(ROOT)}')
    elif content is not None:
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(content)
    elif existing is not None:
        if not existing.startswith('-- Generated by scripts/generate-contracts.py; do not edit by hand.\n'):
            raise RuntimeError(f'Refusing to remove a hand-written contract: {target.relative_to(ROOT)}')
        target.unlink()
    return len(contracts)


with ThreadPoolExecutor(max_workers=4) as pool:
    counts = list(pool.map(generate, exercises))
print(f'{"Verified" if args.check else "Generated"} {sum(counts)} theorem contracts across {len(exercises)} exercises.')
