-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: 67aacc0504de873ffb011c5a8092f3bcee73e42cf58170a5d41ab28916a695bf
-- Preserve these theorem statements when completing the exercise.

-- append_assoc'
section
set_option autoImplicit true in
example : ∀ {α : Type u_1} (a b c : List.{u_1} α),
  @Eq.{u_1 + 1} (List.{u_1} α)
    (@HAppend.hAppend.{u_1, u_1, u_1} (List.{u_1} α) (List.{u_1} α) (List.{u_1} α)
      (@instHAppendOfAppend.{u_1} (List.{u_1} α) (@List.instAppend.{u_1} α))
      (@HAppend.hAppend.{u_1, u_1, u_1} (List.{u_1} α) (List.{u_1} α) (List.{u_1} α)
        (@instHAppendOfAppend.{u_1} (List.{u_1} α) (@List.instAppend.{u_1} α)) a b)
      c)
    (@HAppend.hAppend.{u_1, u_1, u_1} (List.{u_1} α) (List.{u_1} α) (List.{u_1} α)
      (@instHAppendOfAppend.{u_1} (List.{u_1} α) (@List.instAppend.{u_1} α)) a
      (@HAppend.hAppend.{u_1, u_1, u_1} (List.{u_1} α) (List.{u_1} α) (List.{u_1} α)
        (@instHAppendOfAppend.{u_1} (List.{u_1} α) (@List.instAppend.{u_1} α)) b c)) := @append_assoc'
#print axioms append_assoc'
end

-- append_nil'
section
set_option autoImplicit true in
example : ∀ {α : Type u_1} (l : List.{u_1} α),
  @Eq.{u_1 + 1} (List.{u_1} α)
    (@HAppend.hAppend.{u_1, u_1, u_1} (List.{u_1} α) (List.{u_1} α) (List.{u_1} α)
      (@instHAppendOfAppend.{u_1} (List.{u_1} α) (@List.instAppend.{u_1} α)) l (@List.nil.{u_1} α))
    l := @append_nil'
#print axioms append_nil'
end

-- length_append'
section
set_option autoImplicit true in
example : ∀ {α : Type u_1} (a b : List.{u_1} α),
  @Eq.{1} Nat
    (@List.length.{u_1} α
      (@HAppend.hAppend.{u_1, u_1, u_1} (List.{u_1} α) (List.{u_1} α) (List.{u_1} α)
        (@instHAppendOfAppend.{u_1} (List.{u_1} α) (@List.instAppend.{u_1} α)) a b))
    (@HAdd.hAdd.{0, 0, 0} Nat Nat Nat (@instHAdd.{0} Nat instAddNat) (@List.length.{u_1} α a) (@List.length.{u_1} α b)) := @length_append'
#print axioms length_append'
end
