-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: 97f08445a72d87ddc73c88afa77e60fc8f7f58035b33eebcfcba0e1f9d801770
-- Preserve these theorem statements when completing the exercise.

-- map_id'
section
set_option autoImplicit true in
example : ∀ {α : Type u_1} (l : List.{u_1} α), @Eq.{u_1 + 1} (List.{u_1} α) (@List.map.{u_1, u_1} α α (@id.{u_1 + 1} α) l) l := @map_id'
#print axioms map_id'
end

-- map_length
section
set_option autoImplicit true in
example : ∀ {α : Type u_1} {β : Type u_2} (f : α → β) (l : List.{u_1} α),
  @Eq.{1} Nat (@List.length.{u_2} β (@List.map.{u_1, u_2} α β f l)) (@List.length.{u_1} α l) := @map_length
#print axioms map_length
end

-- reverse_length
section
set_option autoImplicit true in
example : ∀ {α : Type u_1} (l : List.{u_1} α),
  @Eq.{1} Nat (@List.length.{u_1} α (@List.reverse.{u_1} α l)) (@List.length.{u_1} α l) := @reverse_length
#print axioms reverse_length
end
