-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: 13bd7d2101317b374dfaa37a3d5f134d53cf3be15273ae0732222840e968bd8c
-- Preserve these theorem statements when completing the exercise.

-- myAppend_assoc
section
set_option autoImplicit true in
example : ∀ {α : Type u_1} (a b c : List.{u_1} α),
  @Eq.{u_1 + 1} (List.{u_1} α) (@myAppend.{u_1} α (@myAppend.{u_1} α a b) c)
    (@myAppend.{u_1} α a (@myAppend.{u_1} α b c)) := @myAppend_assoc
#print axioms myAppend_assoc
end

-- myAppend_eq_append
section
set_option autoImplicit true in
example : ∀ {α : Type u_1} (a b : List.{u_1} α),
  @Eq.{u_1 + 1} (List.{u_1} α) (@myAppend.{u_1} α a b)
    (@HAppend.hAppend.{u_1, u_1, u_1} (List.{u_1} α) (List.{u_1} α) (List.{u_1} α)
      (@instHAppendOfAppend.{u_1} (List.{u_1} α) (@List.instAppend.{u_1} α)) a b) := @myAppend_eq_append
#print axioms myAppend_eq_append
end

-- myAppend_nil
section
set_option autoImplicit true in
example : ∀ {α : Type u_1} (l : List.{u_1} α), @Eq.{u_1 + 1} (List.{u_1} α) (@myAppend.{u_1} α l (@List.nil.{u_1} α)) l := @myAppend_nil
#print axioms myAppend_nil
end
