-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: dcdca22b4ec80aa79f8f5a0575a50e125aa82ffcfcb675c1c419c5cf66aa68de
-- Preserve these theorem statements when completing the exercise.

-- MyNat.mul_add
section
set_option autoImplicit true in
example : ∀ (a b c : MyNat),
  @Eq.{1} MyNat
    (@HMul.hMul.{0, 0, 0} MyNat MyNat MyNat (@instHMul.{0} MyNat MyNat.instMul) a
      (@HAdd.hAdd.{0, 0, 0} MyNat MyNat MyNat (@instHAdd.{0} MyNat MyNat.instAdd) b c))
    (@HAdd.hAdd.{0, 0, 0} MyNat MyNat MyNat (@instHAdd.{0} MyNat MyNat.instAdd)
      (@HMul.hMul.{0, 0, 0} MyNat MyNat MyNat (@instHMul.{0} MyNat MyNat.instMul) a b)
      (@HMul.hMul.{0, 0, 0} MyNat MyNat MyNat (@instHMul.{0} MyNat MyNat.instMul) a c)) := @MyNat.mul_add
#print axioms MyNat.mul_add
end
