-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: a942b66477152e8d2225ac1bb2f0d8b0108a962f760f7c163f5642aa224806c0
-- Preserve these theorem statements when completing the exercise.

-- MyNat.mul_comm
section
set_option autoImplicit true in
example : ∀ (a b : MyNat),
  @Eq.{1} MyNat (@HMul.hMul.{0, 0, 0} MyNat MyNat MyNat (@instHMul.{0} MyNat MyNat.instMul) a b)
    (@HMul.hMul.{0, 0, 0} MyNat MyNat MyNat (@instHMul.{0} MyNat MyNat.instMul) b a) := @MyNat.mul_comm
#print axioms MyNat.mul_comm
end
