-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: 72620450ea11db21d9ece202f56cff8b30673589c2637a9670b362c93025507a
-- Preserve these theorem statements when completing the exercise.

-- MyNat.mul_comm
section
set_option autoImplicit true in
example : ∀ (a b : MyNat),
  @Eq.{1} MyNat (@HMul.hMul.{0, 0, 0} MyNat MyNat MyNat (@instHMul.{0} MyNat MyNat.instMul) a b)
    (@HMul.hMul.{0, 0, 0} MyNat MyNat MyNat (@instHMul.{0} MyNat MyNat.instMul) b a) := @MyNat.mul_comm
#print axioms MyNat.mul_comm
end
