-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: 2b050fe99d996bad1ae117d60df289c33282f93be5512fa47923df065f5cd987
-- Preserve these theorem statements when completing the exercise.

-- MyNat.mul_add
section
set_option autoImplicit true in
example : ∀ (a b c : MyNat),
  @Eq.{1} MyNat
    (@HMul.hMul.{0, 0, 0} MyNat MyNat MyNat (@instHMul.{0} MyNat MyNat.instMul) a
      (@HAdd.hAdd.{0, 0, 0} MyNat MyNat MyNat (@instHAdd.{0} MyNat MyNat.instAdd) b c))
    (@HAdd.hAdd.{0, 0, 0} MyNat MyNat MyNat (@instHAdd.{0} MyNat MyNat.instAdd)
      (@HMul.hMul.{0, 0, 0} MyNat MyNat MyNat (@instHMul.{0} MyNat MyNat.instMul) a b)
      (@HMul.hMul.{0, 0, 0} MyNat MyNat MyNat (@instHMul.{0} MyNat MyNat.instMul) a c)) := @MyNat.mul_add
#print axioms MyNat.mul_add
end
