-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: 6f809b31ab98a819a8793780477a269e12a314cc49514165eb5d560c9a77447f
-- Preserve these theorem statements when completing the exercise.

-- MyNat.mul_assoc
section
set_option autoImplicit true in
example : ∀ (a b c : MyNat),
  @Eq.{1} MyNat
    (@HMul.hMul.{0, 0, 0} MyNat MyNat MyNat (@instHMul.{0} MyNat MyNat.instMul)
      (@HMul.hMul.{0, 0, 0} MyNat MyNat MyNat (@instHMul.{0} MyNat MyNat.instMul) a b) c)
    (@HMul.hMul.{0, 0, 0} MyNat MyNat MyNat (@instHMul.{0} MyNat MyNat.instMul) a
      (@HMul.hMul.{0, 0, 0} MyNat MyNat MyNat (@instHMul.{0} MyNat MyNat.instMul) b c)) := @MyNat.mul_assoc
#print axioms MyNat.mul_assoc
end
