-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: d69e43ee18844a1d53fd6b0fcf46bbdb2a7cdd5a72a2a9cf268912493090f192
-- Preserve these theorem statements when completing the exercise.

-- MyNat.mul_one
section
set_option autoImplicit true in
example : ∀ (m : MyNat),
  @Eq.{1} MyNat
    (@HMul.hMul.{0, 0, 0} MyNat MyNat MyNat (@instHMul.{0} MyNat MyNat.instMul) m
      (@OfNat.ofNat.{0} MyNat (nat_lit 1) (@MyNat.instOfNat (nat_lit 1))))
    m := @MyNat.mul_one
#print axioms MyNat.mul_one
end
