-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: fac39a23b9f2349811d17778a1421cc2f219154fa24a67851fe153083563c00a
-- Preserve these theorem statements when completing the exercise.

-- MyNat.one_mul
section
set_option autoImplicit true in
example : ∀ (m : MyNat),
  @Eq.{1} MyNat
    (@HMul.hMul.{0, 0, 0} MyNat MyNat MyNat (@instHMul.{0} MyNat MyNat.instMul)
      (@OfNat.ofNat.{0} MyNat (nat_lit 1) (@MyNat.instOfNat (nat_lit 1))) m)
    m := @MyNat.one_mul
#print axioms MyNat.one_mul
end
