-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: 83e15a3983fd11a0fbcb08c8da65fd7e17b5c3f17d437fdc839489590a6fdf0f
-- Preserve these theorem statements when completing the exercise.

-- MyNat.succ_mul
section
set_option autoImplicit true in
example : ∀ (a b : MyNat),
  @Eq.{1} MyNat (@HMul.hMul.{0, 0, 0} MyNat MyNat MyNat (@instHMul.{0} MyNat MyNat.instMul) (MyNat.succ a) b)
    (@HAdd.hAdd.{0, 0, 0} MyNat MyNat MyNat (@instHAdd.{0} MyNat MyNat.instAdd)
      (@HMul.hMul.{0, 0, 0} MyNat MyNat MyNat (@instHMul.{0} MyNat MyNat.instMul) a b) b) := @MyNat.succ_mul
#print axioms MyNat.succ_mul
end
