-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: b68f1b234a194932ac384c09f918f685b1a06cc2157348e795333b6af5270fdf
-- Preserve these theorem statements when completing the exercise.

-- MyNat.succ_mul
section
set_option autoImplicit true in
example : ∀ (a b : MyNat),
  @Eq.{1} MyNat (@HMul.hMul.{0, 0, 0} MyNat MyNat MyNat (@instHMul.{0} MyNat MyNat.instMul) (MyNat.succ a) b)
    (@HAdd.hAdd.{0, 0, 0} MyNat MyNat MyNat (@instHAdd.{0} MyNat MyNat.instAdd)
      (@HMul.hMul.{0, 0, 0} MyNat MyNat MyNat (@instHMul.{0} MyNat MyNat.instMul) a b) b) := @MyNat.succ_mul
#print axioms MyNat.succ_mul
end
