-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: 4bae5f1f133f534b781e09594569c199cfa5a374a98b618b6dc149074824cb14
-- Preserve these theorem statements when completing the exercise.

-- MyNat.two_mul
section
set_option autoImplicit true in
example : ∀ (m : MyNat),
  @Eq.{1} MyNat
    (@HMul.hMul.{0, 0, 0} MyNat MyNat MyNat (@instHMul.{0} MyNat MyNat.instMul)
      (@OfNat.ofNat.{0} MyNat (nat_lit 2) (@MyNat.instOfNat (nat_lit 2))) m)
    (@HAdd.hAdd.{0, 0, 0} MyNat MyNat MyNat (@instHAdd.{0} MyNat MyNat.instAdd) m m) := @MyNat.two_mul
#print axioms MyNat.two_mul
end
