-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: 150e9d132c65c55deb35bf38fc0b3d4c67c5dd70ddfebf125244e58428591edc
-- Preserve these theorem statements when completing the exercise.

-- MyNat.zero_mul
section
set_option autoImplicit true in
example : ∀ (m : MyNat),
  @Eq.{1} MyNat
    (@HMul.hMul.{0, 0, 0} MyNat MyNat MyNat (@instHMul.{0} MyNat MyNat.instMul)
      (@OfNat.ofNat.{0} MyNat (nat_lit 0) (@MyNat.instOfNat (nat_lit 0))) m)
    (@OfNat.ofNat.{0} MyNat (nat_lit 0) (@MyNat.instOfNat (nat_lit 0))) := @MyNat.zero_mul
#print axioms MyNat.zero_mul
end
