-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: 6f0e32cc5ab9df6a78185004c9d7d840584fa1ad547b17cd824ee8cdb3473bbb
-- Preserve these theorem statements when completing the exercise.

-- MyNat.zero_mul
section
set_option autoImplicit true in
example : ∀ (m : MyNat),
  @Eq.{1} MyNat
    (@HMul.hMul.{0, 0, 0} MyNat MyNat MyNat (@instHMul.{0} MyNat MyNat.instMul)
      (@OfNat.ofNat.{0} MyNat (nat_lit 0) (@MyNat.instOfNat (nat_lit 0))) m)
    (@OfNat.ofNat.{0} MyNat (nat_lit 0) (@MyNat.instOfNat (nat_lit 0))) := @MyNat.zero_mul
#print axioms MyNat.zero_mul
end
