-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: 67e6efe864818148f994226a941e7a57319b5a11ca63fab6d96a009bf7dea2b6
-- Preserve these theorem statements when completing the exercise.

-- bookTitles_append
section
set_option autoImplicit true in
example : ∀ (l1 l2 : List.{0} Book),
  @Eq.{1} (List.{0} String)
    (bookTitles
      (@HAppend.hAppend.{0, 0, 0} (List.{0} Book) (List.{0} Book) (List.{0} Book)
        (@instHAppendOfAppend.{0} (List.{0} Book) (@List.instAppend.{0} Book)) l1 l2))
    (@HAppend.hAppend.{0, 0, 0} (List.{0} String) (List.{0} String) (List.{0} String)
      (@instHAppendOfAppend.{0} (List.{0} String) (@List.instAppend.{0} String)) (bookTitles l1) (bookTitles l2)) := @bookTitles_append
#print axioms bookTitles_append
end

-- genre_cases
section
set_option autoImplicit true in
example : ∀ (g : Genre), Or (@Eq.{1} Genre g Genre.science) (Or (@Eq.{1} Genre g Genre.history) (@Eq.{1} Genre g Genre.fantasy)) := @genre_cases
#print axioms genre_cases
end

-- pageCount_append
section
set_option autoImplicit true in
example : ∀ (l1 l2 : List.{0} Book),
  @Eq.{1} Nat
    (pageCount
      (@HAppend.hAppend.{0, 0, 0} (List.{0} Book) (List.{0} Book) (List.{0} Book)
        (@instHAppendOfAppend.{0} (List.{0} Book) (@List.instAppend.{0} Book)) l1 l2))
    (@HAdd.hAdd.{0, 0, 0} Nat Nat Nat (@instHAdd.{0} Nat instAddNat) (pageCount l1) (pageCount l2)) := @pageCount_append
#print axioms pageCount_append
end

-- science_ne_history
section
set_option autoImplicit true in
example : @Ne.{1} Genre Genre.science Genre.history := @science_ne_history
#print axioms science_ne_history
end

-- unrated_zero_stars
section
set_option autoImplicit true in
example : ∀ (b : Book),
  @Eq.{1} Rating b.rating Rating.unrated →
    @Eq.{1} Nat b.rating.toNat (@OfNat.ofNat.{0} Nat (nat_lit 0) (instOfNatNat (nat_lit 0))) := @unrated_zero_stars
#print axioms unrated_zero_stars
end

-- withRating_rating
section
set_option autoImplicit true in
example : ∀ (b : Book) (r : Rating), @Eq.{1} Rating (b.withRating r).rating r := @withRating_rating
#print axioms withRating_rating
end

-- zero_not_long
section
set_option autoImplicit true in
example : ∀ (b : Book),
  @Eq.{1} Nat b.pages (@OfNat.ofNat.{0} Nat (nat_lit 0) (instOfNatNat (nat_lit 0))) → @Eq.{1} Bool b.isLong Bool.false := @zero_not_long
#print axioms zero_not_long
end
