-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: cbc813de3f97a8c6025895d99ed60706f6a3c49d6ae524767ac89b0da19148fe
-- Preserve these theorem statements when completing the exercise.

-- add_zero_both
section
set_option autoImplicit true in
example : ∀ (n : Nat),
  And
    (@Eq.{1} Nat
      (@HAdd.hAdd.{0, 0, 0} Nat Nat Nat (@instHAdd.{0} Nat instAddNat)
        (@OfNat.ofNat.{0} Nat (nat_lit 0) (instOfNatNat (nat_lit 0))) n)
      n)
    (@Eq.{1} Nat
      (@HAdd.hAdd.{0, 0, 0} Nat Nat Nat (@instHAdd.{0} Nat instAddNat) n
        (@OfNat.ofNat.{0} Nat (nat_lit 0) (instOfNatNat (nat_lit 0))))
      n) := @add_zero_both
#print axioms add_zero_both
end

-- my_add_assoc
section
set_option autoImplicit true in
example : ∀ (a b c : Nat),
  @Eq.{1} Nat
    (@HAdd.hAdd.{0, 0, 0} Nat Nat Nat (@instHAdd.{0} Nat instAddNat)
      (@HAdd.hAdd.{0, 0, 0} Nat Nat Nat (@instHAdd.{0} Nat instAddNat) a b) c)
    (@HAdd.hAdd.{0, 0, 0} Nat Nat Nat (@instHAdd.{0} Nat instAddNat) a
      (@HAdd.hAdd.{0, 0, 0} Nat Nat Nat (@instHAdd.{0} Nat instAddNat) b c)) := @my_add_assoc
#print axioms my_add_assoc
end

-- my_add_comm
section
set_option autoImplicit true in
example : ∀ (a b : Nat),
  @Eq.{1} Nat (@HAdd.hAdd.{0, 0, 0} Nat Nat Nat (@instHAdd.{0} Nat instAddNat) a b)
    (@HAdd.hAdd.{0, 0, 0} Nat Nat Nat (@instHAdd.{0} Nat instAddNat) b a) := @my_add_comm
#print axioms my_add_comm
end
