-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: eef494b0cf5e5abf1888d204f526b806148c40d9be63033a93439b41b29fed20
-- Preserve these theorem statements when completing the exercise.

-- add_le_add
section
set_option autoImplicit true in
example : ∀ (a b c : Nat),
  @LE.le.{0} Nat instLENat a b →
    @LE.le.{0} Nat instLENat (@HAdd.hAdd.{0, 0, 0} Nat Nat Nat (@instHAdd.{0} Nat instAddNat) a c)
      (@HAdd.hAdd.{0, 0, 0} Nat Nat Nat (@instHAdd.{0} Nat instAddNat) b c) := @add_le_add
#print axioms add_le_add
end

-- le_antisymm'
section
set_option autoImplicit true in
example : ∀ (a b : Nat), @LE.le.{0} Nat instLENat a b → @LE.le.{0} Nat instLENat b a → @Eq.{1} Nat a b := @le_antisymm'
#print axioms le_antisymm'
end

-- le_double
section
set_option autoImplicit true in
example : ∀ (n : Nat),
  @LE.le.{0} Nat instLENat n
    (@HMul.hMul.{0, 0, 0} Nat Nat Nat (@instHMul.{0} Nat instMulNat)
      (@OfNat.ofNat.{0} Nat (nat_lit 2) (instOfNatNat (nat_lit 2))) n) := @le_double
#print axioms le_double
end

-- my_le_trans
section
set_option autoImplicit true in
example : ∀ (a b c : Nat), @LE.le.{0} Nat instLENat a b → @LE.le.{0} Nat instLENat b c → @LE.le.{0} Nat instLENat a c := @my_le_trans
#print axioms my_le_trans
end
