-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: dddeb0d12068df0bf4530ecee04107e5fc4fdb941356d030d7b74066dbea9a61
-- Preserve these theorem statements when completing the exercise.

-- sumTo_formula
section
set_option autoImplicit true in
example : ∀ (n : Nat),
  @Eq.{1} Nat
    (@HMul.hMul.{0, 0, 0} Nat Nat Nat (@instHMul.{0} Nat instMulNat)
      (@OfNat.ofNat.{0} Nat (nat_lit 2) (instOfNatNat (nat_lit 2))) (sumTo n))
    (@HMul.hMul.{0, 0, 0} Nat Nat Nat (@instHMul.{0} Nat instMulNat) n
      (@HAdd.hAdd.{0, 0, 0} Nat Nat Nat (@instHAdd.{0} Nat instAddNat) n
        (@OfNat.ofNat.{0} Nat (nat_lit 1) (instOfNatNat (nat_lit 1))))) := @sumTo_formula
#print axioms sumTo_formula
end

-- sumTo_mono
section
set_option autoImplicit true in
example : ∀ (n : Nat),
  @LE.le.{0} Nat instLENat (sumTo n)
    (sumTo
      (@HAdd.hAdd.{0, 0, 0} Nat Nat Nat (@instHAdd.{0} Nat instAddNat) n
        (@OfNat.ofNat.{0} Nat (nat_lit 1) (instOfNatNat (nat_lit 1))))) := @sumTo_mono
#print axioms sumTo_mono
end
