-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: 607577879baff6512e120fc63b3c0a666e24654c6196927c21803f6f74f03ecd
-- Preserve these theorem statements when completing the exercise.

-- MyNat.add_comm
section
set_option autoImplicit true in
example : ∀ (a b : MyNat),
  @Eq.{1} MyNat (@HAdd.hAdd.{0, 0, 0} MyNat MyNat MyNat (@instHAdd.{0} MyNat MyNat.instAdd) a b)
    (@HAdd.hAdd.{0, 0, 0} MyNat MyNat MyNat (@instHAdd.{0} MyNat MyNat.instAdd) b a) := @MyNat.add_comm
#print axioms MyNat.add_comm
end
