-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: c44bf7fee66f664793dc7cafe4c3683462cdb36d5defdbf5742bc55b5ebc1651
-- Preserve these theorem statements when completing the exercise.

-- MyNat.add_assoc
section
set_option autoImplicit true in
example : ∀ (a b c : MyNat),
  @Eq.{1} MyNat
    (@HAdd.hAdd.{0, 0, 0} MyNat MyNat MyNat (@instHAdd.{0} MyNat MyNat.instAdd)
      (@HAdd.hAdd.{0, 0, 0} MyNat MyNat MyNat (@instHAdd.{0} MyNat MyNat.instAdd) a b) c)
    (@HAdd.hAdd.{0, 0, 0} MyNat MyNat MyNat (@instHAdd.{0} MyNat MyNat.instAdd) a
      (@HAdd.hAdd.{0, 0, 0} MyNat MyNat MyNat (@instHAdd.{0} MyNat MyNat.instAdd) b c)) := @MyNat.add_assoc
#print axioms MyNat.add_assoc
end
