-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: d0d0144d375d2a7c28301d78e05c932e5233ca80924749e3fd626a984d1eaedb
-- Preserve these theorem statements when completing the exercise.

-- MyNat.add_assoc
section
set_option autoImplicit true in
example : ∀ (a b c : MyNat),
  @Eq.{1} MyNat
    (@HAdd.hAdd.{0, 0, 0} MyNat MyNat MyNat (@instHAdd.{0} MyNat MyNat.instAdd)
      (@HAdd.hAdd.{0, 0, 0} MyNat MyNat MyNat (@instHAdd.{0} MyNat MyNat.instAdd) a b) c)
    (@HAdd.hAdd.{0, 0, 0} MyNat MyNat MyNat (@instHAdd.{0} MyNat MyNat.instAdd) a
      (@HAdd.hAdd.{0, 0, 0} MyNat MyNat MyNat (@instHAdd.{0} MyNat MyNat.instAdd) b c)) := @MyNat.add_assoc
#print axioms MyNat.add_assoc
end
