-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: 6a48a51ce44863bad26c3035f7567e6a5d4b8f06782aa51a48310ef14a57be12
-- Preserve these theorem statements when completing the exercise.

-- MyNat.add_right_comm
section
set_option autoImplicit true in
example : ∀ (a b c : MyNat),
  @Eq.{1} MyNat
    (@HAdd.hAdd.{0, 0, 0} MyNat MyNat MyNat (@instHAdd.{0} MyNat MyNat.instAdd)
      (@HAdd.hAdd.{0, 0, 0} MyNat MyNat MyNat (@instHAdd.{0} MyNat MyNat.instAdd) a b) c)
    (@HAdd.hAdd.{0, 0, 0} MyNat MyNat MyNat (@instHAdd.{0} MyNat MyNat.instAdd)
      (@HAdd.hAdd.{0, 0, 0} MyNat MyNat MyNat (@instHAdd.{0} MyNat MyNat.instAdd) a c) b) := @MyNat.add_right_comm
#print axioms MyNat.add_right_comm
end
