-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: a472f391353d1b8e5c9602325a1a0267363bd9d9eac06489affb4f60eab1f4d3
-- Preserve these theorem statements when completing the exercise.

-- MyNat.succ_add
section
set_option autoImplicit true in
example : ∀ (a b : MyNat),
  @Eq.{1} MyNat (@HAdd.hAdd.{0, 0, 0} MyNat MyNat MyNat (@instHAdd.{0} MyNat MyNat.instAdd) (MyNat.succ a) b)
    (MyNat.succ (@HAdd.hAdd.{0, 0, 0} MyNat MyNat MyNat (@instHAdd.{0} MyNat MyNat.instAdd) a b)) := @MyNat.succ_add
#print axioms MyNat.succ_add
end
