-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: 253d1a7372f0af0d38ec242e66c99082fdddc49fe89afec263088bb38521916d
-- Preserve these theorem statements when completing the exercise.

-- MyNat.succ_add
section
set_option autoImplicit true in
example : ∀ (a b : MyNat),
  @Eq.{1} MyNat (@HAdd.hAdd.{0, 0, 0} MyNat MyNat MyNat (@instHAdd.{0} MyNat MyNat.instAdd) (MyNat.succ a) b)
    (MyNat.succ (@HAdd.hAdd.{0, 0, 0} MyNat MyNat MyNat (@instHAdd.{0} MyNat MyNat.instAdd) a b)) := @MyNat.succ_add
#print axioms MyNat.succ_add
end
