-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: 46f549cf4a1a58468d05e21ffae3db4ac3379fcf2b5291c5a8251206e53a3ffb
-- Preserve these theorem statements when completing the exercise.

-- MyNat.zero_add
section
set_option autoImplicit true in
example : ∀ (n : MyNat),
  @Eq.{1} MyNat
    (@HAdd.hAdd.{0, 0, 0} MyNat MyNat MyNat (@instHAdd.{0} MyNat MyNat.instAdd)
      (@OfNat.ofNat.{0} MyNat (nat_lit 0) (@MyNat.instOfNat (nat_lit 0))) n)
    n := @MyNat.zero_add
#print axioms MyNat.zero_add
end
