-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: 4c63d0abc72531657815c3e4a101d1d14f06f94d38c965240b2483a465ceedee
-- Preserve these theorem statements when completing the exercise.

-- MyNat.zero_add
section
set_option autoImplicit true in
example : ∀ (n : MyNat),
  @Eq.{1} MyNat
    (@HAdd.hAdd.{0, 0, 0} MyNat MyNat MyNat (@instHAdd.{0} MyNat MyNat.instAdd)
      (@OfNat.ofNat.{0} MyNat (nat_lit 0) (@MyNat.instOfNat (nat_lit 0))) n)
    n := @MyNat.zero_add
#print axioms MyNat.zero_add
end
