-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: d6fafc349516625e2ef57b090446db19d32ef88b34b0bad63c02e23ab48a522e
-- Preserve these theorem statements when completing the exercise.

-- Analysis.MyReal.add_zero
section
set_option autoImplicit true in
example : ∀ (x : Analysis.MyReal),
  @Eq.{1} Analysis.MyReal
    (@HAdd.hAdd.{0, 0, 0} Analysis.MyReal Analysis.MyReal Analysis.MyReal
      (@instHAdd.{0} Analysis.MyReal Analysis.MyReal.instAdd) x
      (@OfNat.ofNat.{0} Analysis.MyReal (nat_lit 0) (@Zero.toOfNat0.{0} Analysis.MyReal Analysis.MyReal.instZero)))
    x := @Analysis.MyReal.add_zero
#print axioms Analysis.MyReal.add_zero
end
