-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: cf22c0d3973f90a6b1b94db0409ad95df58232a983e8afa250277d92ef24057c
-- Preserve these theorem statements when completing the exercise.

-- Analysis.MyReal.add_zero
section
set_option autoImplicit true in
example : ∀ (x : Analysis.MyReal),
  @Eq.{1} Analysis.MyReal
    (@HAdd.hAdd.{0, 0, 0} Analysis.MyReal Analysis.MyReal Analysis.MyReal
      (@instHAdd.{0} Analysis.MyReal Analysis.MyReal.instAdd) x
      (@OfNat.ofNat.{0} Analysis.MyReal (nat_lit 0) (@Zero.toOfNat0.{0} Analysis.MyReal Analysis.MyReal.instZero)))
    x := @Analysis.MyReal.add_zero
#print axioms Analysis.MyReal.add_zero
end
