-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: 209107d89841372f409f47157e1e36c637db6c8a7ef999a5b4da856a75bd7ab5
-- Preserve these theorem statements when completing the exercise.

-- Analysis.MyReal.add_comm
section
set_option autoImplicit true in
example : ∀ (x y : Analysis.MyReal),
  @Eq.{1} Analysis.MyReal
    (@HAdd.hAdd.{0, 0, 0} Analysis.MyReal Analysis.MyReal Analysis.MyReal
      (@instHAdd.{0} Analysis.MyReal Analysis.MyReal.instAdd) x y)
    (@HAdd.hAdd.{0, 0, 0} Analysis.MyReal Analysis.MyReal Analysis.MyReal
      (@instHAdd.{0} Analysis.MyReal Analysis.MyReal.instAdd) y x) := @Analysis.MyReal.add_comm
#print axioms Analysis.MyReal.add_comm
end
