-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: 0d8d0075ead3f75e58116e9147f8f78591c0b03682a98586a9637815b2e216ae
-- Preserve these theorem statements when completing the exercise.

-- Analysis.MyReal.add_assoc
section
set_option autoImplicit true in
example : ∀ (x y z : Analysis.MyReal),
  @Eq.{1} Analysis.MyReal
    (@HAdd.hAdd.{0, 0, 0} Analysis.MyReal Analysis.MyReal Analysis.MyReal
      (@instHAdd.{0} Analysis.MyReal Analysis.MyReal.instAdd)
      (@HAdd.hAdd.{0, 0, 0} Analysis.MyReal Analysis.MyReal Analysis.MyReal
        (@instHAdd.{0} Analysis.MyReal Analysis.MyReal.instAdd) x y)
      z)
    (@HAdd.hAdd.{0, 0, 0} Analysis.MyReal Analysis.MyReal Analysis.MyReal
      (@instHAdd.{0} Analysis.MyReal Analysis.MyReal.instAdd) x
      (@HAdd.hAdd.{0, 0, 0} Analysis.MyReal Analysis.MyReal Analysis.MyReal
        (@instHAdd.{0} Analysis.MyReal Analysis.MyReal.instAdd) y z)) := @Analysis.MyReal.add_assoc
#print axioms Analysis.MyReal.add_assoc
end
