-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: 4e3ebcfe65cebd30db5daa4b9e50e1452e982953ad6598bc88d3a71d7ccc10fb
-- Preserve these theorem statements when completing the exercise.

-- Analysis.MyReal.left_distrib
section
set_option autoImplicit true in
example : ∀ (x y z : Analysis.MyReal),
  @Eq.{1} Analysis.MyReal
    (@HMul.hMul.{0, 0, 0} Analysis.MyReal Analysis.MyReal Analysis.MyReal
      (@instHMul.{0} Analysis.MyReal Analysis.MyReal.instMul) x
      (@HAdd.hAdd.{0, 0, 0} Analysis.MyReal Analysis.MyReal Analysis.MyReal
        (@instHAdd.{0} Analysis.MyReal Analysis.MyReal.instAdd) y z))
    (@HAdd.hAdd.{0, 0, 0} Analysis.MyReal Analysis.MyReal Analysis.MyReal
      (@instHAdd.{0} Analysis.MyReal Analysis.MyReal.instAdd)
      (@HMul.hMul.{0, 0, 0} Analysis.MyReal Analysis.MyReal Analysis.MyReal
        (@instHMul.{0} Analysis.MyReal Analysis.MyReal.instMul) x y)
      (@HMul.hMul.{0, 0, 0} Analysis.MyReal Analysis.MyReal Analysis.MyReal
        (@instHMul.{0} Analysis.MyReal Analysis.MyReal.instMul) x z)) := @Analysis.MyReal.left_distrib
#print axioms Analysis.MyReal.left_distrib
end
