-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: b428b3dd7922a474b27dfa578fb4b0616e053c066c03d2c0a65674f553f88bd5
-- Preserve these theorem statements when completing the exercise.

-- Analysis.MyReal.mul_one
section
set_option autoImplicit true in
example : ∀ (x : Analysis.MyReal),
  @Eq.{1} Analysis.MyReal
    (@HMul.hMul.{0, 0, 0} Analysis.MyReal Analysis.MyReal Analysis.MyReal
      (@instHMul.{0} Analysis.MyReal Analysis.MyReal.instMul) x
      (@OfNat.ofNat.{0} Analysis.MyReal (nat_lit 1) (@One.toOfNat1.{0} Analysis.MyReal Analysis.MyReal.instOne)))
    x := @Analysis.MyReal.mul_one
#print axioms Analysis.MyReal.mul_one
end
