-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: 0e51e46cdc0160891227c8353dbe9fc22f799b5fa8647a980d632a15a3637d08
-- Preserve these theorem statements when completing the exercise.

-- Analysis.MyReal.mul_assoc
section
set_option autoImplicit true in
example : ∀ (x y z : Analysis.MyReal),
  @Eq.{1} Analysis.MyReal
    (@HMul.hMul.{0, 0, 0} Analysis.MyReal Analysis.MyReal Analysis.MyReal
      (@instHMul.{0} Analysis.MyReal Analysis.MyReal.instMul)
      (@HMul.hMul.{0, 0, 0} Analysis.MyReal Analysis.MyReal Analysis.MyReal
        (@instHMul.{0} Analysis.MyReal Analysis.MyReal.instMul) x y)
      z)
    (@HMul.hMul.{0, 0, 0} Analysis.MyReal Analysis.MyReal Analysis.MyReal
      (@instHMul.{0} Analysis.MyReal Analysis.MyReal.instMul) x
      (@HMul.hMul.{0, 0, 0} Analysis.MyReal Analysis.MyReal Analysis.MyReal
        (@instHMul.{0} Analysis.MyReal Analysis.MyReal.instMul) y z)) := @Analysis.MyReal.mul_assoc
#print axioms Analysis.MyReal.mul_assoc
end
