-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: 123e8a02ea1ea04b37902a809a8d3cc24bbf44faa0549e22c41fb6266e2d4767
-- Preserve these theorem statements when completing the exercise.

-- Analysis.MyReal.mul_comm
section
set_option autoImplicit true in
example : ∀ (x y : Analysis.MyReal),
  @Eq.{1} Analysis.MyReal
    (@HMul.hMul.{0, 0, 0} Analysis.MyReal Analysis.MyReal Analysis.MyReal
      (@instHMul.{0} Analysis.MyReal Analysis.MyReal.instMul) x y)
    (@HMul.hMul.{0, 0, 0} Analysis.MyReal Analysis.MyReal Analysis.MyReal
      (@instHMul.{0} Analysis.MyReal Analysis.MyReal.instMul) y x) := @Analysis.MyReal.mul_comm
#print axioms Analysis.MyReal.mul_comm
end
