-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: 91e4b9c0656a67bcb6497b1086f4b18a9df2dbf06dad71f6656b4369d408d353
-- Preserve these theorem statements when completing the exercise.

-- Analysis.MyReal.neg_add_cancel
section
set_option autoImplicit true in
example : ∀ (x : Analysis.MyReal),
  @Eq.{1} Analysis.MyReal
    (@HAdd.hAdd.{0, 0, 0} Analysis.MyReal Analysis.MyReal Analysis.MyReal
      (@instHAdd.{0} Analysis.MyReal Analysis.MyReal.instAdd) (@Neg.neg.{0} Analysis.MyReal Analysis.MyReal.instNeg x)
      x)
    (@OfNat.ofNat.{0} Analysis.MyReal (nat_lit 0) (@Zero.toOfNat0.{0} Analysis.MyReal Analysis.MyReal.instZero)) := @Analysis.MyReal.neg_add_cancel
#print axioms Analysis.MyReal.neg_add_cancel
end
