-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: ee5d87d22264b5435f65d37f376750242624e833abd2bc41510a816eb8ddbe49
-- Preserve these theorem statements when completing the exercise.

-- Analysis.MyReal.ofRat_mul
section
set_option autoImplicit true in
example : ∀ (a b : Analysis.MyRat),
  @Eq.{1} Analysis.MyReal
    (Analysis.MyReal.ofRat
      (@HMul.hMul.{0, 0, 0} Analysis.MyRat Analysis.MyRat Analysis.MyRat
        (@instHMul.{0} Analysis.MyRat Analysis.MyRat.instMul) a b))
    (@HMul.hMul.{0, 0, 0} Analysis.MyReal Analysis.MyReal Analysis.MyReal
      (@instHMul.{0} Analysis.MyReal Analysis.MyReal.instMul) (Analysis.MyReal.ofRat a) (Analysis.MyReal.ofRat b)) := @Analysis.MyReal.ofRat_mul
#print axioms Analysis.MyReal.ofRat_mul
end
