-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: ab8736b95ece3c8fcfa6c7239b5f431555307298382829786d003284f11638b6
-- Preserve these theorem statements when completing the exercise.

-- Analysis.MyReal.ofRat_add
section
set_option autoImplicit true in
example : ∀ (a b : Analysis.MyRat),
  @Eq.{1} Analysis.MyReal
    (Analysis.MyReal.ofRat
      (@HAdd.hAdd.{0, 0, 0} Analysis.MyRat Analysis.MyRat Analysis.MyRat
        (@instHAdd.{0} Analysis.MyRat Analysis.MyRat.instAdd) a b))
    (@HAdd.hAdd.{0, 0, 0} Analysis.MyReal Analysis.MyReal Analysis.MyReal
      (@instHAdd.{0} Analysis.MyReal Analysis.MyReal.instAdd) (Analysis.MyReal.ofRat a) (Analysis.MyReal.ofRat b)) := @Analysis.MyReal.ofRat_add
#print axioms Analysis.MyReal.ofRat_add
end
