-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: d447efdd22cee5cbaddb4fe0b0c05bee4c17167a336e845a99ee812e763d82d7
-- Preserve these theorem statements when completing the exercise.

-- Analysis.MyReal.one_mul
section
set_option autoImplicit true in
example : ∀ (x : Analysis.MyReal),
  @Eq.{1} Analysis.MyReal
    (@HMul.hMul.{0, 0, 0} Analysis.MyReal Analysis.MyReal Analysis.MyReal
      (@instHMul.{0} Analysis.MyReal Analysis.MyReal.instMul)
      (@OfNat.ofNat.{0} Analysis.MyReal (nat_lit 1) (@One.toOfNat1.{0} Analysis.MyReal Analysis.MyReal.instOne)) x)
    x := @Analysis.MyReal.one_mul
#print axioms Analysis.MyReal.one_mul
end
