-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: d7c1529f13fa1f906be092fbed6e8e5b864b9b5610baea3dfd777c04d4836e0b
-- Preserve these theorem statements when completing the exercise.

-- Analysis.MyReal.zero_add
section
set_option autoImplicit true in
example : ∀ (x : Analysis.MyReal),
  @Eq.{1} Analysis.MyReal
    (@HAdd.hAdd.{0, 0, 0} Analysis.MyReal Analysis.MyReal Analysis.MyReal
      (@instHAdd.{0} Analysis.MyReal Analysis.MyReal.instAdd)
      (@OfNat.ofNat.{0} Analysis.MyReal (nat_lit 0) (@Zero.toOfNat0.{0} Analysis.MyReal Analysis.MyReal.instZero)) x)
    x := @Analysis.MyReal.zero_add
#print axioms Analysis.MyReal.zero_add
end
