-- Generated by scripts/generate-contracts.py; do not edit by hand.
-- Reference SHA-256: 269772924670ddece369ccd40c979e18bb707a64f3d86372ae7c9d94b2fc972e
-- Preserve these theorem statements when completing the exercise.

-- Tree.depth_le_size
section
set_option autoImplicit true in
example : ∀ {α : Type} (t : Tree α), @LE.le.{0} Nat instLENat (@Tree.depth α t) (@Tree.size α t) := @Tree.depth_le_size
#print axioms Tree.depth_le_size
end

-- Tree.depth_mirror
section
set_option autoImplicit true in
example : ∀ {α : Type} (t : Tree α), @Eq.{1} Nat (@Tree.depth α (@Tree.mirror α t)) (@Tree.depth α t) := @Tree.depth_mirror
#print axioms Tree.depth_mirror
end

-- Tree.mirror_mirror
section
set_option autoImplicit true in
example : ∀ {α : Type} (t : Tree α), @Eq.{1} (Tree α) (@Tree.mirror α (@Tree.mirror α t)) t := @Tree.mirror_mirror
#print axioms Tree.mirror_mirror
end

-- Tree.node_has_element
section
set_option autoImplicit true in
example : ∀ {α : Type} (l : Tree α) (v : α) (r : Tree α),
  @Exists.{1} α fun x =>
    @Membership.mem.{0, 0} α (List.{0} α) (@List.instMembership.{0} α) (@Tree.toList α (@Tree.node α l v r)) x := @Tree.node_has_element
#print axioms Tree.node_has_element
end

-- Tree.size_leaf
section
set_option autoImplicit true in
example : ∀ {α : Type}, @Eq.{1} Nat (@Tree.size α (@Tree.leaf α)) (@OfNat.ofNat.{0} Nat (nat_lit 0) (instOfNatNat (nat_lit 0))) := @Tree.size_leaf
#print axioms Tree.size_leaf
end

-- Tree.size_mirror
section
set_option autoImplicit true in
example : ∀ {α : Type} (t : Tree α), @Eq.{1} Nat (@Tree.size α (@Tree.mirror α t)) (@Tree.size α t) := @Tree.size_mirror
#print axioms Tree.size_mirror
end

-- Tree.size_node_pos
section
set_option autoImplicit true in
example : ∀ {α : Type} (l : Tree α) (v : α) (r : Tree α),
  @GE.ge.{0} Nat instLENat (@Tree.size α (@Tree.node α l v r))
    (@OfNat.ofNat.{0} Nat (nat_lit 1) (instOfNatNat (nat_lit 1))) := @Tree.size_node_pos
#print axioms Tree.size_node_pos
end

-- Tree.size_zero_iff_leaf
section
set_option autoImplicit true in
example : ∀ {α : Type} (t : Tree α),
  Iff (@Eq.{1} Nat (@Tree.size α t) (@OfNat.ofNat.{0} Nat (nat_lit 0) (instOfNatNat (nat_lit 0))))
    (@Eq.{1} (Tree α) t (@Tree.leaf α)) := @Tree.size_zero_iff_leaf
#print axioms Tree.size_zero_iff_leaf
end

-- Tree.toList_leaf
section
set_option autoImplicit true in
example : ∀ {α : Type}, @Eq.{1} (List.{0} α) (@Tree.toList α (@Tree.leaf α)) (@List.nil.{0} α) := @Tree.toList_leaf
#print axioms Tree.toList_leaf
end

-- Tree.toList_length
section
set_option autoImplicit true in
example : ∀ {α : Type} (t : Tree α), @Eq.{1} Nat (@List.length.{0} α (@Tree.toList α t)) (@Tree.size α t) := @Tree.toList_length
#print axioms Tree.toList_length
end

-- sample_size
section
set_option autoImplicit true in
example : @Eq.{1} Nat (@Tree.size Nat sampleTree) (@OfNat.ofNat.{0} Nat (nat_lit 3) (instOfNatNat (nat_lit 3))) := @sample_size
#print axioms sample_size
end
